// Generated by client/core-ts/scripts/operations.ts from client/core-ts/src/ops.ts. Do not edit.
export interface OperationParams {
  "session.stop": { key: string };
  "session.warm": { key: string };
  "session.evict": { key: string };
  "session.delete": { key: string };
  "session.settings": { key: string; profile?: string | null | undefined; model?: string | null | undefined; effort?: string | null | undefined; fast?: boolean | null | undefined };
  "chat.archive": { archived?: boolean | null | undefined; session: string; thread?: number | null | undefined };
  "chat.keep": { thread: number };
  "chat.rename": { session?: string | null | undefined; title?: string | null | undefined; thread?: number | null | undefined };
  "chat.pin": { pinned?: boolean | null | undefined; session: string };
  "decision.dismiss": { thread: number; seq: number };
  "decision.close": { thread: number; seq: number; option: string };
  "session.new": { runtime?: string | null | undefined; profile?: string | null | undefined; model?: string | null | undefined; effort?: string | null | undefined; fast?: boolean | null | undefined };
  "chats.archived": {  };
  "chat.forSession": { session?: string | null | undefined };
  "widget.state": { key: string; path: string };
  "widget.setState": { key: string; path?: string | null | undefined; state?: unknown };
  "machineSessions.list": {  };
  "machineSessions.read": { runtime: string; id: string; limit?: number | null | undefined };
  "machineSessions.continue": { runtime?: string | null | undefined; id?: string | null | undefined };
  "automaticDecisions.save": { input: unknown };
  "automaticDecisions.refresh": {  };
  "connect.create": { input?: unknown; id?: string | null | undefined };
  "connect.put": { id: string; input?: unknown };
  "connect.delete": { id: string };
  "connect.reconnect": { id: string };
  "connect.bindSession": { connect: string; session?: string | null | undefined; title?: string | null | undefined };
  "connect.putSlackApp": { connect: string; input?: unknown };
  "slack.verify": { connect?: string | null | undefined; install?: string | null | undefined; appToken?: string | null | undefined; botToken?: string | null | undefined };
  "slack.makeApp": { team?: string | null | undefined; settings?: unknown; icon?: string | null | undefined };
  "slack.dropApp": { appId: string };
  "slack.installed": { code?: string | null | undefined; state?: string | null | undefined };
  "slack.addConfigToken": { refreshToken?: string | null | undefined };
  "slack.removeConfigToken": { team: string };
  "slack.people": {  };
  "slack.createAppUrl": { name: string };
  "slack.identity": { bound?: boolean | null | undefined; user: string };
  "profile.add": { runtime?: string | null | undefined; access?: unknown };
  "profile.useMachineLogin": { runtime?: string | null | undefined };
  "profile.put": { id: string; input?: unknown };
  "profile.addModel": { id: string; model: string };
  "profile.delete": { id: string };
  "profile.resetQuota": { id: string };
  "profile.quota": { id: string };
  "profile.check": { id: string };
  "profile.login": { id: string };
  "profile.cancelLogin": { id: string };
  "profile.loginCode": { id: string; code?: string | null | undefined };
  "login.new": { runtime?: string | null | undefined };
  "login.code": { id: string; code?: string | null | undefined };
  "login.drop": { id: string };
  "job.get": { id: string };
  "job.log": { id: string; lines: number };
  "job.stop": { id: string };
  "job.clearEnded": { session: string };
  "memory.get": {  };
  "footprint.scan": {  };
  "footprint.rebuild": { keys?: string[] | null | undefined };
  "footprint.delete": { keys?: string[] | null | undefined };
  "footprint.evict": { keys?: string[] | null | undefined };
  "software.update": { id?: string | null | undefined };
  "software.updateAll": {  };
  "software.check": {  };
  "software.channel": { channel?: string | null | undefined };
  "software.auto": { on?: boolean | null | undefined };
  "workspace.create": { name?: string | null | undefined; invite_code?: string | null | undefined };
  "workspace.rename": { workspace: string; name?: string | null | undefined };
  "workspace.delete": { workspace: string };
  "workspace.invite": { workspace: string; role?: string | null | undefined; email?: string | null | undefined };
  "workspace.addMembers": { workspace: string; role?: string | null | undefined; emails?: string[] | null | undefined };
  "workspace.removeAdded": { workspace: string; email: string };
  "workspace.revokeInvitation": { workspace: string; invitation: string };
  "workspace.setRole": { workspace: string; member: string; role?: string | null | undefined };
  "workspace.removeMember": { workspace: string; member: string };
  "workspace.enroll": { workspace: string; name?: string | null | undefined };
  "workspace.renameStation": { workspace: string; station: string; name?: string | null | undefined };
  "workspace.removeStation": { workspace: string; station: string };
  "invitation.preview": { token?: string | null | undefined };
  "invitation.accept": { id?: string | null | undefined; token?: string | null | undefined };
  "invitation.decline": { id: string };
  "loginSession.revoke": { id: string };
  "admin.me": {  };
  "admin.createCode": { note?: string | null | undefined; days?: number | null | undefined };
  "admin.revokeCode": { code: string };
  "admin.setBeta": { user: string; on?: boolean | null | undefined };
  "admin.setMayCreate": { user: string; on?: boolean | null | undefined };
  "admin.block": { user: string; on?: boolean | null | undefined };
  "admin.deleteWorkspace": { workspace: string };
  "admin.feedbackStatus": { id: string; status?: string | null | undefined };
}

export const UNTRACKED_OPERATIONS = new Set(["admin.me", "chats.archived", "job.get", "job.log", "login.drop", "machineSessions.list", "machineSessions.read", "memory.get", "session.warm", "slack.createAppUrl", "slack.people", "widget.setState", "widget.state"]);

type Call = (name: string, params: Record<string, unknown>) => Promise<unknown>;

export function bindStationOperations(call: Call) {
  return {
    sessionStop: <T = unknown>(params: OperationParams["session.stop"]) => call("session.stop", params) as Promise<T>,
    sessionWarm: <T = unknown>(params: OperationParams["session.warm"]) => call("session.warm", params) as Promise<T>,
    sessionEvict: <T = unknown>(params: OperationParams["session.evict"]) => call("session.evict", params) as Promise<T>,
    sessionDelete: <T = unknown>(params: OperationParams["session.delete"]) => call("session.delete", params) as Promise<T>,
    sessionSettings: <T = unknown>(params: OperationParams["session.settings"]) => call("session.settings", params) as Promise<T>,
    chatArchive: <T = unknown>(params: OperationParams["chat.archive"]) => call("chat.archive", params) as Promise<T>,
    chatKeep: <T = unknown>(params: OperationParams["chat.keep"]) => call("chat.keep", params) as Promise<T>,
    chatRename: <T = unknown>(params: OperationParams["chat.rename"] = {}) => call("chat.rename", params) as Promise<T>,
    chatPin: <T = unknown>(params: OperationParams["chat.pin"]) => call("chat.pin", params) as Promise<T>,
    decisionDismiss: <T = unknown>(params: OperationParams["decision.dismiss"]) => call("decision.dismiss", params) as Promise<T>,
    decisionClose: <T = unknown>(params: OperationParams["decision.close"]) => call("decision.close", params) as Promise<T>,
    sessionNew: <T = unknown>(params: OperationParams["session.new"] = {}) => call("session.new", params) as Promise<T>,
    chatsArchived: <T = unknown>(params: OperationParams["chats.archived"] = {}) => call("chats.archived", params) as Promise<T>,
    chatForSession: <T = unknown>(params: OperationParams["chat.forSession"] = {}) => call("chat.forSession", params) as Promise<T>,
    widgetState: <T = unknown>(params: OperationParams["widget.state"]) => call("widget.state", params) as Promise<T>,
    widgetSetState: <T = unknown>(params: OperationParams["widget.setState"]) => call("widget.setState", params) as Promise<T>,
    machineSessionsList: <T = unknown>(params: OperationParams["machineSessions.list"] = {}) => call("machineSessions.list", params) as Promise<T>,
    machineSessionsRead: <T = unknown>(params: OperationParams["machineSessions.read"]) => call("machineSessions.read", params) as Promise<T>,
    machineSessionsContinue: <T = unknown>(params: OperationParams["machineSessions.continue"] = {}) => call("machineSessions.continue", params) as Promise<T>,
    automaticDecisionsSave: <T = unknown>(params: OperationParams["automaticDecisions.save"]) => call("automaticDecisions.save", params) as Promise<T>,
    automaticDecisionsRefresh: <T = unknown>(params: OperationParams["automaticDecisions.refresh"] = {}) => call("automaticDecisions.refresh", params) as Promise<T>,
    connectCreate: <T = unknown>(params: OperationParams["connect.create"] = {}) => call("connect.create", params) as Promise<T>,
    connectPut: <T = unknown>(params: OperationParams["connect.put"]) => call("connect.put", params) as Promise<T>,
    connectDelete: <T = unknown>(params: OperationParams["connect.delete"]) => call("connect.delete", params) as Promise<T>,
    connectReconnect: <T = unknown>(params: OperationParams["connect.reconnect"]) => call("connect.reconnect", params) as Promise<T>,
    connectBindSession: <T = unknown>(params: OperationParams["connect.bindSession"]) => call("connect.bindSession", params) as Promise<T>,
    connectPutSlackApp: <T = unknown>(params: OperationParams["connect.putSlackApp"]) => call("connect.putSlackApp", params) as Promise<T>,
    slackVerify: <T = unknown>(params: OperationParams["slack.verify"] = {}) => call("slack.verify", params) as Promise<T>,
    slackMakeApp: <T = unknown>(params: OperationParams["slack.makeApp"] = {}) => call("slack.makeApp", params) as Promise<T>,
    slackDropApp: <T = unknown>(params: OperationParams["slack.dropApp"]) => call("slack.dropApp", params) as Promise<T>,
    slackInstalled: <T = unknown>(params: OperationParams["slack.installed"] = {}) => call("slack.installed", params) as Promise<T>,
    slackAddConfigToken: <T = unknown>(params: OperationParams["slack.addConfigToken"] = {}) => call("slack.addConfigToken", params) as Promise<T>,
    slackRemoveConfigToken: <T = unknown>(params: OperationParams["slack.removeConfigToken"]) => call("slack.removeConfigToken", params) as Promise<T>,
    slackPeople: <T = unknown>(params: OperationParams["slack.people"] = {}) => call("slack.people", params) as Promise<T>,
    slackCreateAppUrl: <T = unknown>(params: OperationParams["slack.createAppUrl"]) => call("slack.createAppUrl", params) as Promise<T>,
    slackIdentity: <T = unknown>(params: OperationParams["slack.identity"]) => call("slack.identity", params) as Promise<T>,
    profileAdd: <T = unknown>(params: OperationParams["profile.add"] = {}) => call("profile.add", params) as Promise<T>,
    profileUseMachineLogin: <T = unknown>(params: OperationParams["profile.useMachineLogin"] = {}) => call("profile.useMachineLogin", params) as Promise<T>,
    profilePut: <T = unknown>(params: OperationParams["profile.put"]) => call("profile.put", params) as Promise<T>,
    profileAddModel: <T = unknown>(params: OperationParams["profile.addModel"]) => call("profile.addModel", params) as Promise<T>,
    profileDelete: <T = unknown>(params: OperationParams["profile.delete"]) => call("profile.delete", params) as Promise<T>,
    profileResetQuota: <T = unknown>(params: OperationParams["profile.resetQuota"]) => call("profile.resetQuota", params) as Promise<T>,
    profileQuota: <T = unknown>(params: OperationParams["profile.quota"]) => call("profile.quota", params) as Promise<T>,
    profileCheck: <T = unknown>(params: OperationParams["profile.check"]) => call("profile.check", params) as Promise<T>,
    profileLogin: <T = unknown>(params: OperationParams["profile.login"]) => call("profile.login", params) as Promise<T>,
    profileCancelLogin: <T = unknown>(params: OperationParams["profile.cancelLogin"]) => call("profile.cancelLogin", params) as Promise<T>,
    profileLoginCode: <T = unknown>(params: OperationParams["profile.loginCode"]) => call("profile.loginCode", params) as Promise<T>,
    loginNew: <T = unknown>(params: OperationParams["login.new"] = {}) => call("login.new", params) as Promise<T>,
    loginCode: <T = unknown>(params: OperationParams["login.code"]) => call("login.code", params) as Promise<T>,
    loginDrop: <T = unknown>(params: OperationParams["login.drop"]) => call("login.drop", params) as Promise<T>,
    jobGet: <T = unknown>(params: OperationParams["job.get"]) => call("job.get", params) as Promise<T>,
    jobLog: <T = unknown>(params: OperationParams["job.log"]) => call("job.log", params) as Promise<T>,
    jobStop: <T = unknown>(params: OperationParams["job.stop"]) => call("job.stop", params) as Promise<T>,
    jobClearEnded: <T = unknown>(params: OperationParams["job.clearEnded"]) => call("job.clearEnded", params) as Promise<T>,
    memoryGet: <T = unknown>(params: OperationParams["memory.get"] = {}) => call("memory.get", params) as Promise<T>,
    footprintScan: <T = unknown>(params: OperationParams["footprint.scan"] = {}) => call("footprint.scan", params) as Promise<T>,
    footprintRebuild: <T = unknown>(params: OperationParams["footprint.rebuild"] = {}) => call("footprint.rebuild", params) as Promise<T>,
    footprintDelete: <T = unknown>(params: OperationParams["footprint.delete"] = {}) => call("footprint.delete", params) as Promise<T>,
    footprintEvict: <T = unknown>(params: OperationParams["footprint.evict"] = {}) => call("footprint.evict", params) as Promise<T>,
    softwareUpdate: <T = unknown>(params: OperationParams["software.update"] = {}) => call("software.update", params) as Promise<T>,
    softwareUpdateAll: <T = unknown>(params: OperationParams["software.updateAll"] = {}) => call("software.updateAll", params) as Promise<T>,
    softwareCheck: <T = unknown>(params: OperationParams["software.check"] = {}) => call("software.check", params) as Promise<T>,
    softwareChannel: <T = unknown>(params: OperationParams["software.channel"] = {}) => call("software.channel", params) as Promise<T>,
    softwareAuto: <T = unknown>(params: OperationParams["software.auto"] = {}) => call("software.auto", params) as Promise<T>,
  };
}

export function bindCloudOperations(call: Call) {
  return {
    workspaceCreate: <T = unknown>(params: OperationParams["workspace.create"] = {}) => call("workspace.create", params) as Promise<T>,
    workspaceRename: <T = unknown>(params: OperationParams["workspace.rename"]) => call("workspace.rename", params) as Promise<T>,
    workspaceDelete: <T = unknown>(params: OperationParams["workspace.delete"]) => call("workspace.delete", params) as Promise<T>,
    workspaceInvite: <T = unknown>(params: OperationParams["workspace.invite"]) => call("workspace.invite", params) as Promise<T>,
    workspaceAddMembers: <T = unknown>(params: OperationParams["workspace.addMembers"]) => call("workspace.addMembers", params) as Promise<T>,
    workspaceRemoveAdded: <T = unknown>(params: OperationParams["workspace.removeAdded"]) => call("workspace.removeAdded", params) as Promise<T>,
    workspaceRevokeInvitation: <T = unknown>(params: OperationParams["workspace.revokeInvitation"]) => call("workspace.revokeInvitation", params) as Promise<T>,
    workspaceSetRole: <T = unknown>(params: OperationParams["workspace.setRole"]) => call("workspace.setRole", params) as Promise<T>,
    workspaceRemoveMember: <T = unknown>(params: OperationParams["workspace.removeMember"]) => call("workspace.removeMember", params) as Promise<T>,
    workspaceEnroll: <T = unknown>(params: OperationParams["workspace.enroll"]) => call("workspace.enroll", params) as Promise<T>,
    workspaceRenameStation: <T = unknown>(params: OperationParams["workspace.renameStation"]) => call("workspace.renameStation", params) as Promise<T>,
    workspaceRemoveStation: <T = unknown>(params: OperationParams["workspace.removeStation"]) => call("workspace.removeStation", params) as Promise<T>,
    invitationPreview: <T = unknown>(params: OperationParams["invitation.preview"] = {}) => call("invitation.preview", params) as Promise<T>,
    invitationAccept: <T = unknown>(params: OperationParams["invitation.accept"] = {}) => call("invitation.accept", params) as Promise<T>,
    invitationDecline: <T = unknown>(params: OperationParams["invitation.decline"]) => call("invitation.decline", params) as Promise<T>,
    loginSessionRevoke: <T = unknown>(params: OperationParams["loginSession.revoke"]) => call("loginSession.revoke", params) as Promise<T>,
    adminMe: <T = unknown>(params: OperationParams["admin.me"] = {}) => call("admin.me", params) as Promise<T>,
    adminCreateCode: <T = unknown>(params: OperationParams["admin.createCode"] = {}) => call("admin.createCode", params) as Promise<T>,
    adminRevokeCode: <T = unknown>(params: OperationParams["admin.revokeCode"]) => call("admin.revokeCode", params) as Promise<T>,
    adminSetBeta: <T = unknown>(params: OperationParams["admin.setBeta"]) => call("admin.setBeta", params) as Promise<T>,
    adminSetMayCreate: <T = unknown>(params: OperationParams["admin.setMayCreate"]) => call("admin.setMayCreate", params) as Promise<T>,
    adminBlock: <T = unknown>(params: OperationParams["admin.block"]) => call("admin.block", params) as Promise<T>,
    adminDeleteWorkspace: <T = unknown>(params: OperationParams["admin.deleteWorkspace"]) => call("admin.deleteWorkspace", params) as Promise<T>,
    adminFeedbackStatus: <T = unknown>(params: OperationParams["admin.feedbackStatus"]) => call("admin.feedbackStatus", params) as Promise<T>,
  };
}
