/*
 Generated by client/core-ts/scripts/shapes.ts from client/core-ts/src/shapes/schema.ts: do not edit.
*/

/** Whose account a profile runs on. */
export type AccessKind = "subscription" | "opencode-go" | "anthropic-api" | "env" | "api-provider";

export interface Access {
	/** subscription | opencode-go | anthropic-api | env | api-provider */
	kind: AccessKind;
	key: string;
	/** The provider of an `api-provider` (shapes/providers.ts); an older core reads such a profile as `env` and drops this. */
	provider?: string;
	/** Its address, where the provider has none of its own (Azure, Cloudflare, custom). */
	endpoint?: string;
	/** At such an address, the protocol it speaks there: chat_completions, responses or anthropic. */
	protocol?: string;
}

/**
 * What an agent at work does now (activity.ts): `key` names the thing (a step, or where the turn stands), `text` says
 * it; the same thing keeps its key while its words change.
 */
export interface ActivityNow {
	key: string;
	text: string;
}

/** What an agent at work is doing, as a chat shows it (activity.ts). */
export interface Activity {
	now: ActivityNow;
}

/**
 * This phone's adb as lent to a station's agents (the `adbShare` topic; client/core-ts/src/adb.ts, docs/adb-share.md).
 * `phase`: `off`, `connecting` (the link opening, or opening again after it went: `message` says why) or `offered`;
 * `adb`, as the station's adb holds the phone once offered: `connecting`, `connected`, `unpaired`, `unauthorized`,
 * `off` (Wireless debugging is), `missing` (no adb there) or `failed`, `message` saying more. Stopped by itself (its hour up, a station too old), it
 * is off with why in `message`. `serial`: what the agents reach it at on the station; `until`: when it stops.
 */
export interface AdbShareView {
	sharing: boolean;
	station?: string;
	phase: string;
	serial?: string;
	adb?: string;
	message?: string;
	until?: number;
	tunnels: number;
	connectPort?: number;
	pairPort?: number;
}

/** A runtime. */
export type RuntimeKind = "claude" | "codex";

export interface AgentProcess {
	pgid: number;
	startedAt: number;
	runtime: RuntimeKind;
	label: string;
	rssMb?: number;
}

/**
 * An agent waiting on work it started, which brings it back: since its turn ended, and at most how many seconds
 * until it is asked again (absent from a station yet to update).
 */
export interface AgentWait {
	since: number;
	seconds?: number;
	/** What it waits for in words, as its activity line says it (在等：CI 跑完; 等待中 from a station that does not say). */
	text?: string;
}

/**
 * A provider a key can be added for (shapes/providers.ts); a station lists its ids (`id`, `name`, `group`), the core fills the
 * rest in as the picker's tiles.
 */
export interface ApiProvider {
	id: string;
	name: string;
	/** labs | china | gateways | cloud | inference | local */
	group: string;
	/** The mark of its maker; none: the generic one. */
	mark?: string;
	/** How a profile on it is made: api-provider | opencode-go | anthropic-api | env (variables by hand). */
	kind?: string;
	/** It has a key to add, and/or a subscription to sign in (OpenAI: ChatGPT; Anthropic: Claude). */
	hasKey?: boolean;
	hasPlan?: boolean;
	/** Of its subscription, or of the variables: the runtime (claude | codex). */
	runtime?: string;
	/** Its address is the person's own: asked for with the key. */
	endpointRequired?: boolean;
	/** An example of such an address. */
	endpointExample?: string;
	/** At such an address, the protocols it can speak there (more than one: asked which). */
	protocols?: string[];
	/** Works without a key. */
	keyOptional?: boolean;
	/** What a profile on it can do: `claude`, `codex`, `decision`. */
	uses?: string[];
	/** What the core says of it: what it can do, in words. */
	usesText?: string;
}

/**
 * A build of the app on still.fail cloud (`app.update`; scripts/release.sh puts it in /releases/<platform>/latest.json):
 * `file` is under /releases/.
 */
export interface AppRelease {
	versionCode: number;
	versionName: string;
	file: string;
	sha256: string;
	size: number;
}

/** What the archive check made of a chat as it stands, under its agent's all-done post. */
export interface ArchiveCheck {
	/** The option the check picked and what came of it, or that it failed, in a line. */
	text: string;
	recommended: boolean;
	failed: boolean;
}

/**
 * An archived chat: its thread (or, an agent with no chat, only its session), its title and last line, when it was
 * archived (`at`, and `clock` 14:05) and how (`how`: 手动归档, 空闲后自动归档). `place`: its station's name, where there
 * is more than one to tell apart. Not `deletable` when archived alone (its agents still at work elsewhere).
 */
export interface ArchiveItem {
	station: string;
	session: string;
	thread?: number;
	title: string;
	last: string;
	at: number;
	clock: string;
	how: string;
	deletable: boolean;
	place?: string;
}

/** A day of the archive, headed as the chat list's (今天, 昨天, 星期三, 9月20日). */
export interface ArchiveDay {
	label: string;
	items: ArchiveItem[];
}

export interface ArchiveError {
	station: string;
	text: string;
}

export interface ArchiveOptionChat {
	session: string;
	title: string;
	at: number;
	recommended: boolean;
}

export interface ArchiveOptionDraft {
	/** Stable while the draft lasts, for the list's keys. */
	key: string;
	id?: string;
	name: string;
	rubric: string;
	archive: boolean;
}

export interface ArchiveOptionView {
	id: string;
	name: string;
	rubric: string;
	/** A chat in this situation is recommended for archiving. */
	archive: boolean;
	/** Chats the checks of the last days put here. */
	count: number;
	chats: ArchiveOptionChat[];
}

export interface ArchivePolicyAuthor {
	/** person or agent */
	kind: string;
	email?: string;
	name?: string;
	session?: string;
	title?: string;
	runtime?: string;
}

export interface ArchivePolicyChange {
	at: number;
	summary: string;
	by: ArchivePolicyAuthor;
}

/** The archive policy as one page edits it (policyForm). */
export interface ArchivePolicyDraft {
	policy: string;
	options: ArchiveOptionDraft[];
	dirty: boolean;
	pending: boolean;
}

export interface ArchivePolicyView {
	/** The policy in words: what the decision model is told. */
	text: string;
	options: ArchiveOptionView[];
	days: number;
	/** Chats checked in the last `days` (each by its latest check). */
	checked: number;
	/** Of them, those whose latest check failed. */
	failed: number;
	/** Saved by someone; else the default. */
	edited: boolean;
	change?: ArchivePolicyChange;
	/** The checks counted, in a line (core). */
	summaryText?: string;
	/** Who changed it last, where, when and what, in a line (core). */
	changeText?: string;
}

/**
 * The archive of a scope's stations online (the `archive` topic): chats archived by hand or by their station once
 * idle, newest first by the day they were archived; what could not be read of it; and what the page says in place
 * of rows (reading, none), if anything. Restored (`chat.archive` with `archived` false) or deleted (`session.delete`),
 * a chat leaves it.
 */
export interface ArchiveView {
	days: ArchiveDay[];
	/** A station's archive that could not be read, in a line (named where there are several). */
	errors: ArchiveError[];
	loading: boolean;
	note?: string;
}

export interface Attachment {
	name: string;
	path: string;
	size: number;
	width?: number;
	height?: number;
	/** An image's ThumbHash (base64): a blurred likeness of it, shown until it loads. */
	thumbhash?: string;
}

/** How full something is. */
export type Level = "ok" | "amber" | "red";

/** A window of a session's account running out, as its ring draws it. */
export interface QuotaAttention {
	left: number;
	mark: string;
	level: Level;
	until?: number;
}

/**
 * What is worth a look about a session now (account | quota | disk): what it says (`text`; for a quota, its tip's
 * first line, `more` the rest), and a quota's ring.
 */
export interface Attention {
	kind: string;
	text: string;
	more?: string;
	quota?: QuotaAttention;
}

/** A moment in words, fresh each minute: 3 分钟前 (`ago`), 9/20 14:05:09 (`full`), 3 小时后 (`until`), whether it has come. */
export interface Stamp {
	at: number;
	ago: string;
	full: string;
	until: string;
	past: boolean;
}

export interface AutomaticDecisionCheck {
	id: number;
	session: string;
	title: string;
	at: number;
	stamp?: Stamp;
	label: string;
	accepted: boolean;
	model: string;
	profile?: string;
	elapsedMs: number;
	error?: string;
}

/** Who made a model, for its mark; absent when the marks do not know it (the runtime's stands in). */
export interface Maker {
	id: string;
	name: string;
}

/** Used up until a time (or no one knows when), in words. */
export interface Spent {
	until?: number;
	text: string;
	back?: string;
}

export interface QuotaCredits {
	hasCredits: boolean;
	unlimited: boolean;
	balance?: string;
}

/** A quota window, as drawn: its mark (5H, W), what is left, how full (ok | amber | red), when it refills in words. */
export interface QuotaWindow {
	label: string;
	usedPercent: number;
	resetsAt?: number;
	mark: string;
	left: number;
	level: Level;
	refills?: string;
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
}

/** An allowance: its windows shortest first. */
export interface Quota {
	credits?: QuotaCredits;
	resetCount?: number;
	creditsText?: string;
	resetText?: string;
	/** ok | unsupported | unavailable | blocked (the provider refuses the account) */
	state: string;
	windows: QuotaWindow[];
	detail?: string;
	checkedAt: number;
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
}

/**
 * What is left of an account's allowance, in a few words: every window in gray, or only the one running low, with
 * its level.
 */
export interface QuotaLine {
	text: string;
	level?: Level;
}

/** A profile that can run a model: `current` it runs on it now. */
export interface RunnableProfile {
	/** The chosen model’s reasoning levels on this account. */
	efforts?: string[];
	id: string;
	name: string;
	current: boolean;
	spent?: Spent;
	kind?: AccessKind;
	/** The mark of its provider's maker (a key on a listed provider); none: the kind's own. */
	mark?: string;
	runtime?: RuntimeKind;
	quota?: Quota;
	/** What is left of its allowance, in a few words (a core from before it says nothing). */
	quotaLine?: QuotaLine;
}

/** A model a station can run: its maker, the runtimes it runs on, and for each how hard it can think and who runs it. */
export interface ModelOption {
	/** The spelling a client sends: the one that is its key when a profile has that, else the first. */
	model: string;
	/** As people call it (Opus 5.5). */
	name: string;
	/** Its series (Opus, GPT), what a list groups it under; none when not known. Lists come by series, newest first. */
	family?: string;
	/** Every spelling of it the station's profiles have enabled (openai/gpt-6-astra, gpt-6-astra): one model. */
	ids: string[];
	maker?: Maker;
	runtimes: RuntimeKind[];
	efforts: Record<string, string[]>;
	accounts: Record<string, RunnableProfile[]>;
	spent?: Spent;
}

/**
 * What a chat runs on: `model` none when none is chosen; `effort` none the default depth; `profile` none the
 * station's pick.
 */
export interface Picked {
	model?: string;
	runtime: RuntimeKind;
	effort?: string;
	fast?: boolean;
	profile?: string;
}

/** The account a model control names: kept to (`auto` false), or the station's pick; `level` its window running low. */
export interface PickAccount {
	text: string;
	auto: boolean;
	level?: Level;
	profile?: RunnableProfile;
}

/**
 * A model control (the `pick` topic): what runs it now (`value`), what is picked in its panel so far (`draft`,
 * until `pick.save`), and what they say. An account kept to that does not run the model picked gives way to the
 * station's pick, said so (`dropped`, `force`).
 */
export interface PickView {
	fastAvailable?: boolean;
	fastText?: string;
	options: ModelOption[];
	runtimeFixed: boolean;
	value: Picked;
	valueOption?: ModelOption;
	/** The account the control names; none: it names none (a new chat's, while the station's pick is fine). */
	account?: PickAccount;
	draft: Picked;
	/** The option picked in the panel, by its `model`. */
	option?: string;
	/** The runtimes offered for it (none: not asked), how hard it can think there, who can run it. */
	runtimes: RuntimeKind[];
	efforts: string[];
	accounts: RunnableProfile[];
	dropped?: string;
	/**
	 * The way to the accounts in the panel's foot: the one kept to, short, or 账号; amber when one gave way or the
	 * station's pick runs low.
	 */
	who: string;
	whoLevel?: Level;
	/** The station's pick, said: who it is on now, or what it does. */
	autoNote: string;
	changed: boolean;
	/**
	 * Full screen (the phone's): the model, depth and account as they were and as they become; why the account
	 * must change; the model and account picked in words; what the button says.
	 */
	was: string[];
	becomes: string[];
	force?: string;
	modelText: string;
	maker?: Maker;
	accountText: string;
	accountNote: string;
	accountWarn: boolean;
	saveText: string;
}

export interface AutomaticDecisionDraft {
	enabled: boolean;
	model: string;
	dirty: boolean;
	pending: boolean;
	/** The shared model selector, restricted to verified decision candidates. */
	pick?: PickView;
}

export interface AutomaticDecisionModel {
	id: string;
	name: string;
	profiles: string[];
}

export interface AutomaticDecisionRule {
	enabled: boolean;
	model?: string;
}

export interface AutomaticDecisionSettings {
	completion?: AutomaticDecisionRule;
}

export interface AutomaticDecisionView {
	canEdit: boolean;
	/** The station reviews the done chats no decision has answered when asked (automaticDecisions.review). */
	canReview?: boolean;
	settings: AutomaticDecisionSettings;
	models: AutomaticDecisionModel[];
	recent: AutomaticDecisionCheck[];
	/** The archive policy the completion check follows. Absent from stations before it. */
	policy?: ArchivePolicyView;
}

export interface Bind {
	runtime: RuntimeKind;
	model?: string;
	effort?: string;
	profile?: string;
}

/** A buddy a Slack app can wear (`buddies`): its picture is avatars/<id>.webp (and .thumb.webp), on `bg`. */
export interface Buddy {
	id: string;
	label: string;
	bg: string;
}

/**
 * One change: its lines for people, the version it came in, where it is (`place`: the parts and version, empty when
 * it needed no release), whether this app has it (`has`: absent when it is not this app's), and what that means
 * (`note`: 你的版本已包含, 更新到 0.1.n 后就有, 还没发布, 已发布, 已上线); `mine`: it is this app's.
 */
export interface ChangelogItem {
	version: number;
	versionName: string;
	text: string[];
	place: string;
	has?: boolean;
	note: string;
	mine: boolean;
}

/** A day's changes, under its heading (今天, 昨天, 9月20日). */
export interface ChangelogDay {
	label: string;
	entries: ChangelogItem[];
}

/** What this app got since the changelog was last shown here: its `build` (0.1.n) and those changes. */
export interface ChangelogNews {
	build?: string;
	entries: ChangelogItem[];
}

/**
 * What changed in still.fail, as this app shows it (the `changelog` topic; client/core-ts/src/changelog.ts): `app`
 * (web, desktop or android) and its `build` (0.1.<n>: n), absent before its host says; the changes by day, newest
 * first; what this app got since the changelog was last shown here (`news`, until `changelog.seen`); `loading` while
 * first read, `error` when it could not be and none was kept.
 */
export interface ChangelogView {
	app?: string;
	build?: number;
	days: ChangelogDay[];
	news?: ChangelogNews;
	loading?: boolean;
	error?: string;
}

/** A person as the core names them: `display` is 你 for the viewer. */
export interface PersonShown {
	name: string;
	display: string;
	picture?: string;
	mine: boolean;
}

/**
 * Who started a session or chat, or added a connect: an email, or "slack:<connect>:<user>"; "local" in records from
 * a station's own page, before it went.
 */
export interface Creator {
	id: string;
	name: string;
	email?: string;
	/** local | cloud | slack */
	via: string;
	/** As the core names them. */
	shown?: PersonShown;
}

/** The message a turn's state is about: its thread, its seq there, its ts. */
export interface TurnAbout {
	thread: number;
	seq: number;
	ts: string;
}

export interface TurnSummary {
	kind: string;
	outcome?: string;
	declared?: string;
	/** For waiting: at most how long, in seconds, until the agent is asked again (a station yet to update says none). */
	waitSeconds?: number;
	/** For waiting: what it waits for, in the agent's words (a station yet to update says nothing). */
	waitFor?: string;
	/**
	 * How the agent ended it in today's words: all_done, need_help or waiting (`declared` keeps the words from before:
	 * final, block; a station before cards may say need_decision, which the core reads as need_help). A station yet to
	 * update says nothing.
	 */
	ending?: string;
	/**
	 * For need_help: what a person has to give, do or decide, in the agent's words; for all_done, what the chat ends
	 * with.
	 */
	need?: string;
	/**
	 * The message its state is about (the agent's `about`; for need_help, the card waiting by default). A station
	 * before it says nothing.
	 */
	about?: TurnAbout;
	detail?: string;
	startedAt: number;
	endedAt?: number;
}

/** A colour of meaning. */
export type Tone = "accent" | "green" | "blue" | "red" | "amber" | "neutral";

/** An agent's mark: at work, blocked, failed. */
export type Badge = "run" | "block" | "failed";

/**
 * What a session keeps watch with (its watches running): their names, oldest first; since when the first runs; when
 * one last gave word (a notice, else its start).
 */
export interface Watching {
	names: string[];
	since: number;
	at: number;
}

/**
 * A session, with what the clients show of it. Before its details are read an agent is only what the sidebar's rows
 * say of it (key, runtime, model, effort, process, pending, last turn): the rest is absent then.
 */
export interface Session {
	key: string;
	connect?: string;
	/** thread | all */
	scope?: string;
	title?: string;
	createdBy?: string;
	boundTo?: string[];
	creator?: Creator;
	participants?: Creator[];
	/** claude | codex */
	runtime: RuntimeKind;
	profile?: string;
	profilePinned?: boolean;
	model?: string;
	effort?: string;
	fast?: boolean;
	runtimeSessionId?: string;
	workspace?: string;
	running?: boolean;
	createdAt?: number;
	lastActiveAt?: number;
	archivedAt?: number;
	/** running | warm | cold */
	process: string;
	turns?: number;
	pending: number;
	firstText?: string;
	lastTurn?: TurnSummary;
	statusText: string;
	/** accent | green | blue | red | neutral */
	tone: Tone;
	/** Its mark (run | block | failed), and in words. */
	mark?: Badge;
	badgeText?: string;
	titleText: string;
	agentText: string;
	/** Its model as people call it (Opus 5.5). */
	modelName?: string;
	maker?: Maker;
	runtimeText: string;
	processText?: string;
	/** How hard its runtime can think, lowest first. */
	efforts: string[];
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
	/**
	 * On a connect's page: the chat it was last talked in; as a candidate to deliver into, described, and whether it
	 * is the one now.
	 */
	chat?: number;
	description?: string;
	current?: boolean;
	/** Keeping watch (a `job_start` watch of its runs): its chat is a watching one. A station from before watches says none. */
	watch?: Watching;
}

/** Where an agent stands. */
export type Status = "running" | "queued" | "final" | "block" | "decision" | "failed" | "aborted" | "unexpected" | "idle";

/** How a connect's conversations become sessions. */
export type ConnectMode = "multi-session" | "single-session";

export interface SlackTokens {
	appToken: string;
	botToken: string;
}

export interface SlackIdentity {
	team: string;
	teamId: string;
	url: string;
	botUserId: string;
	botName: string;
	/** Its bot's picture (the app's icon), when Slack says. */
	botImage?: string;
}

/**
 * A connect's link to Slack: disabled | no_tokens | starting | connected | reconnecting (`botUserId`, `lastError`,
 * `workspace`) | error (`error`).
 */
export interface ConnectState {
	state: string;
	botUserId?: string;
	lastError?: string;
	workspace?: SlackIdentity;
	error?: string;
}

export interface Owner {
	id: string;
	name: string;
	/** As the core names them. */
	shown?: PersonShown;
}

/** A link's dot. */
export type Presence = "online" | "busy" | "error" | "offline";

/** A connect, with its state and how it runs in words. */
export interface Connect {
	id: string;
	name: string;
	team?: string;
	/** Its bot's picture in Slack, as last seen. */
	botImage?: string;
	enabled: boolean;
	kind: string;
	/** multi-session | single-session */
	mode: ConnectMode;
	requireMention: boolean;
	bind: Bind;
	slack: SlackTokens;
	connection: ConnectState;
	createdBy?: Owner;
	sessions: number;
	session?: string;
	statusText: string;
	/** online | busy | error | offline */
	presence: Presence;
	modeText: string;
	modeShort: string;
	runtimeText: string;
	runText: string;
	/** Its bound model as people call it (Opus 5.5). */
	modelName?: string;
}

export interface EnvVar {
	key: string;
	secret: boolean;
	value: string;
}

/** Discovered on the existing profile; credentials and transport settings never enter this view. */
export interface DecisionCapability {
	state: string;
	detail: string;
	model?: string;
	provider?: string;
}

export interface ProfileCheck {
	decision?: DecisionCapability;
	/** Runtime → model → supported reasoning levels; absent on older stations. */
	modelEfforts?: Record<string, Record<string, string[]>>;
	/** ok | login | failed | unknown */
	state: string;
	detail: string;
	models?: string[];
	checkedAt: number;
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
}

export interface LoginJob {
	profile: string;
	runtime: RuntimeKind;
	/** starting | needs_code | needs_approval | verifying | done | failed | cancelled */
	state: string;
	url?: string;
	userCode?: string;
	error?: string;
	startedAt: number;
	expiresAt: number;
}

export interface ProfileTrouble {
	title: string;
	detail: string;
	next: string;
	/** check | quota | login | command | key | env */
	action: string;
	label: string;
}

/** Models of one series (Opus), newest first. */
export interface ModelSeries {
	name: string;
	models: string[];
}

/** How a profile is shared between the workspace's stations (docs/station-share.md). */
export interface ProfileShare {
	/** The share's id: the same on every station that has the profile. */
	id: string;
	/** host: this station has it and lends it; user: a copy of another station's. */
	role: string;
	/** The station that has it. */
	host: string;
	/** The stations that may use it; absent: every station of the workspace. */
	allow?: string[];
	/** For a copy: whether its host answered lately (absent on the host). */
	reachable?: boolean;
	/** On its host: the stations that have it (a copy, or borrowing it). */
	users?: string[];
}

/** A profile, with its last check in words and its models' makers. */
export interface Profile {
	id: string;
	name: string;
	/** The signed-in subscription identity; independent of the editable display name. */
	email?: string;
	runtime: RuntimeKind;
	runtimes: RuntimeKind[];
	access: Access;
	home: string;
	homeExists: boolean;
	model?: string;
	models: string[];
	/** Models changed by the pending selection; None when no selection is being saved. */
	modelsSaving?: string[];
	env: EnvVar[];
	usedBy: string[];
	loginCommand: string;
	/** On the machine's own login of its runtime: not edited (but for its models) or signed in here; removing it stops using that login. */
	machine?: boolean;
	/**
	 * Whether a message to a running Claude Code turn moves what it waits on to the background first; None from a
	 * station older than the setting.
	 */
	backgroundOnMessage?: boolean;
	fast?: boolean;
	check?: ProfileCheck;
	login?: LoginJob;
	quota?: Quota;
	checkText: string;
	checkTone: Tone;
	/** The first problem to resolve, with its next step; absent when nothing needs attention. */
	trouble?: ProfileTrouble;
	/** The makers of its models, and of those its check found, by model. */
	makers: Record<string, Maker>;
	/** Its models, its default and those its check found as people call them (Opus 5.5), by model. */
	names: Record<string, string>;
	/**
	 * Its models and those its check found, by series (Claude's biggest first, the rest by name; 其他 last), newest
	 * first: how the list to enable them from is laid out.
	 */
	series: ModelSeries[];
	/** How many of the models it could run are enabled, in words. */
	modelsText: string;
	/** What can be enabled on it: what its provider lists, then whatever is enabled already, each once. */
	available?: string[];
	/**
	 * What it can do: `claude`, `codex`, `decision` (the automatic decisions). The core works it out from where its
	 * provider speaks and what its check found.
	 */
	uses?: string[];
	/** What it can do, in words (Claude Code · Codex · 自动决策). */
	usesText?: string;
	/** The provider of a key from the list of API providers, and the mark of its maker (none: the generic one). */
	providerName?: string;
	providerMark?: string;
	/** A model can be named by hand (a key on a listed provider: not every one lists its models). */
	canAddModel?: boolean;
	/** A provider that only answers the automatic decisions (Jev): its models are the ones its decision probe found. */
	decisionOnly?: boolean;
	decisionModels?: string[];
	/** Where the decision probe is, in words (what it found, or why it found none). */
	decisionText?: string;
	/** Shared with the workspace's other stations, or another station's (absent: neither, or a station older than sharing). */
	share?: ProfileShare;
}

export interface TurnRecord {
	id: string;
	kind: string;
	outcome?: string;
	declared?: string;
	/** In today's words (TurnSummary::ending). */
	ending?: string;
	/** For waiting: at most how long, in seconds, until the agent is asked again (a station yet to update says none). */
	waitSeconds?: number;
	detail?: string;
	startedAt: number;
	endedAt?: number;
}

export interface Membership {
	thread: number;
	session: string;
	connect: string;
	joinedAt: number;
}

export interface Quote {
	author: string;
	text: string;
	comment: string;
	ts?: string;
	/** agent | person | page (a mark on a previewed page) | image (a numbered mark on an image) */
	role?: string;
	/** The name of the file, among the message's attachments, that goes with it (a preview mark's screenshot). */
	file?: string;
}

/** A message as merged from its thread's entries. In a chat, the core says whose it is and who said it. */
export interface Message {
	seq: number;
	thread: number;
	ts: string;
	/** person | agent | ember */
	authorKind: string;
	author: string;
	authorName?: string;
	text: string;
	attachments: Attachment[];
	quotes: Quote[];
	/** An agent's post that ended its turn: final, block (the words from before; `ending` has today's). */
	declared?: string;
	/** all_done, need_decision, need_help: how the post ended its agent's turn. A station yet to update says nothing. */
	ending?: string;
	createdAt: number;
	editedAt?: number;
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
}

/** A thread: a Slack thread or a chat on still.fail's page. */
export interface ChatThread {
	id: number;
	/** "slack:<team id>" or "ember". */
	surface: string;
	channel: string;
	channelName?: string;
	threadTs: string;
	title?: string;
	createdBy?: string;
	creator?: Creator;
	createdAt: number;
	sessions: Membership[];
	last: number;
	lastMessage?: Message;
	read: number;
	unread: number;
	people: Creator[];
	firstText?: string;
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
}

/** Something a job said, and when; `ago` (3 分钟前) and `clock` (13:04, 9/27 13:04) put in by the core. */
export interface JobNotice {
	at: number;
	text: string;
	ago?: string;
	clock?: string;
}

/**
 * A part of a job's line: `word` its state's word (coloured as its dot), `notice` what it said (in the text's colour),
 * none the rest.
 */
export interface JobPart {
	text: string;
	kind?: string;
}

/** The chat an open job is in. */
export interface JobChat {
	id: string;
	title?: string;
	archived?: boolean;
}

/**
 * A background job an agent started (a web service when it has a port): shown by its name; the port is how the
 * station reaches a service, not for people.
 */
export interface Job {
	id: string;
	/** The session that started it (a chat's agents each have their own). */
	session?: string;
	name: string;
	/** running | exited | stopped | failed (a service that exited is being started again) */
	state: string;
	port?: number;
	exitCode?: number;
	startedAt: number;
	endedAt?: number;
	/** What it runs (sh -c). */
	command?: string;
	/** How often a service was started again after it ended. */
	restarts?: number;
	/** What it said lately (`ember-job notify`), newest first: how people see what a long-running job is up to. */
	notices?: JobNotice[];
	/** Started to keep watch (`job_start` watch). A station from before watches says none. */
	watch?: boolean;
	/** When its output last grew; absent when it has none. */
	outputAt?: number;
	/** Its dot: up (a service up), live (a job alive), restart (a service being started again), fail, off (over). */
	tone?: string;
	/** A web service (it has a port). */
	service?: boolean;
	/** A service whose page can be opened: up, or being started again. */
	open?: boolean;
	/** Over, so clearing takes it away (stopped, failed, ended by itself; not a service started again). */
	ended?: boolean;
	/** It matters now: up, alive, restarting, or died lately (a day). */
	current?: boolean;
	/** Its state in a word (在线, 在盯着, 意外退出…), coloured as its dot. */
	word?: string;
	/** The line under its name, in parts (see `JobPart`). */
	meta?: JobPart[];
	/** Its state, how long, and how many notices, as a detail's head says it: 在盯着 · 3 分钟 · 2 条通知. */
	detail?: string;
	/** When its output last grew, in words: 最后输出 · 3 分钟前. */
	outputSaid?: string;
	/** How long it has been up: 3 小时. */
	age?: string;
	/**
	 * Among the open ones (`longJobs`): its station, that station's name when there are several, the chat it is in as
	 * the viewer's sidebar has it, and all that in a line (studio · 修登录 · 已归档).
	 */
	station?: string;
	stationName?: string;
	chat?: JobChat;
	whereText?: string;
}

/** An agent of a chat: its session, the connect that started it, its profile, and what it can move to. */
export interface ChatAgent {
	session: Session;
	status: Status;
	badge?: Badge;
	connect?: Connect;
	profile?: Profile;
	profiles: RunnableProfile[];
	/** The models it can move to, as its model control offers them; the account it runs on now. */
	choices: ModelOption[];
	account?: RunnableProfile;
	attention: Attention[];
	/** When its running turn began; absent when none runs. */
	since?: number;
	/** While it waits on work it started (its turn ended as waiting): since when, and for how long at most. */
	wait?: AgentWait;
	/** Seen starting its turn while the chat shows (not at work already when first seen): its activity comes in. */
	started?: boolean;
	turns: TurnRecord[];
	threads: ChatThread[];
	/** Its background jobs, newest first; those with a port are web services, shown by their names. */
	jobs: Job[];
}

/** An agent of a sidebar row, with what its mark shows. */
export interface RowAgent {
	key: string;
	runtime: RuntimeKind;
	model?: string;
	effort?: string;
	process: string;
	pending: number;
	lastTurn?: TurnSummary;
	agentText: string;
	maker?: Maker;
	mark?: Badge;
	statusText: string;
	badgeText?: string;
	/** Keeping watch, as its session's `watch`. */
	watch?: Watching;
}

/** Who said a row's last thing: an agent (its state riding on its picture), a person, or ember. */
export interface LastBy {
	/** agent | person | ember */
	kind: string;
	name: string;
	mine: boolean;
	model?: string;
	runtime?: RuntimeKind;
	/** block | run | failed */
	state?: Badge;
	id?: string;
	picture?: string;
	/** What its picture says when pointed at: who, and an agent's state. */
	label: string;
	maker?: Maker;
}

/** A row's last message, its text cut to 200 characters; `preview` its line. */
export interface RowMessage {
	seq: number;
	authorKind: string;
	author: string;
	authorName?: string;
	text: string;
	createdAt: number;
	by?: LastBy;
	preview: string;
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
}

export interface Origin {
	teamName?: string;
	channel: string;
	channelName?: string;
	threadTs: string;
}

/** Someone in a chat, named as the core names them. */
export interface Person {
	id: string;
	name: string;
	email?: string;
	via: string;
	shown: PersonShown;
}

/**
 * A watching chat (core, present.ts): what it watches in words (监控中：盯 CI), and what archiving it by hand asks
 * first (`ask`: it runs on in the archive).
 */
export interface RowWatch {
	text: string;
	ask: string;
}

/**
 * One answer a decision offers (an agent's block post with chat_post `options`): a short phrase that reads on its own,
 * a line on what it leads to, and whether the agent recommends it.
 */
export interface DecisionOption {
	label: string;
	detail?: string;
	recommended?: boolean;
}

/**
 * What an agent's message asks people to answer it with (core decisions.ts): `type` options (`options`, as shown: the
 * recommended one last; a tap answers, `decision.answer`) or text (a field to write in, with a `placeholder`;
 * `decision.reply`). A type a UI does not know: answered by writing in the chat.
 */
export interface MessageCard {
	/** The person the agent asks to decide, by email. Absent on legacy cards. */
	assignee?: string;
	/** Who needs to decide, in the viewer's words; prepared by the core. */
	assigneeText?: string;
	/** options | text */
	type: string;
	options?: DecisionOption[];
	placeholder?: string;
}

/**
 * A chat's card still pending (a row's, a chat page's; named for when the only cards were decisions): its post's entry,
 * the card as shown, an options card's options in the order they are shown (the recommended one last; empty for a
 * text card), whether the viewer dismissed it, and its line (奏 · …) while it is the viewer's.
 */
export interface RowDecision {
	seq: number;
	options: DecisionOption[];
	/** The card itself. A core before cards says none: an options card. */
	card?: MessageCard;
	dismissed?: boolean;
	/** 奏 · <the post's first line, cut to about 40 characters>. Absent once dismissed. */
	text?: string;
}

/** An item of the sidebar, as its station puts it together for the viewer, and where it is. */
export interface ChatItem {
	id: string;
	session: string;
	thread?: number;
	title: string;
	agents: RowAgent[];
	last?: RowMessage;
	unread: boolean;
	mine: boolean;
	lastActiveAt: number;
	connect?: string;
	origin?: Origin;
	station: string;
	stationName: string;
	/** block | run | failed */
	state?: Badge;
	/** Where it came from (Slack · workspace · #channel), for a Slack chat. */
	originText?: string;
	/** Its station is offline, in words ("Studio 离线"): the row is shown greyed and marked. Absent while online. */
	offline?: string;
	/**
	 * Its station's link coming back, or failing and retried, in words ("正在重连 Studio…"): the row is marked with a
	 * turning ring. Absent while linked (and while offline).
	 */
	reconnecting?: string;
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
	/** A new chat asked for here that its station has not made yet. Absent otherwise. */
	pending?: boolean;
	/**
	 * Who is in it, for its pictures: who started it first, then everyone who wrote in it, each once. From a
	 * station that does not say: absent.
	 */
	people?: Person[];
	/** Who started it, as in `people`. */
	creator?: Creator;
	/** Its people in words, who started it said ("小王 发起 · Lina、你"), with `people`. */
	peopleText?: string;
	/** The key a chat asked for here went by before its station made it: the list keeps it one row throughout. Older stations do not say it. */
	clientKey?: string;
	/** Pinned by the viewer to the top of their list. Absent when its station does not know pins (it cannot be pinned). */
	pinned?: boolean;
	/** A watching chat (one of its agents keeps watch): archiving it by hand asks first. Absent otherwise. */
	watch?: RowWatch;
	/**
	 * The card it waits on (an agent's post with a card no one has answered yet), as the viewer sees it. Absent when
	 * there is none (and from a station before decisions).
	 */
	decision?: RowDecision;
	/**
	 * Nothing is left in it: each of its agents ended all_done, nothing at work, no card waiting for the viewer,
	 * nothing unread; where its station's archive review is on, only once the review recommended archiving it. Drawn faded,
	 * below the rest of its day (the core orders it so). Absent otherwise.
	 */
	settled?: boolean;
	/** With `settled`: offer to archive it with one tap (`chat.archive`). Absent otherwise. */
	archivable?: boolean;
	/**
	 * Where it stands, in words, for its second line, its agents' states first: 要你帮忙：…, 出问题：…; then 奏 · … (a
	 * card waiting for the viewer, even while an agent works); then 在等：…, 做完了(：…). Absent while it is at work with
	 * no card waiting, or with nothing to say.
	 */
	stateText?: string;
	/**
	 * The message `stateText` is about (a seq in this chat): the card, or the one the agent's state names. Opening the
	 * chat from the line may go to it. Absent when none.
	 */
	stateAbout?: number;
	/**
	 * Its mark, the most urgent first: alert (an agent failed), wait (a card waits, not dismissed by the viewer; or an
	 * agent needs them: need_help), busy (at work), done (something unread). Absent for none.
	 */
	tone?: string;
}

/**
 * A day of the list, with its heading (今天, 昨天, 星期三, 9月20日); or, above them all, the chats the viewer pinned
 * (`pinned`, `daysAgo` -1, headed 已固定).
 */
export interface ChatDay {
	daysAgo: number;
	at: number;
	label: string;
	items: ChatItem[];
	pinned?: boolean;
}

/**
 * A chat's services and background jobs as its pages show them (the `chatJobs` view): every one, those that matter
 * now first (died, restarting, up and alive, over; newest first within each); what the button's dot says; each
 * group's head's note; how many matter now, how many are over and whose they are (clearing them is per session).
 */
export interface ChatJobsView {
	jobs: Job[];
	/** fail: one died lately; restart: a service is being started again. */
	alarm?: string;
	/** 2 个在线，1 个在重启; 1 个在盯着 (empty: nothing to say). */
	servicesNote: string;
	jobsNote: string;
	current: number;
	ended: number;
	/** The sessions whose jobs that are over clearing takes away (`job.clearEnded` each). */
	clear: string[];
	/** 全部 5 个; 清掉 2 个已结束的; 另有 2 个已停止或结束. */
	allText: string;
	clearText: string;
	hiddenText: string;
}

/** Who said a message, as its line shows them: an agent by its label and mark, a person by name and picture. */
export interface MessageBy {
	name: string;
	agent?: string;
	maker?: Maker;
	runtime?: RuntimeKind;
	picture?: string;
	/** Another chat's agent (session_send): that chat's link, its name opens it. */
	from?: string;
}

/**
 * Where a decision in a chat's messages stands (core, decisions.ts): still waiting (no person has written since it was
 * asked, and no newer one replaced it), or `resolved`, with who answered and whether by picking an option.
 */
export interface MessageDecision {
	resolved: boolean;
	/** Still waiting, and the viewer dismissed it (off their list; the options still work). */
	dismissed?: boolean;
	/**
	 * Who answered it (the first person to write after it), by name; absent while it waits, or when a newer decision
	 * replaced it.
	 */
	answeredBy?: string;
	/** The option they picked (their message quoted it with an option's label), its label. */
	chosen?: string;
	/** Resolved, in words: 林晓 选了「先不改」, 林晓 回复了, 已换成新的问题. */
	text?: string;
}

/**
 * A message of a chat, with what the core decides of it: the viewer's (their bubble), still.fail's own notice, who said
 * it, and whether its agents have yet to take it.
 */
export interface ChatMessage {
	/** The local outbox identity this message replaced, when sent from this core. */
	outgoing?: string;
	seq: number;
	thread: number;
	ts: string;
	/** person | agent | ember */
	authorKind: string;
	author: string;
	authorName?: string;
	text: string;
	attachments: Attachment[];
	quotes: Quote[];
	/** An agent's post that ended its turn: final, block (the words from before; `ending` has today's). */
	declared?: string;
	/** all_done, need_decision, need_help: how the post ended its agent's turn. A station yet to update says nothing. */
	ending?: string;
	createdAt: number;
	editedAt?: number;
	mine: boolean;
	system: boolean;
	/** still.fail's notice about one of the station's profiles (its sign-in failed): that profile's id, for a link to it. */
	profile?: string;
	by: MessageBy;
	waiting: boolean;
	/**
	 * Said while the chat shows (told as it was said, not caught up on): it comes in rather than being there at once.
	 * Decided by the core once, when first seen (attend.ts).
	 */
	said?: boolean;
	/** Its times in words, by field (`createdAt`). */
	time?: Record<string, Stamp>;
	/**
	 * An agent's post with an options card: the answers to pick, in the order they are shown (the one the agent
	 * recommends last), as `card.options`; drawn under the message. Absent for every other message.
	 */
	options?: DecisionOption[];
	/** The card it carries (options to pick, or a text field), as shown. Absent for a message with none. */
	card?: MessageCard;
	/** With a card: whether it still waits for an answer, and who answered it how. */
	decision?: MessageDecision;
}

/** A range of a text, `from` to `to` (UTF-16 units). */
export interface TextMark {
	from: number;
	to: number;
}

/** A message a search's words found (`ChatSearchView.messages`): its chat opens at it (thread, seq). */
export interface FoundMessage {
	station: string;
	thread: number;
	seq: number;
	/** Its chat, as the sidebar lists it. */
	chat: ChatItem;
	/** Who said it, as a chat names them (empty when not known). */
	by: string;
	/** The line of it that has the words, on one line, Markdown's marks out; `…` first when cut to the words. */
	text: string;
	/** Where the words are in `text` (UTF-16 ranges), in order. */
	marks: TextMark[];
	createdAt?: number;
	/** Its times in words, by field (`createdAt`). */
	time?: Record<string, Stamp>;
}

/**
 * The chats a few words find (the `chatSearch` topic): as the sidebar has them, those whose title has the words
 * first. What the composer's `@` menu and the switcher list.
 */
export interface ChatSearchView {
	items: ChatItem[];
	/** The words looked for, as a found message marks them in its chat when opened (with `messages`). */
	words?: string[];
	/**
	 * The messages that have the words (asked for by `messages`, at most that many), newest first: only in the chats
	 * listed. Empty when not asked for.
	 */
	messages?: FoundMessage[];
}

/** A place a message came from or went to: a chat on still.fail's page (`session`: the agent it opens), or a Slack thread. */
export interface Place {
	/** A still.fail chat's title, or a Slack thread's workspace and channel (`Cue#ops`). */
	name: string;
	/** ember | slack */
	surface: string;
	session?: string;
	/** A Slack thread's link in Slack, while a connect is signed in to its workspace. */
	url?: string;
}

/**
 * A message in Slack an agent of a chat sent (chat_post to a Slack thread, slack_api chat.postMessage) or was given,
 * read from its transcript: the chat shows it after the message it followed, without it being one of the chat's.
 */
export interface ChatSentElsewhere {
	key: string;
	/** The message it comes after (its seq); 0 before the first of the chat. */
	after: number;
	createdAt: number;
	/** As sent (Slack's mrkdwn). */
	text: string;
	/** Where it went; none when the core cannot name it. */
	place?: Place;
	failed?: boolean;
	/** A person's message in Slack its agent was given (`by`: who said it); absent for what the agent sent there. */
	received?: boolean;
	by: MessageBy;
	/** Its times in words, by field (`createdAt`). */
	time?: Record<string, Stamp>;
}

/** Who is looking: the account that reaches the workspace, by its email. */
export interface Me {
	id?: string;
	email?: string;
}

/** A message sent from here that the chat does not show yet (sending | failed); `seq` once the station has it. */
export interface Outgoing {
	id: string;
	text: string;
	attachments: Attachment[];
	quotes: Quote[];
	createdAt: number;
	state: string;
	error?: string;
	seq?: number;
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
}

/** A station's mesh link: connecting | online | offline | error. */
export interface Link {
	state: string;
	message?: string;
}

/**
 * A chat's link to its station while it is not as it should be: `tone` trouble (down; `detail` why) | busy (coming
 * back), and the line that says it.
 */
export interface LinkShown {
	tone: string;
	text: string;
	detail?: string;
}

/** The station update control beside a chat title. Additions default for older cores. */
export interface StationUpdateNotice {
	tone: string;
	text: string;
	detail?: string;
	label?: string;
	/** The station's name as its workspace has it ("station" when it has none). Absent from older cores. */
	station?: string;
	/** The version it runs. */
	from?: string;
	/** The version it is going to, when known and not the one it runs. */
	to?: string;
	/** How far an update is, 0–100, when the station says. */
	percent?: number;
	version?: string;
	open?: boolean;
	canUpdate?: boolean;
	dismissible?: boolean;
}

/** An item's page: its chat (with the viewer's read position), or its agent before it has one. */
export interface ChatView {
	/** The newest message asks for attention or gives a final result: dim earlier messages only at the scroll end. */
	focusLast?: boolean;
	/** Archived chats must be restored before composing another message. */
	archived?: boolean;
	/** Pinned to the top of the viewer's list. Absent when its station does not know pins (it cannot be pinned). */
	pinned?: boolean;
	me: Me;
	thread?: ChatThread;
	title: string;
	/** Where a Slack chat is (#channel, 私信), and its link in Slack while its connect is signed in. */
	place?: string;
	slackUrl?: string;
	people: Person[];
	agents: ChatAgent[];
	messages: ChatMessage[];
	/**
	 * What its agents said in Slack and were given from it meanwhile (not in this chat), shown among its messages;
	 * not kept in it. Empty from a core before it.
	 */
	elsewhere?: ChatSentElsewhere[];
	more: boolean;
	/**
	 * Entries after those loaded: the chat shows a window short of its end (`chat.newer` loads the next page,
	 * `chat.latest` goes to the end). What is said meanwhile waits there, counted in its thread's `unread`.
	 */
	newer?: boolean;
	/**
	 * The entry the chat opened at when not at its end (its first unread, or where it was left): the list shows it
	 * at its top. Absent when it opened at its end.
	 */
	at?: number;
	/**
	 * Opened where it was left (`at`): how far below the top of the list that entry's top was then, as the client
	 * that left it said (`chat.place`). Absent otherwise, and from a core before it.
	 */
	atOffset?: number;
	/**
	 * The last message caught up on (read: kept on the device, a page, what was missed) rather than said while the
	 * chat is open. The core decides from it which come in (`ChatMessage::said`); clients go by that.
	 */
	caught?: number;
	/**
	 * The message the unread line goes over: the first the viewer had not read when the chat was opened (not
	 * theirs); none while older pages are loaded to find it, or with nothing unread. Absent from a core before it.
	 */
	unreadLine?: number;
	/** The unread line lies above the messages loaded: older pages are being loaded to find it. */
	unreadAbove?: boolean;
	outbox: Outgoing[];
	link: Link;
	offline: boolean;
	/** One of its agents keeps watch: archiving it by hand asks first. Absent otherwise. */
	watch?: RowWatch;
	/** A new chat asked for here that its station has not made yet: what is sent to it waits in its outbox. */
	pending?: boolean;
	/** The key its station gave a chat asked for here, once made: the page, opened under the core's key, goes by it. */
	key?: string;
	/** Why the station could not make it, the last time it was tried. */
	failed?: string;
	/** Its link while it is down or coming back, in words; absent while it is up (and from a core before it). */
	connection?: LinkShown;
	/** Station update availability or progress, including the local outbox while reconnecting. */
	stationUpdate?: StationUpdateNotice;
	/** The card it waits on, as its row has it. Absent when there is none. */
	decision?: RowDecision;
	/**
	 * Nothing is left in it (as its row's `settled`), and it is not archived: offer to archive it with one tap
	 * (`chat.archive`). Absent otherwise.
	 */
	archivable?: boolean;
	/** What the archive check made of it as it stands (the option picked, or a failure). Absent when none did. */
	archiveCheck?: ArchiveCheck;
}

export interface StationState {
	station: string;
	id: string;
	name: string;
	/** online | connecting | offline | error */
	state: string;
	message?: string;
}

/**
 * What is wrong with the workspace's stations, in a line, and the worst of it: offline | error | reconnecting.
 * `retry`: always false now (a station down is tried again from the stations' page); true from older cores while down.
 */
export interface StationTrouble {
	text: string;
	state: string;
	retry?: boolean;
}

/** Whose pictures lead the rows of a list (`ChatsView::leading`). */
export type Lead = "agents" | "people";

/**
 * The stations at a glance (the glyph): how many are online, offline or connecting (`dim`), failing, and at work; the
 * line beside it while all is well (the one station by name, else how many; and who works), and all of it in words.
 */
export interface StationsGlyph {
	online: number;
	dim: number;
	/** Of `dim`, those whose link is on its way: they pulse. Absent from a core before it. */
	connecting?: number;
	failing: number;
	working: number;
	summary: string;
	label: string;
}

export interface StationFailing {
	station: string;
	text: string;
	message?: string;
}

/**
 * What a list with no rows to show says in their place: it is still reading, the stations it cannot reach (`text`
 * says so, `message` why), or there is nothing (`empty`). All false and none with rows to show.
 */
export interface ListNote {
	reading: boolean;
	/** While reading, what it waits on (正在连接 Studio, 正在读取会话); absent from a core before it. */
	text?: string;
	failing: StationFailing[];
	empty: boolean;
}

export interface ChatsView {
	me: Me;
	stations: StationState[];
	loading: boolean;
	days: ChatDay[];
	/**
	 * The stations not working as they should, in a line ("MBA 离线", "正在重连 Studio", "2 台 station 异常"), for a
	 * corner of the list; absent while all are (a station first connecting is not one).
	 */
	trouble?: StationTrouble;
	/** How many people the scope has, for how rows are pictured; absent until known. */
	members?: number;
	/** Whose pictures lead the rows: the device's setting (`prefs`), 自动 by `members` (unknown: as if alone). */
	leading?: Lead;
	/** The stations at a glance, and what the list says with no rows; absent from a core before them. */
	glyph?: StationsGlyph;
	note?: ListNote;
}

export interface ConfigTokenOwner {
	team: string;
	teamDomain?: string;
	teamIcon?: string;
	user: string;
	email?: string;
	image?: string;
}

export interface ConnectAppSettings {
	name: string;
	displayName: string;
	description: string;
	longDescription: string;
	backgroundColor: string;
	groups: Record<string, boolean>;
}

export interface SlackTeam {
	teamId: string;
	name: string;
	owner?: ConfigTokenOwner;
}

export interface SlackAppLinks {
	settings: string;
	install: string;
	appToken: string;
	oauth: string;
}

/** A Slack app still.fail made that no connect has taken yet, as its maker sees it (never its secrets or tokens). */
export interface MadeSlackApp {
	appId: string;
	name: string;
	teamId: string;
	/** The Slack workspace's name, when its configuration token says. */
	team?: string;
	created: number;
	links: SlackAppLinks;
	/** The link that installs it through Slack's OAuth (a station in still.fail cloud); none when its tokens are copied by hand. */
	install?: string;
	/** Its install's state, what a connect names it by. */
	state?: string;
	installed: boolean;
	installedTeam?: string;
}

/** One transient connect wizard. Decisions and navigation come from the core on every client. */
export interface ConnectFlowView {
	step: string;
	title: string;
	back: string;
	number: number;
	total: number;
	resume?: string;
	mobile: boolean;
	team?: string;
	adding: boolean;
	settings: ConnectAppSettings;
	icon?: string;
	iconError?: string;
	madeId?: string;
	config: string;
	configReady: boolean;
	configError?: string;
	mode: ConnectMode;
	requireMention: boolean;
	gettingToken: boolean;
	noProfile: boolean;
	canMake: boolean;
	canCreate: boolean;
	teams: SlackTeam[];
	chosen?: SlackTeam;
	made?: MadeSlackApp;
	pick?: PickView;
}

export interface ConnectItem {
	station: string;
	stationName: string;
	connect: Connect;
	/** Its latest dozen; the one it delivers into; those it could deliver into instead. */
	sessions: Session[];
	bound?: Session;
	candidates: Session[];
	running: number;
}

/** One thing waited on: what (`text`), how long or how much (`detail`), and whether it is slow | trouble. */
export interface StatusItem {
	state: string;
	text: string;
	detail: string;
}

/**
 * What a chat says of its connection (the `connection` topic; client/core-ts/src/pill.ts), all decided in the core:
 * `tone` busy (its link coming back, or something of its workspace waited on a while) | trouble (down) | back (up
 * again, for a moment after a busy or trouble was shown), absent while there is nothing to say; `text` the line,
 * `detail` beside it, `items` each thing waited on (on hover).
 */
export interface ConnectionView {
	tone?: string;
	text?: string;
	detail?: string;
	items: StatusItem[];
}

export interface ConnectsView {
	me: Me;
	items: ConnectItem[];
	loading: boolean;
}

export interface Counts {
	sessions: number;
	running: number;
	warm: number;
}

/**
 * A card the viewer answered today: where it is, what it asked (`text`, its post's first line), how they answered it
 * (`answer`: 选了「…」, 回复：…), and when (`clock`, 14:05).
 */
export interface DecisionAnswered {
	station: string;
	stationName: string;
	session: string;
	thread: number;
	title: string;
	seq: number;
	text: string;
	answer: string;
	clock: string;
}

/**
 * One card on the 奏 page: where it is, the post that asks (as a chat shows messages, with its card) and the messages
 * just before it, the card (an options card's options as shown, also as `options`), and whether the viewer set it
 * aside on this device. An options card is answered with `decision.answer`, a text card with `decision.reply`.
 */
export interface DecisionItem {
	station: string;
	stationName: string;
	/** Its chat's item id (its session's key): what its page opens by. */
	session: string;
	thread: number;
	/** Its chat's title. */
	title: string;
	seq: number;
	message: ChatMessage;
	/** The one or two messages before it, oldest first. */
	before: ChatMessage[];
	options: DecisionOption[];
	/** The card. A core before cards says none: an options card. */
	card?: MessageCard;
	/** Set aside (待定) on this device: last in the list, still pending. */
	deferred?: boolean;
	/** 奏 · <the post's first line> */
	text: string;
	/**
	 * What it asks, uncut: the need its agent ended need_human with, else the post's first line. A core before it says
	 * none.
	 */
	question?: string;
}

/**
 * A chat of the viewer's where an agent is at work or waiting: where it is, and what it is doing (`line`: 在做 · …,
 * 在等：…), and since when (`time.lastActiveAt`).
 */
export interface DecisionWorking {
	station: string;
	stationName: string;
	session: string;
	thread: number;
	title: string;
	line: string;
	time?: Record<string, Stamp>;
}

/**
 * The 奏 page's day: how many cards the viewer answered today, how long they waited on average (in words; none with
 * none answered), and how many of their chats have an agent at work or waiting.
 */
export interface DecisionsToday {
	count: number;
	waited?: string;
	working: number;
}

/**
 * The cards waiting in a workspace's chats for the viewer (the `decisions` view, the 奏 page, core decisions.ts):
 * pending whatever their agents do, not dismissed by them, those they set aside (待定) last; `count` for 奏 N.
 */
export interface DecisionsView {
	items: DecisionItem[];
	count: number;
	/** Some station's chats are still being read: more may come. */
	loading: boolean;
	/** The cards the viewer answered today, newest first. A core before them says none. */
	answered?: DecisionAnswered[];
	/** The viewer's chats where an agent is at work or waiting (正在办), newest first: where the next may come from. */
	working?: DecisionWorking[];
	/** The day in numbers. */
	today?: DecisionsToday;
}

/** What this device is, as its host told the core at start (`client.device`), and what follows from it. */
export interface DeviceView {
	/** `web`, `desktop` or `android`; empty until told. */
	app?: string;
	/** A phone (the Android app, or a phone's browser). */
	phone?: boolean;
	/** An item's link from outside is offered to the desktop app first (a computer's browser). */
	handoff?: boolean;
	/** The device's language as its host says (`zh-CN`, `en-US`, …); none until told. */
	locale?: string;
}

export interface Disk {
	path: string;
	totalBytes: number;
	freeBytes: number;
}

export interface DiskRoom {
	freeBytes: number;
	totalBytes: number;
}

/**
 * A call under way: its name (`job.stop`), its params that are words, numbers or yes/no, as words (what a page
 * matches it by), and since when; `stage` running, rechecking (its station went quiet before it answered: asked again
 * once it is back, `note` saying so), or failed (kept a few seconds, `error` saying why). A core from before stages
 * gives none: running.
 */
export interface DoingItem {
	call: string;
	params: Record<string, string>;
	since: number;
	stage?: string;
	error?: string;
	note?: string;
}

/**
 * What people set going on this device and the core has not finished (the `doing` topic; client/core-ts/src/doing.ts),
 * oldest first.
 */
export interface DoingView {
	doing: DoingItem[];
}

/**
 * What is being written to a chat on this device (the `draft` topic, `draft.put`): its text as typed, the passages
 * it quotes with what is said about them, and the files already up (the station keeps them in no chat until a
 * message takes them). Files still going up are the page's own.
 */
export interface DraftView {
	text: string;
	quotes: Quote[];
	files: Attachment[];
}

export interface FlowChoice {
	id: string;
	title: string;
	hint: string;
}

export interface FlowOption {
	id: string;
	label: string;
}

export interface FootprintConfirm {
	title: string;
	text: string;
	action: string;
	danger: boolean;
}

/**
 * One way to clean: `call` (footprint.rebuild, footprint.delete, footprint.evict) with `keys`, after each of `confirms` is agreed
 * to in turn; `done` is said after.
 */
export interface FootprintChoice {
	label: string;
	call: string;
	keys: string[];
	confirms: FootprintConfirm[];
	done: string;
}

/** A clean-up offered: its line, and the choices it has (one, or several: all archived chats, or the older ones). */
export interface FootprintAction {
	id: string;
	title: string;
	note: string;
	/** The button's words. */
	action: string;
	danger: boolean;
	/** Asked first when there are several: which one. */
	pick?: string;
	choices: FootprintChoice[];
}

/** How much of the disk a station takes, for the row that opens its footprint page. */
export interface FootprintBrief {
	/** None before its first measure. */
	bytes?: number;
	scanning?: boolean;
	/** What the core says of it: 12.3 GB, 正在统计…. */
	text?: string;
}

/** A chat's directory: its size, what can be made again in it, how long since it was used, and what can be done. */
export interface FootprintChat {
	key: string;
	/** The chat to open, by its id in the list. */
	chat?: string;
	title: string;
	archived: boolean;
	text: string;
	note: string;
	choices: FootprintChoice[];
}

export interface FootprintLegend {
	text: string;
	/** Its dot's colour (as FootprintSegment's), or none for words alone. */
	tone: string;
	level: Level;
}

/** A part of the data directory (or a place beside it): `chats` opens the list of chats. */
export interface FootprintPart {
	id: string;
	label: string;
	note: string;
	text: string;
	tone: string;
	opens: boolean;
}

/** A line of the memory part: the station, the agents together, or one agent's process (`key`: its chat's session). */
export interface FootprintRow {
	label: string;
	text: string;
	note?: string;
	/** Under the line before it (an agent's process under the agents). */
	nested: boolean;
	chat?: string;
	choice?: FootprintChoice;
}

/** A piece of the disk's bar: `tone` is the part's colour (chart-1…6), `rest` (used by others) or `free`. */
export interface FootprintSegment {
	id: string;
	percent: number;
	tone: string;
}

/**
 * How much of the machine a station takes, as its footprint page shows it: everything in words, with what can be cleaned
 * and how (each clean a choice: the call, the chats it is for and the questions asked before it, in order).
 */
export interface FootprintView {
	/** Measured at least once: before, the page says it is being measured. */
	measured: boolean;
	scanning: boolean;
	/** The viewer may clean up (an owner or admin). */
	manage: boolean;
	/** 3 分钟前统计, 正在统计…. */
	checkedText: string;
	/** still.fail 在这台机器上占用. */
	lead: string;
	totalText: string;
	/** The disk in one bar: the station's parts, the rest that is used, and what is free (percent of the disk). */
	bar: FootprintSegment[];
	legend: FootprintLegend[];
	parts: FootprintPart[];
	/** Beside the data directory: shown, not counted or cleaned. */
	elsewhere: FootprintPart[];
	elsewhereNote: string;
	/** What can be cleaned up (only for those who may). */
	actions: FootprintAction[];
	/** Why there is nothing to clean, or why the viewer cannot. */
	actionsNote?: string;
	chats: FootprintChat[];
	/** 213 个 chat · 8.6 GB. */
	chatsText: string;
	/** Chats of others the viewer cannot see, counted. */
	unseenText?: string;
	/** 内存 · 共 6 GB，已用 5.2 GB. */
	memoryTitle: string;
	memory: FootprintRow[];
}

/** One-click model and depth for a new chat; ranked and labelled by the core. */
export interface FrequentCombo {
	model: string;
	runtime: RuntimeKind;
	effort?: string;
	label: string;
	selected: boolean;
}

export interface HistoryFrom {
	name: string;
	slackUser?: string;
	bound: boolean;
}

/** A line of a group: a thought or a call. */
export type HistoryRow = 
	| { kind: "thought", content: HistoryThought }
	| { kind: "step", content: HistoryStep };

/**
 * Tool calls and thinking between two boundaries, in the order they came (`rows`): named by its latest call, what it
 * did by kind (`title`), how many failed and are running.
 */
export interface HistoryGroup {
	summary: string;
	title: string;
	failures: number;
	pending: number;
	rows: HistoryRow[];
}

/** What an item of the history is. */
export type HistoryBody = 
	| { kind: "received", content: HistoryReceived }
	| { kind: "text", content: HistoryText }
	| { kind: "post", content: HistoryPost }
	| { kind: "mark", content: HistoryMark }
	| { kind: "group", content: HistoryGroup };

/** One item of an execution history, and the transcript entries it draws (`entries`: first, last). */
export interface HistoryItem {
	key: string;
	entries: number[];
	body: HistoryBody;
}

export interface HistoryLive {
	id: string;
	text: string;
}

/**
 * A wait in an agent's history: from its mark (`since`) until the next word brought it back (`until`, absent while it
 * still waits: count on from `since`), at most `seconds`.
 */
export interface HistoryWait {
	since: number;
	until?: number;
	seconds?: number;
	/** What it waited for, in its own words (chat_state's `for`); absent when it did not say. */
	what?: string;
}

/** A state the agent marked, in words; `wait` when it went to wait on work it started (drawn with an hourglass). */
export interface HistoryMark {
	text: string;
	wait?: HistoryWait;
}

export interface HistoryMessage {
	key: string;
	from: HistoryFrom;
	text: string;
	place?: Place;
}

export interface HistoryPhase {
	phase: string;
	text: string;
	since: number;
}

/** A message the agent posted: where to, whether it ended its work blocked, whether it failed. */
export interface HistoryPost {
	text: string;
	place?: Place;
	block: boolean;
	failed: boolean;
}

/** What a prompt carried: still.fail's own words around them (`note`), then the messages. */
export interface HistoryReceived {
	note?: string;
	messages: HistoryMessage[];
}

export interface HistoryStep {
	said?: string;
	name: string;
	hint: string;
	meta: string;
	failed: boolean;
	call: string;
	result?: string;
}

/** The agent's own words; `subagent`: a sub-agent's. */
export interface HistoryText {
	text: string;
	subagent: boolean;
}

export interface HistoryThought {
	text: string;
	first: string;
}

export interface UsageLine {
	label: string;
	value: string;
}

/** An agent's execution history, read for people (history.ts). */
export interface HistoryView {
	items: HistoryItem[];
	live: HistoryLive[];
	phase?: HistoryPhase;
	usage?: UsageLine[];
	usageLine?: string;
	/** What shows at its top: where the session begins, or why there is nothing (yet). */
	edge: string;
	empty: boolean;
	loaded: boolean;
	/** Older entries exist: `history.older` loads the page before them. */
	more?: boolean;
}

export interface Memory {
	totalBytes: number;
	usedBytes: number;
	swapUsedBytes?: number;
}

/** CPU, memory or disk: how full (and how bad: ok | amber | red), in words. */
export interface Meter {
	label: string;
	short: string;
	percent: number;
	level: Level;
	value: string;
	/** Remaining capacity for an alert chip; absent for CPU and older cores. */
	remaining?: string;
	note?: string;
}

/** The machine a station runs on, with it in words. */
export interface Host {
	hostname: string;
	os: string;
	arch: string;
	cpus: number;
	cpuModel: string;
	/** 1-minute load average divided by CPU count, 0–1+. */
	load: number;
	/** How busy the CPUs are, all together, 0–1 (stations before it: absent). */
	cpuBusy?: number;
	uptimeSec: number;
	memory: Memory;
	disk: Disk;
	emberRssBytes: number;
	checkedAt: number;
	summary: string;
	line: string;
	facts: string[];
	meters: Meter[];
	/** Memory and disk in a line, what is used and what is left: 内存 12.3 / 32 GB · 磁盘 剩 45.2 / 460 GB. */
	usage: string;
	emberText: string;
}

/**
 * A job's output as it grows (the `jobLog` topic): its last lines, when it last grew, its state (absent from a
 * station yet to say), and, put in by the core, its last line and when in words (absent: nothing to say).
 */
export interface JobLogView {
	text: string;
	outputAt?: number;
	state?: string;
	last?: string;
	said?: string;
}

/** A chat's history tabs as last left: which are open, which is in front. */
export interface KeptTabs {
	tabs: string[];
	active?: string;
}

/**
 * What one of still.fail's links opens in the app (`link.parse`): `invite` (`token`), a chat's page (`chat`), or an
 * item (`item`: its `session`, and `service` its web service); the call answers null for any other link.
 */
export interface LinkTarget {
	opens: string;
	token?: string;
	workspace?: string;
	station?: string;
	chat?: string;
	session?: string;
	service?: string;
}

export interface TimelineEntry {
	at?: string;
	/** user | assistant | thinking | tool_call | tool_result */
	kind: string;
	text: string;
	tool?: string;
	ok?: boolean;
	callId?: string;
	subagent?: boolean;
}

export interface TranscriptUsage {
	modelCalls: number;
	inputTokens: number;
	cachedTokens: number;
	outputTokens: number;
	model?: string;
}

/** A step in flight; an ended one stays until the transcript entry that records it arrives. */
export interface LiveStep {
	id: string;
	/** text | thinking | tool */
	step: string;
	tool?: string;
	subagent?: boolean;
	parent?: string;
	input: string;
	startedAt: number;
	ended?: boolean;
}

/** Where the turn stands with the model (starting | requesting | responding | working), since when. */
export interface Phase {
	phase: string;
	since: number;
}

/**
 * A session as it runs: its transcript (its latest entries once `loaded`, from entry `first`; `history.older` loads
 * those before), the model's use, the steps in flight, where the turn stands, how fast it writes, and its activity.
 */
export interface Live {
	loaded: boolean;
	first?: number;
	timeline: TimelineEntry[];
	usage?: TranscriptUsage;
	steps: LiveStep[];
	phase?: Phase;
	rate?: number;
	activity?: Activity;
	/** Its station is offline: this is what was kept. */
	offline?: boolean;
}

export interface LongJobsGroup {
	/** services | jobs */
	key: string;
	/** 开了很久的网页服务 · 3 */
	head: string;
	jobs: Job[];
}

/**
 * The services and jobs left up a long while (an hour) on a scope's stations that are up (the `longJobs` view),
 * oldest first, in groups: web services, then background jobs; none while empty.
 */
export interface LongJobsView {
	groups: LongJobsGroup[];
}

/** Who the station machine's own Claude Code or Codex is signed in as (only read: still.fail never takes the login over). */
export interface MachineLogin {
	runtime: RuntimeKind;
	installed: boolean;
	loggedIn: boolean;
	email?: string;
	plan?: string;
	/** A profile can use it as it is (kept in a file, not only in the keychain). */
	usable?: boolean;
	/** Its allowance, as a profile on it would show (none until read, or when it cannot be). */
	quota?: Quota;
	/** In a line, as the pages show it. */
	text: string;
	/** Offered for a profile: signed in, on a plan, and no profile on it yet. */
	offered?: boolean;
}

export interface MemoryFile {
	path: string;
	text: string;
}

export interface MeshStatus {
	/** off | missing | running | restarting */
	state: string;
	origin?: string;
	station?: string;
	workspace?: string;
	workspaceId?: string;
	name?: string;
}

/** A figure in words, and how bad it is. */
export interface NetFigure {
	text: string;
	level: Level;
}

/** The way through one relay: its round trip, or none if it was not reached in time. */
export interface NetRelay {
	/** What still.fail calls it (北京), or its host. */
	name: string;
	rtt?: NetFigure;
	/** The connection goes through it now. */
	current: boolean;
}

/** A station's ways through each relay as last measured, and whether they are being measured again. */
export interface NetMeasured {
	measuring: boolean;
	relays: NetRelay[];
	/** The relay the connection moved to as they were measured (its name), if it did. */
	moved?: string;
}

export interface RuntimeModels {
	runtime: RuntimeKind;
	models: string[];
}

/** Who is looking: local | access (`email`) | mesh (`email`, `name`, `sub`, `role`, `workspace`, `device`). */
export interface Viewer {
	via: string;
	email?: string;
	name?: string;
	sub?: string;
	role?: string;
	workspace?: string;
	device?: string;
}

export interface PendingLogin {
	id: string;
	runtime: RuntimeKind;
	job?: LoginJob;
	created?: string;
	/** Why a sign-in that succeeded made no profile. */
	error?: string;
}

/**
 * A piece of software on a station and whether a newer one is out (the station's updates): the station itself (`station`) or a
 * runtime (`claude`, `codex`).
 */
export interface SoftwareVersion {
	/** station | claude | codex */
	id: string;
	name: string;
	/** On the machine (a runtime may not be: then `updatable` says it can be installed from here). */
	installed: boolean;
	/** What runs now; none when it is not installed, or not a release (a clone). */
	version?: string;
	/** The latest out, when it could be read. */
	latest?: string;
	/** The latest is newer than what runs. */
	newer: boolean;
	/**
	 * The station's, switched back from the test channel: the latest is the stable release, older than the beta that
	 * runs, and going back to it is offered (回到正式版). False from a station older than channels.
	 */
	downgrade?: boolean;
	/**
	 * The station's: which releases it is updated to, `stable` or `beta`; none where it cannot be updated from here,
	 * and from a station older than channels.
	 */
	channel?: string;
	/**
	 * The station's: whether it updates itself when a newer release of its channel is out (自动更新); none where it
	 * cannot be updated from here, and from a station older than it.
	 */
	auto?: boolean;
	/** Automatic updates wait for clients and running turns to leave, then five quiet minutes. */
	idleOnly?: boolean;
	/** The pages can update it (or install it, when it is not installed). */
	updatable: boolean;
	/** Why it cannot be updated from here (the desktop app's station, a runtime installed another way…). */
	note?: string;
	/** idle | updating | failed */
	state: string;
	/**
	 * The station's, while it is updating: where the update is, in a line (正在下载新版本…). None from a station
	 * older than it, or an installer that does not say.
	 */
	progress?: string;
	/**
	 * A runtime's, while what its install or update downloads comes in: how much of it is, 0–100 (drawn as a bar
	 * beside `progress`). None when that is not known, and from a station older than it.
	 */
	percent?: number;
	/** The station's, for a while after an update ended well: how it went (已更新到 0.1.1300，agent 没有中断). */
	done?: string;
	/** What the last update that failed said. */
	message?: string;
	/** When what is out was last read. */
	checkedAt?: number;
}

/** A station's overview, with what the clients show of its connects and profiles. */
export interface Overview {
	automaticDecisions?: AutomaticDecisionView;
	viewer: Viewer;
	connects: Connect[];
	profiles: Profile[];
	processes: AgentProcess[];
	counts: Counts;
	mesh?: MeshStatus;
	slackUsers: string[];
	slackTeams: SlackTeam[];
	slackApps?: MadeSlackApp[];
	disk?: DiskRoom;
	logins: PendingLogin[];
	/** This machine's own logins (none from a station older than them). */
	machineLogins?: MachineLogin[];
	/** It can share profiles and skills with the workspace's other stations (docs/station-share.md). */
	sharing?: boolean;
	/**
	 * The providers a key can be added for (none from a station older than them: they are then not offered), as the
	 * station lists them.
	 */
	apiProviders?: ApiProvider[];
	/** The station's and its runtimes' versions, and whether newer ones are out (none from a station older than them). */
	updates?: SoftwareVersion[];
	/** Its agents' processes, in a line. */
	processesText: string;
	/** How much of the disk it takes (none from a station older than the footprint page, which then is not offered). */
	footprint?: FootprintBrief;
}

/**
 * This device's connection to a station, in words (its card's network line): how it goes, its round trip now and
 * over the last minute, and what goes over it.
 */
export interface StationNet {
	/** 直连, 北京中继 (the relay's name, or 中继 host), or 正在选路. */
	path: string;
	rtt?: NetFigure;
	/** Round trips over the last minute, oldest first, in milliseconds. */
	rttHistory: number[];
	/** Bytes a second now, each way: 1.4 MB/s. */
	down: string;
	up: string;
	/** What went over it today on this device: 今天共 ↓ 212 MB · ↑ 9.6 MB (a core from before: 本次共, since it opened). */
	total: string;
	/** The same each way: 212 MB. Missing from a core from before. */
	downTotal?: string;
	upTotal?: string;
	/** Packets lost over the last minute, when some were. */
	loss?: NetFigure;
	/**
	 * The way through each relay as last measured, once it was (natively and in the browser: the mesh). Missing from
	 * a core from before.
	 */
	measured?: NetMeasured;
}

export interface StationView {
	station: string;
	id: string;
	name: string;
	/** Its line in a list: offline since when, or what it is and whether its agents work. */
	summary: string;
	/** Its buddy's face: offline | working | idle; and what it is under its name (its processor, else 在线/离线). */
	face?: string;
	line?: string;
	online: boolean;
	/** Up, but not reached just now (connecting or coming back): its figures are from before. */
	reconnecting?: boolean;
	/** Seconds, from still.fail cloud. */
	lastSeen?: number;
	version?: string;
	link: Link;
	runtimes: RuntimeModels[];
	models: ModelOption[];
	overview?: Overview;
	/**
	 * Its versions offer the 测试版 switch: it can be put on a channel (its station's version says one), and the
	 * account that reaches it is in the beta or it is on the test channel already (to be switched back).
	 */
	betaOffered?: boolean;
	host?: Host;
	/**
	 * How this device's connection to it runs; none for a station reached without one of its own (the page's own)
	 * or before one is open.
	 */
	net?: StationNet;
	/** Its times in words, by field (`createdAt`, `lastActiveAt`, …). */
	time?: Record<string, Stamp>;
}

/**
 * A new chat's page (the `newChat` topic): the stations it can start on, the one it starts on, and what it runs
 * there, as last picked on this device (`newChat.pick`); what the station no longer has gives way to the first it has.
 */
export interface NewChatView {
	/**
	 * The station last started on (or picked) in the scope, its id: the page holds its place with it until the
	 * stations are known.
	 */
	kept: string;
	/** The scope's stations up now; none until its workspace has been read (`error`: why it could not be). */
	stations?: StationView[];
	error?: string;
	/** Whether the scope has any station, up or not. */
	any: boolean;
	/** The one it starts on: the one kept, else the first up; none when none is up. */
	station?: StationView;
	model?: ModelOption;
	runtime?: RuntimeKind;
	effort?: string;
	fast?: boolean;
	/** The account kept to, while it still runs the model there; none: the station's pick. */
	profile?: string;
	/** How hard it can think there, and who can run it (offered when more than one can: `pickAccount`). */
	efforts: string[];
	accounts: RunnableProfile[];
	pickAccount: boolean;
	/** Its profiles are being read. */
	waiting: boolean;
	/** What keeps a chat from starting: `profile` (none added) or `models` (none enabled). */
	blocked?: string;
	/** In a line under the page's words: the profiles being read, or no model enabled. */
	problem?: string;
	/** Every account of the model has used up its allowance: what is sent waits for it. */
	spent?: string;
	/** Its model control (the `pick` topic of `new` on the station), with the page. */
	pick?: PickView;
	/** Up to four combinations used on this device in this workspace, filtered to this station. */
	frequent?: FrequentCombo[];
}

/**
 * A chat that wants its person: its agent is blocked on them (`block`), failed (`failed`), finished with something
 * new to read (`done`), or someone else said something (`message`). `tag` names the chat (one notification each),
 * `url` opens it.
 */
export interface Notice {
	id: string;
	kind: string;
	station: string;
	workspace: string;
	stationId: string;
	session: string;
	thread?: number;
	title: string;
	body: string;
	tag: string;
	url: string;
	at: number;
}

/** What a person hears about while the client runs (the `notices` topic; docs/notifications.md), oldest first. */
export interface NoticesView {
	items: Notice[];
}

/**
 * Notifications on this device (the `notify` topic; `notify.set`, `notice.claim`): whether they are on, whether the
 * system was asked to allow them, whether the device should hold a push registration, and the notices a page is to
 * show now, each taken by one page (`notice.claim`).
 */
export interface NotifyView {
	on: boolean;
	asked: boolean;
	push: boolean;
	show: Notice[];
}

/** A chat to go back to: its station's address and the key its page goes by. */
export interface OpenChat {
	station: string;
	key: string;
}

/** How the pages look: as the system does (the default), or always light, or always dark. */
export type Appearance = "system" | "light" | "dark";

/**
 * Whose pictures lead a chat's row: by how many people the scope has (the default), or always the agents', or the
 * people's.
 */
export type RowPictureSetting = "auto" | "agents" | "people";

/** What this device keeps of how its person likes it (the `prefs` topic, `prefs.set`), and what it is. */
export interface PrefsView {
	/** The lists show only the chats and connects the viewer takes part in. */
	onlyMine?: boolean;
	/** The chat list shows only the watching chats (监控中); never with `only_mine`. */
	onlyWatching?: boolean;
	/**
	 * The wide screen's sidebar shows the decisions waiting for the viewer (奏) in place of the chats; never with
	 * `only_mine` or `only_watching`.
	 */
	onlyDecisions?: boolean;
	appearance?: Appearance;
	rowPicture?: RowPictureSetting;
	/** Times are shown as dates rather than "3 分钟前". */
	absoluteTime?: boolean;
	/** The language chosen: `zh`, `en`, or none to follow the device's (its `locale`). */
	language?: string;
	/**
	 * The language things are said in, as chosen or else as the device is: `zh` or `en` (the core's; none from a core
	 * before languages, when the clients go by the device themselves).
	 */
	lang?: string;
	/** Keys changed for an action (the desktop app's), by action. */
	keys?: Record<string, string[]>;
	/** The workspace last open (the Android app's). */
	workspace?: string;
	/** The chat page last open, by scope (a workspace; `local` in what a station's own page kept, before it went). */
	lastChat?: Record<string, string>;
	/**
	 * The chat last open, by workspace, as the core keeps it from `client.focus` (a settings page leaves it as it
	 * was): what the workspace's page goes back to.
	 */
	openChat?: Record<string, OpenChat>;
	/** Each chat's history tabs, by `<station>:<chat>` (the latest 200). */
	chatTabs?: Record<string, KeptTabs>;
	/** A Slack app made for a new connect, to go on with, by station (the Android app's). */
	resume?: Record<string, string>;
	/** Versions dismissed on this device, by workspace/station. */
	stationUpdatesDismissed?: Record<string, string>;
	/** The invite code a page was opened with, kept through signing in until a workspace is made with it. */
	invite?: string;
	device?: DeviceView;
}

/** Providers of one group, as the picker lists them. */
export interface ProviderGroup {
	id: string;
	title: string;
	providers: ApiProvider[];
}

/**
 * The add-profile pages, as the core keeps them for one device: the picker, how to connect what was picked (a plan or
 * a key), and the form with what it will be usable for. The views draw it and name what changed (`profile.flow.edit`).
 */
export interface ProfileFlowView {
	/** pick | method | connect */
	step: string;
	station: string;
	title: string;
	hint: string;
	groups: ProviderGroup[];
	tile?: ApiProvider;
	/** plan | key, once chosen. */
	method?: string;
	/** At the method step: the two cards. */
	choices: FlowChoice[];
	showEndpoint: boolean;
	endpoint: string;
	endpointHint?: string;
	/** Asked only when there are more than one. */
	protocols: FlowOption[];
	protocol?: string;
	/** Asked only for a provider that runs in more than one region (international and China). */
	regions?: FlowOption[];
	region?: string;
	showKey: boolean;
	key: string;
	keyLabel: string;
	keyHint?: string;
	/** Shown under the key. */
	error?: string;
	canSubmit: boolean;
	pending: boolean;
	submitLabel: string;
	/** What the profile will be usable for, in words (the line under the page). */
	usesLine: string;
}

/** One station's copy of an account in the workspace's list. */
export interface ProfileMember {
	station: string;
	stationId: string;
	stationName: string;
	online: boolean;
	/** Its id on that station (its page there). */
	profileId: string;
	/** host: has it and lends it; user: borrows it (or a copy of a key); own: signed in there on its own. */
	role: string;
	/** What it is there, in words: 借给 mini / 向 studio 借 / 自己登录. */
	about: string;
	usable: boolean;
	checkText: string;
	checkTone: string;
	/** How many connects use it there. */
	usedBy: number;
}

export interface ShareStation {
	id: string;
	station: string;
	name: string;
	online: boolean;
	allowed: boolean;
}

/** An account in the workspace's list: the same subscription or key on several stations (shared or each signed in) is one. */
export interface WorkspaceProfile {
	/** The share's id, or station/profile for one on a station only. */
	key: string;
	/** The station whose copy this is (its page is there). */
	station: string;
	stationId: string;
	stationName: string;
	profile: Profile;
	shared: boolean;
	/** The station that has it (its id). */
	host: string;
	hostName: string;
	hostOnline: boolean;
	/** False for a shared subscription while the station signed in to it is away. */
	usable: boolean;
	/** Where it is, in words: 只在 studio / 登录在 studio · 只给 a、b. */
	where: string;
	/** The stations that may use a shared one; absent: every one. */
	allow?: string[];
	/** For a shared one: the workspace's stations and whether each may use it. */
	stations: ShareStation[];
	/** Its page is on the station that has it (its sharing can be changed there). */
	editable: boolean;
	/** Its station can share it (one older than sharing cannot). */
	canShare: boolean;
	/** Each station that has this account: one row, its page their parts. */
	members?: ProfileMember[];
}

/**
 * The workspace's profiles in one list (the `profiles` view): one shared between stations once, the others each with
 * the station they are on; usable ones first.
 */
export interface ProfilesView {
	items: WorkspaceProfile[];
	/** A station that is up is not read yet: its profiles come later. */
	loading: boolean;
}

/** A session with its threads and turns (`session` topic). */
export interface SessionDetail {
	session: Session;
	threads: ChatThread[];
	turns: TurnRecord[];
}

/** How a skill is shared between the workspace's stations. */
export interface SkillShare {
	id: string;
	/** host: shared from this station; user: a copy of another station's. */
	role: string;
	host: string;
	allow?: string[];
	/** Edits made on an older copy, kept beside the skill (SKILL.conflict-*.md), on its host. */
	conflicts?: string[];
}

/**
 * A skill: `body` its text as people read it (no frontmatter), `about` when it applies (a project's without its
 * 项目记忆：); both absent from a core before them.
 */
export interface SkillFile {
	name: string;
	description: string;
	project: boolean;
	builtin: boolean;
	text: string;
	body?: string;
	about?: string;
	/** Shared with the workspace's other stations, or another station's (absent: neither). */
	share?: SkillShare;
}

/** Address of a transient Slack token form, shared by calls and topic subscriptions. */
export interface SlackTokenForm {
	station: string;
	form: string;
}

/** A Slack token form: a transient core draft, never saved to device storage. */
export interface SlackTokensView {
	appToken: string;
	botToken: string;
	verified?: SlackIdentity;
	errors: string[];
	ready: boolean;
}

/** The agents' memory on a station (`memory.get`): the global one, and the skills (projects' memories among them). */
export interface StationMemory {
	global: MemoryFile;
	skills: SkillFile[];
}

/**
 * What the core is waiting on (the `status` topic), when it is worth saying: `state` slow (something has taken a
 * while) | trouble (a connection down), absent while all goes as it should; `text` says it in one line.
 */
export interface StatusView {
	state?: string;
	text?: string;
	items: StatusItem[];
}

/** Where a chat in the usage lists opens: its station, and its thread, or its agent's session. */
export interface UsageChat {
	station: string;
	thread?: number;
	session?: string;
}

/**
 * A day (`day` 2026-10-01, `label` 10/1): what it cost, split as `series` (`parts`, in dollars, and in words), and its
 * calls.
 */
export interface UsageDay {
	day: string;
	label: string;
	today: boolean;
	cost: number;
	costText: string;
	calls: number;
	callsText: string;
	parts: number[];
	partsText: string[];
}

/**
 * A person, chat, account or model, and what it spent: `share` of the total cost (of the calls, when nothing was
 * priced), `detail` its calls and tokens in a line. A person's `person` (with `shown`); a chat's page (`chat`), when
 * it is still there.
 */
export interface UsageItem {
	key: string;
	title: string;
	sub?: string;
	cost: number;
	costText: string;
	share: number;
	shareText: string;
	calls: number;
	detail: string;
	person?: Creator;
	chat?: UsageChat;
}

/** 按人 / 按对话 / 按账号 / 按模型 (`key` people, chats, profiles, models), the most spent first. */
export interface UsageList {
	key: string;
	title: string;
	items: UsageItem[];
}

export interface UsageRate {
	label: string;
	value: string;
}

export interface UsagePriceRow {
	model: string;
	rates: UsageRate[];
}

/** A station's own price table; its note explains missing data on older/offline stations. */
export interface UsagePriceTable {
	station: string;
	note: string;
	rows: UsagePriceRow[];
}

/** A part of each day's bar: a person (`key` their email or reference), or the rest (`key` empty). */
export interface UsageSeries {
	key: string;
	name: string;
}

/** 折合费用 $1,911 (按 API 价算). */
export interface UsageTile {
	label: string;
	value: string;
	sub: string;
}

/**
 * What the agents of a workspace spent over its last `days` (the `usage` view, client/core-ts/src/views/usage.ts): a few
 * totals (`tiles`), each day's cost split by the people who spent most (`series`, the rest as 其他), and lists of who,
 * which chats, which accounts and which models spent the most, at the providers' API prices (`basis` says what that
 * means). `notes`: what is missing or still being read, in lines; `loading` while a station has not answered.
 */
export interface UsageView {
	days: number;
	loading: boolean;
	empty: boolean;
	tiles: UsageTile[];
	series: UsageSeries[];
	daily: UsageDay[];
	/** The most a day cost (what the bars are drawn against). */
	max: number;
	lists: UsageList[];
	notes: string[];
	basis: string;
	/** Each station's own calculation table; absent with older cores. */
	prices?: UsagePriceTable[];
}

/**
 * A workspace's mark: of the chats its person takes part in, how many want them (blocked or failed) and how many
 * have something unread; of all its chats, how many have a decision waiting (`wait`); its `tone` (alert | wait | done, as a
 * chat's mark) and in words, none when it is 0 and 0; the chat last
 * open in it.
 */
export interface WorkspaceMark {
	alert: number;
	unread: number;
	/**
	 * How many have a card waiting (not dismissed by them) or an agent needing them (need_help), not counted in
	 * `alert`. Absent for 0.
	 */
	wait?: number;
	/** How many cards wait in it for them in all (奏 N). Absent for 0. */
	decisions?: number;
	tone?: string;
	/** 2 个需要处理 · 1 个在等你 · 3 个有新消息 */
	label?: string;
	chat?: OpenChat;
}

/**
 * What each workspace has waiting for its person, for where workspaces are switched (the `workspaceMarks` view):
 * by workspace id; and of those other than the one in view, the most urgent.
 */
export interface WorkspaceMarksView {
	workspaces: Record<string, WorkspaceMark>;
	/** alert | wait | done: the others' mark; none when nothing there wants anyone. */
	others?: string;
	/** 其他 workspace：1 个需要处理 · 2 个有新消息 */
	othersLabel?: string;
}

