// Generated by scripts/operations.py from client/core/src/ops.rs. Do not edit.
package fail.still.android.data

import kotlinx.serialization.json.*
import kotlin.properties.ReadWriteProperty
import kotlin.reflect.KProperty

/** A field is absent until assigned; assigning null sends JSON null (reset to default). */
val UNTRACKED_OPERATIONS = setOf("admin.me", "chats.archived", "job.get", "job.log", "login.drop", "machineSessions.list", "machineSessions.read", "memory.get", "session.warm", "slack.createAppUrl", "slack.people", "widget.setState", "widget.state")

open class OperationFields {
    internal val fields = mutableMapOf<String, JsonElement>()
    protected fun <T> field(name: String, encode: (T) -> JsonElement) = object : ReadWriteProperty<Any?, T?> {
        private var value: T? = null
        override fun getValue(thisRef: Any?, property: KProperty<*>): T? = value
        override fun setValue(thisRef: Any?, property: KProperty<*>, value: T?) {
            this.value = value; fields[name] = value?.let(encode) ?: JsonNull
        }
    }
}

class StationOperations(private val call: suspend (String, JsonObject) -> JsonElement) {
    suspend fun sessionStop(key: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["key"] = JsonPrimitive(key)
        return call("session.stop", JsonObject(values))
    }
    suspend fun sessionWarm(key: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["key"] = JsonPrimitive(key)
        return call("session.warm", JsonObject(values))
    }
    suspend fun sessionEvict(key: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["key"] = JsonPrimitive(key)
        return call("session.evict", JsonObject(values))
    }
    suspend fun sessionDelete(key: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["key"] = JsonPrimitive(key)
        return call("session.delete", JsonObject(values))
    }
    class SessionSettingsFields : OperationFields() {
        var profile: String? by field<String>("profile") { JsonPrimitive(it) }
        var model: String? by field<String>("model") { JsonPrimitive(it) }
        var effort: String? by field<String>("effort") { JsonPrimitive(it) }
    }
    suspend fun sessionSettings(key: String, fill: SessionSettingsFields.() -> Unit = {}): JsonElement {
        val values = SessionSettingsFields().apply(fill).fields
        values["key"] = JsonPrimitive(key)
        return call("session.settings", JsonObject(values))
    }
    class ChatArchiveFields : OperationFields() {
        var archived: Boolean? by field<Boolean>("archived") { JsonPrimitive(it) }
        var thread: Long? by field<Long>("thread") { JsonPrimitive(it) }
    }
    suspend fun chatArchive(session: String, fill: ChatArchiveFields.() -> Unit = {}): JsonElement {
        val values = ChatArchiveFields().apply(fill).fields
        values["session"] = JsonPrimitive(session)
        return call("chat.archive", JsonObject(values))
    }
    class ChatRenameFields : OperationFields() {
        var session: String? by field<String>("session") { JsonPrimitive(it) }
        var title: String? by field<String>("title") { JsonPrimitive(it) }
        var thread: Long? by field<Long>("thread") { JsonPrimitive(it) }
    }
    suspend fun chatRename(fill: ChatRenameFields.() -> Unit = {}): JsonElement {
        val values = ChatRenameFields().apply(fill).fields
        return call("chat.rename", JsonObject(values))
    }
    class ChatPinFields : OperationFields() {
        var pinned: Boolean? by field<Boolean>("pinned") { JsonPrimitive(it) }
    }
    suspend fun chatPin(session: String, fill: ChatPinFields.() -> Unit = {}): JsonElement {
        val values = ChatPinFields().apply(fill).fields
        values["session"] = JsonPrimitive(session)
        return call("chat.pin", JsonObject(values))
    }
    suspend fun decisionDismiss(thread: Long, seq: Long): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["thread"] = JsonPrimitive(thread)
        values["seq"] = JsonPrimitive(seq)
        return call("decision.dismiss", JsonObject(values))
    }
    suspend fun decisionClose(thread: Long, seq: Long): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["thread"] = JsonPrimitive(thread)
        values["seq"] = JsonPrimitive(seq)
        return call("decision.close", JsonObject(values))
    }
    class SessionNewFields : OperationFields() {
        var runtime: String? by field<String>("runtime") { JsonPrimitive(it) }
        var profile: String? by field<String>("profile") { JsonPrimitive(it) }
        var model: String? by field<String>("model") { JsonPrimitive(it) }
        var effort: String? by field<String>("effort") { JsonPrimitive(it) }
    }
    suspend fun sessionNew(fill: SessionNewFields.() -> Unit = {}): JsonElement {
        val values = SessionNewFields().apply(fill).fields
        return call("session.new", JsonObject(values))
    }
    suspend fun chatsArchived(): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        return call("chats.archived", JsonObject(values))
    }
    class ChatForSessionFields : OperationFields() {
        var session: String? by field<String>("session") { JsonPrimitive(it) }
    }
    suspend fun chatForSession(fill: ChatForSessionFields.() -> Unit = {}): JsonElement {
        val values = ChatForSessionFields().apply(fill).fields
        return call("chat.forSession", JsonObject(values))
    }
    suspend fun widgetState(key: String, path: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["key"] = JsonPrimitive(key)
        values["path"] = JsonPrimitive(path)
        return call("widget.state", JsonObject(values))
    }
    class WidgetSetStateFields : OperationFields() {
        var path: String? by field<String>("path") { JsonPrimitive(it) }
        var state: JsonElement? by field<JsonElement>("state") { it }
    }
    suspend fun widgetSetState(key: String, fill: WidgetSetStateFields.() -> Unit = {}): JsonElement {
        val values = WidgetSetStateFields().apply(fill).fields
        values["key"] = JsonPrimitive(key)
        return call("widget.setState", JsonObject(values))
    }
    suspend fun machineSessionsList(): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        return call("machineSessions.list", JsonObject(values))
    }
    class MachineSessionsReadFields : OperationFields() {
        var limit: Long? by field<Long>("limit") { JsonPrimitive(it) }
    }
    suspend fun machineSessionsRead(runtime: String, id: String, fill: MachineSessionsReadFields.() -> Unit = {}): JsonElement {
        val values = MachineSessionsReadFields().apply(fill).fields
        values["runtime"] = JsonPrimitive(runtime)
        values["id"] = JsonPrimitive(id)
        return call("machineSessions.read", JsonObject(values))
    }
    class MachineSessionsContinueFields : OperationFields() {
        var runtime: String? by field<String>("runtime") { JsonPrimitive(it) }
        var id: String? by field<String>("id") { JsonPrimitive(it) }
    }
    suspend fun machineSessionsContinue(fill: MachineSessionsContinueFields.() -> Unit = {}): JsonElement {
        val values = MachineSessionsContinueFields().apply(fill).fields
        return call("machineSessions.continue", JsonObject(values))
    }
    class ConnectCreateFields : OperationFields() {
        var input: JsonElement? by field<JsonElement>("input") { it }
        var id: String? by field<String>("id") { JsonPrimitive(it) }
    }
    suspend fun connectCreate(fill: ConnectCreateFields.() -> Unit = {}): JsonElement {
        val values = ConnectCreateFields().apply(fill).fields
        return call("connect.create", JsonObject(values))
    }
    class ConnectPutFields : OperationFields() {
        var input: JsonElement? by field<JsonElement>("input") { it }
    }
    suspend fun connectPut(id: String, fill: ConnectPutFields.() -> Unit = {}): JsonElement {
        val values = ConnectPutFields().apply(fill).fields
        values["id"] = JsonPrimitive(id)
        return call("connect.put", JsonObject(values))
    }
    suspend fun connectDelete(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("connect.delete", JsonObject(values))
    }
    suspend fun connectReconnect(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("connect.reconnect", JsonObject(values))
    }
    class ConnectBindSessionFields : OperationFields() {
        var session: String? by field<String>("session") { JsonPrimitive(it) }
        var title: String? by field<String>("title") { JsonPrimitive(it) }
    }
    suspend fun connectBindSession(connect: String, fill: ConnectBindSessionFields.() -> Unit = {}): JsonElement {
        val values = ConnectBindSessionFields().apply(fill).fields
        values["connect"] = JsonPrimitive(connect)
        return call("connect.bindSession", JsonObject(values))
    }
    class ConnectPutSlackAppFields : OperationFields() {
        var input: JsonElement? by field<JsonElement>("input") { it }
    }
    suspend fun connectPutSlackApp(connect: String, fill: ConnectPutSlackAppFields.() -> Unit = {}): JsonElement {
        val values = ConnectPutSlackAppFields().apply(fill).fields
        values["connect"] = JsonPrimitive(connect)
        return call("connect.putSlackApp", JsonObject(values))
    }
    class SlackVerifyFields : OperationFields() {
        var connect: String? by field<String>("connect") { JsonPrimitive(it) }
        var install: String? by field<String>("install") { JsonPrimitive(it) }
        var appToken: String? by field<String>("appToken") { JsonPrimitive(it) }
        var botToken: String? by field<String>("botToken") { JsonPrimitive(it) }
    }
    suspend fun slackVerify(fill: SlackVerifyFields.() -> Unit = {}): JsonElement {
        val values = SlackVerifyFields().apply(fill).fields
        return call("slack.verify", JsonObject(values))
    }
    class SlackMakeAppFields : OperationFields() {
        var team: String? by field<String>("team") { JsonPrimitive(it) }
        var settings: JsonElement? by field<JsonElement>("settings") { it }
        var icon: String? by field<String>("icon") { JsonPrimitive(it) }
    }
    suspend fun slackMakeApp(fill: SlackMakeAppFields.() -> Unit = {}): JsonElement {
        val values = SlackMakeAppFields().apply(fill).fields
        return call("slack.makeApp", JsonObject(values))
    }
    suspend fun slackDropApp(appId: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["appId"] = JsonPrimitive(appId)
        return call("slack.dropApp", JsonObject(values))
    }
    class SlackInstalledFields : OperationFields() {
        var code: String? by field<String>("code") { JsonPrimitive(it) }
        var state: String? by field<String>("state") { JsonPrimitive(it) }
    }
    suspend fun slackInstalled(fill: SlackInstalledFields.() -> Unit = {}): JsonElement {
        val values = SlackInstalledFields().apply(fill).fields
        return call("slack.installed", JsonObject(values))
    }
    class SlackAddConfigTokenFields : OperationFields() {
        var refreshToken: String? by field<String>("refreshToken") { JsonPrimitive(it) }
    }
    suspend fun slackAddConfigToken(fill: SlackAddConfigTokenFields.() -> Unit = {}): JsonElement {
        val values = SlackAddConfigTokenFields().apply(fill).fields
        return call("slack.addConfigToken", JsonObject(values))
    }
    suspend fun slackRemoveConfigToken(team: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["team"] = JsonPrimitive(team)
        return call("slack.removeConfigToken", JsonObject(values))
    }
    suspend fun slackPeople(): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        return call("slack.people", JsonObject(values))
    }
    suspend fun slackCreateAppUrl(name: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["name"] = JsonPrimitive(name)
        return call("slack.createAppUrl", JsonObject(values))
    }
    class SlackIdentityFields : OperationFields() {
        var bound: Boolean? by field<Boolean>("bound") { JsonPrimitive(it) }
    }
    suspend fun slackIdentity(user: String, fill: SlackIdentityFields.() -> Unit = {}): JsonElement {
        val values = SlackIdentityFields().apply(fill).fields
        values["user"] = JsonPrimitive(user)
        return call("slack.identity", JsonObject(values))
    }
    class ProfileAddFields : OperationFields() {
        var runtime: String? by field<String>("runtime") { JsonPrimitive(it) }
        var access: JsonElement? by field<JsonElement>("access") { it }
    }
    suspend fun profileAdd(fill: ProfileAddFields.() -> Unit = {}): JsonElement {
        val values = ProfileAddFields().apply(fill).fields
        return call("profile.add", JsonObject(values))
    }
    class ProfileUseMachineLoginFields : OperationFields() {
        var runtime: String? by field<String>("runtime") { JsonPrimitive(it) }
    }
    suspend fun profileUseMachineLogin(fill: ProfileUseMachineLoginFields.() -> Unit = {}): JsonElement {
        val values = ProfileUseMachineLoginFields().apply(fill).fields
        return call("profile.useMachineLogin", JsonObject(values))
    }
    class ProfilePutFields : OperationFields() {
        var input: JsonElement? by field<JsonElement>("input") { it }
    }
    suspend fun profilePut(id: String, fill: ProfilePutFields.() -> Unit = {}): JsonElement {
        val values = ProfilePutFields().apply(fill).fields
        values["id"] = JsonPrimitive(id)
        return call("profile.put", JsonObject(values))
    }
    suspend fun profileDelete(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("profile.delete", JsonObject(values))
    }
    suspend fun profileQuota(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("profile.quota", JsonObject(values))
    }
    suspend fun profileCheck(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("profile.check", JsonObject(values))
    }
    suspend fun profileLogin(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("profile.login", JsonObject(values))
    }
    suspend fun profileCancelLogin(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("profile.cancelLogin", JsonObject(values))
    }
    class ProfileLoginCodeFields : OperationFields() {
        var code: String? by field<String>("code") { JsonPrimitive(it) }
    }
    suspend fun profileLoginCode(id: String, fill: ProfileLoginCodeFields.() -> Unit = {}): JsonElement {
        val values = ProfileLoginCodeFields().apply(fill).fields
        values["id"] = JsonPrimitive(id)
        return call("profile.loginCode", JsonObject(values))
    }
    class LoginNewFields : OperationFields() {
        var runtime: String? by field<String>("runtime") { JsonPrimitive(it) }
    }
    suspend fun loginNew(fill: LoginNewFields.() -> Unit = {}): JsonElement {
        val values = LoginNewFields().apply(fill).fields
        return call("login.new", JsonObject(values))
    }
    class LoginCodeFields : OperationFields() {
        var code: String? by field<String>("code") { JsonPrimitive(it) }
    }
    suspend fun loginCode(id: String, fill: LoginCodeFields.() -> Unit = {}): JsonElement {
        val values = LoginCodeFields().apply(fill).fields
        values["id"] = JsonPrimitive(id)
        return call("login.code", JsonObject(values))
    }
    suspend fun loginDrop(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("login.drop", JsonObject(values))
    }
    suspend fun jobGet(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("job.get", JsonObject(values))
    }
    suspend fun jobLog(id: String, lines: Long): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        values["lines"] = JsonPrimitive(lines)
        return call("job.log", JsonObject(values))
    }
    suspend fun jobStop(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("job.stop", JsonObject(values))
    }
    suspend fun jobClearEnded(session: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["session"] = JsonPrimitive(session)
        return call("job.clearEnded", JsonObject(values))
    }
    suspend fun memoryGet(): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        return call("memory.get", JsonObject(values))
    }
    suspend fun footprintScan(): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        return call("footprint.scan", JsonObject(values))
    }
    class FootprintRebuildFields : OperationFields() {
        var keys: List<String>? by field<List<String>>("keys") { JsonArray(it.map(::JsonPrimitive)) }
    }
    suspend fun footprintRebuild(fill: FootprintRebuildFields.() -> Unit = {}): JsonElement {
        val values = FootprintRebuildFields().apply(fill).fields
        return call("footprint.rebuild", JsonObject(values))
    }
    class FootprintDeleteFields : OperationFields() {
        var keys: List<String>? by field<List<String>>("keys") { JsonArray(it.map(::JsonPrimitive)) }
    }
    suspend fun footprintDelete(fill: FootprintDeleteFields.() -> Unit = {}): JsonElement {
        val values = FootprintDeleteFields().apply(fill).fields
        return call("footprint.delete", JsonObject(values))
    }
    class FootprintEvictFields : OperationFields() {
        var keys: List<String>? by field<List<String>>("keys") { JsonArray(it.map(::JsonPrimitive)) }
    }
    suspend fun footprintEvict(fill: FootprintEvictFields.() -> Unit = {}): JsonElement {
        val values = FootprintEvictFields().apply(fill).fields
        return call("footprint.evict", JsonObject(values))
    }
    class SoftwareUpdateFields : OperationFields() {
        var id: String? by field<String>("id") { JsonPrimitive(it) }
    }
    suspend fun softwareUpdate(fill: SoftwareUpdateFields.() -> Unit = {}): JsonElement {
        val values = SoftwareUpdateFields().apply(fill).fields
        return call("software.update", JsonObject(values))
    }
    suspend fun softwareUpdateAll(): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        return call("software.updateAll", JsonObject(values))
    }
    suspend fun softwareCheck(): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        return call("software.check", JsonObject(values))
    }
    class SoftwareChannelFields : OperationFields() {
        var channel: String? by field<String>("channel") { JsonPrimitive(it) }
    }
    suspend fun softwareChannel(fill: SoftwareChannelFields.() -> Unit = {}): JsonElement {
        val values = SoftwareChannelFields().apply(fill).fields
        return call("software.channel", JsonObject(values))
    }
    class SoftwareAutoFields : OperationFields() {
        var on: Boolean? by field<Boolean>("on") { JsonPrimitive(it) }
    }
    suspend fun softwareAuto(fill: SoftwareAutoFields.() -> Unit = {}): JsonElement {
        val values = SoftwareAutoFields().apply(fill).fields
        return call("software.auto", JsonObject(values))
    }
}

class CloudOperations(private val call: suspend (String, JsonObject) -> JsonElement) {
    class WorkspaceCreateFields : OperationFields() {
        var name: String? by field<String>("name") { JsonPrimitive(it) }
        var invite_code: String? by field<String>("invite_code") { JsonPrimitive(it) }
    }
    suspend fun workspaceCreate(fill: WorkspaceCreateFields.() -> Unit = {}): JsonElement {
        val values = WorkspaceCreateFields().apply(fill).fields
        return call("workspace.create", JsonObject(values))
    }
    class WorkspaceRenameFields : OperationFields() {
        var name: String? by field<String>("name") { JsonPrimitive(it) }
    }
    suspend fun workspaceRename(workspace: String, fill: WorkspaceRenameFields.() -> Unit = {}): JsonElement {
        val values = WorkspaceRenameFields().apply(fill).fields
        values["workspace"] = JsonPrimitive(workspace)
        return call("workspace.rename", JsonObject(values))
    }
    suspend fun workspaceDelete(workspace: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["workspace"] = JsonPrimitive(workspace)
        return call("workspace.delete", JsonObject(values))
    }
    class WorkspaceInviteFields : OperationFields() {
        var role: String? by field<String>("role") { JsonPrimitive(it) }
        var email: String? by field<String>("email") { JsonPrimitive(it) }
    }
    suspend fun workspaceInvite(workspace: String, fill: WorkspaceInviteFields.() -> Unit = {}): JsonElement {
        val values = WorkspaceInviteFields().apply(fill).fields
        values["workspace"] = JsonPrimitive(workspace)
        return call("workspace.invite", JsonObject(values))
    }
    class WorkspaceAddMembersFields : OperationFields() {
        var role: String? by field<String>("role") { JsonPrimitive(it) }
        var emails: List<String>? by field<List<String>>("emails") { JsonArray(it.map(::JsonPrimitive)) }
    }
    suspend fun workspaceAddMembers(workspace: String, fill: WorkspaceAddMembersFields.() -> Unit = {}): JsonElement {
        val values = WorkspaceAddMembersFields().apply(fill).fields
        values["workspace"] = JsonPrimitive(workspace)
        return call("workspace.addMembers", JsonObject(values))
    }
    suspend fun workspaceRemoveAdded(workspace: String, email: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["workspace"] = JsonPrimitive(workspace)
        values["email"] = JsonPrimitive(email)
        return call("workspace.removeAdded", JsonObject(values))
    }
    suspend fun workspaceRevokeInvitation(workspace: String, invitation: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["workspace"] = JsonPrimitive(workspace)
        values["invitation"] = JsonPrimitive(invitation)
        return call("workspace.revokeInvitation", JsonObject(values))
    }
    class WorkspaceSetRoleFields : OperationFields() {
        var role: String? by field<String>("role") { JsonPrimitive(it) }
    }
    suspend fun workspaceSetRole(workspace: String, member: String, fill: WorkspaceSetRoleFields.() -> Unit = {}): JsonElement {
        val values = WorkspaceSetRoleFields().apply(fill).fields
        values["workspace"] = JsonPrimitive(workspace)
        values["member"] = JsonPrimitive(member)
        return call("workspace.setRole", JsonObject(values))
    }
    suspend fun workspaceRemoveMember(workspace: String, member: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["workspace"] = JsonPrimitive(workspace)
        values["member"] = JsonPrimitive(member)
        return call("workspace.removeMember", JsonObject(values))
    }
    class WorkspaceEnrollFields : OperationFields() {
        var name: String? by field<String>("name") { JsonPrimitive(it) }
    }
    suspend fun workspaceEnroll(workspace: String, fill: WorkspaceEnrollFields.() -> Unit = {}): JsonElement {
        val values = WorkspaceEnrollFields().apply(fill).fields
        values["workspace"] = JsonPrimitive(workspace)
        return call("workspace.enroll", JsonObject(values))
    }
    class WorkspaceRenameStationFields : OperationFields() {
        var name: String? by field<String>("name") { JsonPrimitive(it) }
    }
    suspend fun workspaceRenameStation(workspace: String, station: String, fill: WorkspaceRenameStationFields.() -> Unit = {}): JsonElement {
        val values = WorkspaceRenameStationFields().apply(fill).fields
        values["workspace"] = JsonPrimitive(workspace)
        values["station"] = JsonPrimitive(station)
        return call("workspace.renameStation", JsonObject(values))
    }
    suspend fun workspaceRemoveStation(workspace: String, station: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["workspace"] = JsonPrimitive(workspace)
        values["station"] = JsonPrimitive(station)
        return call("workspace.removeStation", JsonObject(values))
    }
    class InvitationPreviewFields : OperationFields() {
        var token: String? by field<String>("token") { JsonPrimitive(it) }
    }
    suspend fun invitationPreview(fill: InvitationPreviewFields.() -> Unit = {}): JsonElement {
        val values = InvitationPreviewFields().apply(fill).fields
        return call("invitation.preview", JsonObject(values))
    }
    class InvitationAcceptFields : OperationFields() {
        var id: String? by field<String>("id") { JsonPrimitive(it) }
        var token: String? by field<String>("token") { JsonPrimitive(it) }
    }
    suspend fun invitationAccept(fill: InvitationAcceptFields.() -> Unit = {}): JsonElement {
        val values = InvitationAcceptFields().apply(fill).fields
        return call("invitation.accept", JsonObject(values))
    }
    suspend fun invitationDecline(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("invitation.decline", JsonObject(values))
    }
    suspend fun loginSessionRevoke(id: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["id"] = JsonPrimitive(id)
        return call("loginSession.revoke", JsonObject(values))
    }
    suspend fun adminMe(): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        return call("admin.me", JsonObject(values))
    }
    class AdminCreateCodeFields : OperationFields() {
        var note: String? by field<String>("note") { JsonPrimitive(it) }
        var days: Long? by field<Long>("days") { JsonPrimitive(it) }
    }
    suspend fun adminCreateCode(fill: AdminCreateCodeFields.() -> Unit = {}): JsonElement {
        val values = AdminCreateCodeFields().apply(fill).fields
        return call("admin.createCode", JsonObject(values))
    }
    suspend fun adminRevokeCode(code: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["code"] = JsonPrimitive(code)
        return call("admin.revokeCode", JsonObject(values))
    }
    class AdminSetBetaFields : OperationFields() {
        var on: Boolean? by field<Boolean>("on") { JsonPrimitive(it) }
    }
    suspend fun adminSetBeta(user: String, fill: AdminSetBetaFields.() -> Unit = {}): JsonElement {
        val values = AdminSetBetaFields().apply(fill).fields
        values["user"] = JsonPrimitive(user)
        return call("admin.setBeta", JsonObject(values))
    }
    class AdminSetMayCreateFields : OperationFields() {
        var on: Boolean? by field<Boolean>("on") { JsonPrimitive(it) }
    }
    suspend fun adminSetMayCreate(user: String, fill: AdminSetMayCreateFields.() -> Unit = {}): JsonElement {
        val values = AdminSetMayCreateFields().apply(fill).fields
        values["user"] = JsonPrimitive(user)
        return call("admin.setMayCreate", JsonObject(values))
    }
    class AdminBlockFields : OperationFields() {
        var on: Boolean? by field<Boolean>("on") { JsonPrimitive(it) }
    }
    suspend fun adminBlock(user: String, fill: AdminBlockFields.() -> Unit = {}): JsonElement {
        val values = AdminBlockFields().apply(fill).fields
        values["user"] = JsonPrimitive(user)
        return call("admin.block", JsonObject(values))
    }
    suspend fun adminDeleteWorkspace(workspace: String): JsonElement {
        val values = mutableMapOf<String, JsonElement>()
        values["workspace"] = JsonPrimitive(workspace)
        return call("admin.deleteWorkspace", JsonObject(values))
    }
    class AdminFeedbackStatusFields : OperationFields() {
        var status: String? by field<String>("status") { JsonPrimitive(it) }
    }
    suspend fun adminFeedbackStatus(id: String, fill: AdminFeedbackStatusFields.() -> Unit = {}): JsonElement {
        val values = AdminFeedbackStatusFields().apply(fill).fields
        values["id"] = JsonPrimitive(id)
        return call("admin.feedbackStatus", JsonObject(values))
    }
}
