/**
 * Generated by scripts/shapes.sh from client/shapes (typeshare): do not edit.
 */

package fail.still.android.data

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.JsonClassDiscriminator

/// Whose account a profile runs on.
typealias AccessKind = String

@Serializable
data class Access (
	/// subscription | opencode-go | anthropic-api | env
	val kind: AccessKind,
	val key: String
)

/// What an agent at work does now (activity.rs): `key` names the thing (a step, or where the turn stands), `text` says
/// it; the same thing keeps its key while its words change.
@Serializable
data class ActivityNow (
	val key: String,
	val text: String
)

/// What an agent at work is doing, as a chat shows it (activity.rs).
@Serializable
data class Activity (
	val now: ActivityNow
)

/// A runtime.
typealias RuntimeKind = String

@Serializable
data class AgentProcess (
	val pgid: Long,
	val startedAt: Long,
	val runtime: RuntimeKind,
	val label: String,
	val rssMb: Double? = null
)

/// An agent waiting on work it started, which brings it back: since its turn ended, and at most how many seconds
/// until it is asked again (absent from a station yet to update).
@Serializable
data class AgentWait (
	val since: Long,
	val seconds: Long? = null,
	/// What it waits for in words, as its activity line says it (在等：CI 跑完; 等待中 from a station that does not say).
	val text: String? = null
)

/// A build of the app on still.fail cloud (`app.update`; scripts/release.sh puts it in /releases/<platform>/latest.json):
/// `file` is under /releases/.
@Serializable
data class AppRelease (
	val versionCode: Long,
	val versionName: String,
	val file: String,
	val sha256: String,
	val size: Long
)

/// An archived chat: its thread (or, an agent with no chat, only its session), its title and last line, when it was
/// archived (`at`, and `clock` 14:05) and how (`how`: 手动归档, 空闲后自动归档). `place`: its station's name, where there
/// is more than one to tell apart. Not `deletable` when archived alone (its agents still at work elsewhere).
@Serializable
data class ArchiveItem (
	val station: String,
	val session: String,
	val thread: Long? = null,
	val title: String,
	val last: String,
	val at: Double,
	val clock: String,
	val how: String,
	val deletable: Boolean,
	val place: String? = null
)

/// A day of the archive, headed as the chat list's (今天, 昨天, 星期三, 9月20日).
@Serializable
data class ArchiveDay (
	val label: String,
	val items: List<ArchiveItem>
)

@Serializable
data class ArchiveError (
	val station: String,
	val text: String
)

/// The archive of a scope's stations online (the `archive` topic): chats archived by hand or by their station once
/// idle, newest first by the day they were archived; what could not be read of it; and what the page says in place
/// of rows (reading, none), if anything. Restored (`chat.archive` with `archived` false) or deleted (`session.delete`),
/// a chat leaves it.
@Serializable
data class ArchiveView (
	val days: List<ArchiveDay>,
	/// A station's archive that could not be read, in a line (named where there are several).
	val errors: List<ArchiveError>,
	val loading: Boolean,
	val note: String? = null
)

@Serializable
data class Attachment (
	val name: String,
	val path: String,
	val size: Long,
	val width: Long? = null,
	val height: Long? = null,
	/// An image's ThumbHash (base64): a blurred likeness of it, shown until it loads.
	val thumbhash: String? = null
)

/// How full something is.
typealias Level = String

/// A window of a session's account running out, as its ring draws it.
@Serializable
data class QuotaAttention (
	val left: Long,
	val mark: String,
	val level: Level,
	val until: Long? = null
)

/// What is worth a look about a session now (account | quota | disk): what it says (`text`; for a quota, its tip's
/// first line, `more` the rest), and a quota's ring.
@Serializable
data class Attention (
	val kind: String,
	val text: String,
	val more: String? = null,
	val quota: QuotaAttention? = null
)

@Serializable
data class Bind (
	val runtime: RuntimeKind,
	val model: String? = null,
	val effort: String? = null,
	val profile: String? = null
)

/// A buddy a Slack app can wear (`buddies`): its picture is avatars/<id>.webp (and .thumb.webp), on `bg`.
@Serializable
data class Buddy (
	val id: String,
	val label: String,
	val bg: String
)

/// One change: its lines for people, the version it came in, where it is (`place`: the parts and version, empty when
/// it needed no release), whether this app has it (`has`: absent when it is not this app's), and what that means
/// (`note`: 你的版本已包含, 更新到 0.1.n 后就有, 还没发布, 已发布, 已上线); `mine`: it is this app's.
@Serializable
data class ChangelogItem (
	val version: Long,
	val versionName: String,
	val text: List<String>,
	val place: String,
	val has: Boolean? = null,
	val note: String,
	val mine: Boolean
)

/// A day's changes, under its heading (今天, 昨天, 9月20日).
@Serializable
data class ChangelogDay (
	val label: String,
	val entries: List<ChangelogItem>
)

/// What this app got since the changelog was last shown here: its `build` (0.1.n) and those changes.
@Serializable
data class ChangelogNews (
	val build: String? = null,
	val entries: List<ChangelogItem>
)

/// What changed in still.fail, as this app shows it (the `changelog` topic; client/core/src/changelog.rs): `app`
/// (web, desktop or android) and its `build` (0.1.<n>: n), absent before its host says; the changes by day, newest
/// first; what this app got since the changelog was last shown here (`news`, until `changelog.seen`); `loading` while
/// first read, `error` when it could not be and none was kept.
@Serializable
data class ChangelogView (
	val app: String? = null,
	val build: Long? = null,
	val days: List<ChangelogDay>,
	val news: ChangelogNews? = null,
	val loading: Boolean? = null,
	val error: String? = null
)

/// A person as the core names them: `display` is 你 for the viewer.
@Serializable
data class PersonShown (
	val name: String,
	val display: String,
	val picture: String? = null,
	val mine: Boolean
)

/// Who started a session or chat, or added a connect: an email, or "slack:<connect>:<user>"; "local" in records from
/// a station's own page, before it went.
@Serializable
data class Creator (
	val id: String,
	val name: String,
	val email: String? = null,
	/// local | cloud | slack
	val via: String,
	/// As the core names them.
	val shown: PersonShown? = null
)

/// The message a turn's state is about: its thread, its seq there, its ts.
@Serializable
data class TurnAbout (
	val thread: Long,
	val seq: Long,
	val ts: String
)

@Serializable
data class TurnSummary (
	val kind: String,
	val outcome: String? = null,
	val declared: String? = null,
	/// For waiting: at most how long, in seconds, until the agent is asked again (a station yet to update says none).
	val waitSeconds: Long? = null,
	/// For waiting: what it waits for, in the agent's words (a station yet to update says nothing).
	val waitFor: String? = null,
	/// How the agent ended it in today's words: all_done, need_help or waiting (`declared` keeps the words from before:
	/// final, block; a station before cards may say need_decision, which the core reads as need_help). A station yet to
	/// update says nothing.
	val ending: String? = null,
	/// For need_help: what a person has to give, do or decide, in the agent's words; for all_done, what the chat ends
	/// with.
	val need: String? = null,
	/// The message its state is about (the agent's `about`; for need_help, the card waiting by default). A station
	/// before it says nothing.
	val about: TurnAbout? = null,
	val detail: String? = null,
	val startedAt: Long,
	val endedAt: Long? = null
)

/// A colour of meaning.
typealias Tone = String

/// An agent's mark: at work, blocked, failed.
typealias Badge = String

/// Who made a model, for its mark; absent when the marks do not know it (the runtime's stands in).
@Serializable
data class Maker (
	val id: String,
	val name: String
)

/// A moment in words, fresh each minute: 3 分钟前 (`ago`), 9/20 14:05:09 (`full`), 3 小时后 (`until`), whether it has come.
@Serializable
data class Stamp (
	val at: Double,
	val ago: String,
	val full: String,
	val until: String,
	val past: Boolean
)

/// What a session keeps watch with (its watches running): their names, oldest first; since when the first runs; when
/// one last gave word (a notice, else its start).
@Serializable
data class Watching (
	val names: List<String>,
	val since: Long,
	val at: Long
)

/// A session, with what the clients show of it. Before its details are read an agent is only what the sidebar's rows
/// say of it (key, runtime, model, effort, process, pending, last turn): the rest is absent then.
@Serializable
data class Session (
	val key: String,
	val connect: String? = null,
	/// thread | all
	val scope: String? = null,
	val title: String? = null,
	val createdBy: String? = null,
	val boundTo: List<String>? = null,
	val creator: Creator? = null,
	val participants: List<Creator>? = null,
	/// claude | codex
	val runtime: RuntimeKind,
	val profile: String? = null,
	val profilePinned: Boolean? = null,
	val model: String? = null,
	val effort: String? = null,
	val fast: Boolean? = null,
	val runtimeSessionId: String? = null,
	val workspace: String? = null,
	val running: Boolean? = null,
	val createdAt: Long? = null,
	val lastActiveAt: Long? = null,
	val archivedAt: Long? = null,
	/// running | warm | cold
	val process: String,
	val turns: Long? = null,
	val pending: Long,
	val firstText: String? = null,
	val lastTurn: TurnSummary? = null,
	val statusText: String,
	/// accent | green | blue | red | neutral
	val tone: Tone,
	/// Its mark (run | block | failed), and in words.
	val mark: Badge? = null,
	val badgeText: String? = null,
	val titleText: String,
	val agentText: String,
	/// Its model as people call it (Opus 5.5).
	val modelName: String? = null,
	val maker: Maker? = null,
	val runtimeText: String,
	val processText: String? = null,
	/// How hard its runtime can think, lowest first.
	val efforts: List<String>,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null,
	/// On a connect's page: the chat it was last talked in; as a candidate to deliver into, described, and whether it
	/// is the one now.
	val chat: Long? = null,
	val description: String? = null,
	val current: Boolean? = null,
	/// Keeping watch (a `job_start` watch of its runs): its chat is a watching one. A station from before watches says none.
	val watch: Watching? = null
)

/// Where an agent stands.
typealias Status = String

/// How a connect's conversations become sessions.
typealias ConnectMode = String

@Serializable
data class SlackTokens (
	val appToken: String,
	val botToken: String
)

@Serializable
data class SlackIdentity (
	val team: String,
	val teamId: String,
	val url: String,
	val botUserId: String,
	val botName: String,
	/// Its bot's picture (the app's icon), when Slack says.
	val botImage: String? = null
)

/// A connect's link to Slack: disabled | no_tokens | starting | connected | reconnecting (`botUserId`, `lastError`,
/// `workspace`) | error (`error`).
@Serializable
data class ConnectState (
	val state: String,
	val botUserId: String? = null,
	val lastError: String? = null,
	val workspace: SlackIdentity? = null,
	val error: String? = null
)

@Serializable
data class Owner (
	val id: String,
	val name: String,
	/// As the core names them.
	val shown: PersonShown? = null
)

/// A link's dot.
typealias Presence = String

/// A connect, with its state and how it runs in words.
@Serializable
data class Connect (
	val id: String,
	val name: String,
	val team: String? = null,
	/// Its bot's picture in Slack, as last seen.
	val botImage: String? = null,
	val enabled: Boolean,
	val kind: String,
	/// multi-session | single-session
	val mode: ConnectMode,
	val requireMention: Boolean,
	val bind: Bind,
	val slack: SlackTokens,
	val connection: ConnectState,
	val createdBy: Owner? = null,
	val sessions: Long,
	val session: String? = null,
	val statusText: String,
	/// online | busy | error | offline
	val presence: Presence,
	val modeText: String,
	val modeShort: String,
	val runtimeText: String,
	val runText: String,
	/// Its bound model as people call it (Opus 5.5).
	val modelName: String? = null
)

@Serializable
data class EnvVar (
	val key: String,
	val secret: Boolean,
	val value: String
)

@Serializable
data class ProfileCheck (
	/// Runtime → model → supported reasoning levels; absent on older stations.
	val modelEfforts: Map<String, Map<String, List<String>>>? = null,
	/// ok | login | failed | unknown
	val state: String,
	val detail: String,
	val models: List<String>? = null,
	val checkedAt: Long,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null
)

@Serializable
data class LoginJob (
	val profile: String,
	val runtime: RuntimeKind,
	/// starting | needs_code | needs_approval | verifying | done | failed | cancelled
	val state: String,
	val url: String? = null,
	val userCode: String? = null,
	val error: String? = null,
	val startedAt: Long,
	val expiresAt: Long
)

@Serializable
data class QuotaCredits (
	val hasCredits: Boolean,
	val unlimited: Boolean,
	val balance: String? = null
)

/// A quota window, as drawn: its mark (5H, W), what is left, how full (ok | amber | red), when it refills in words.
@Serializable
data class QuotaWindow (
	val label: String,
	val usedPercent: Double,
	val resetsAt: Long? = null,
	val mark: String,
	val left: Long,
	val level: Level,
	val refills: String? = null,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null
)

/// An allowance: its windows shortest first.
@Serializable
data class Quota (
	val credits: QuotaCredits? = null,
	val resetCount: Long? = null,
	val creditsText: String? = null,
	val resetText: String? = null,
	/// ok | unsupported | unavailable | blocked (the provider refuses the account)
	val state: String,
	val windows: List<QuotaWindow>,
	val detail: String? = null,
	val checkedAt: Long,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null
)

@Serializable
data class ProfileTrouble (
	val title: String,
	val detail: String,
	val next: String,
	/// check | quota | login | command | key | env
	val action: String,
	val label: String
)

/// Models of one series (Opus), newest first.
@Serializable
data class ModelSeries (
	val name: String,
	val models: List<String>
)

/// A profile, with its last check in words and its models' makers.
@Serializable
data class Profile (
	val id: String,
	val name: String,
	/// The signed-in subscription identity; independent of the editable display name.
	val email: String? = null,
	val runtime: RuntimeKind,
	val runtimes: List<RuntimeKind>,
	val access: Access,
	val home: String,
	val homeExists: Boolean,
	val model: String? = null,
	val models: List<String>,
	/// Models changed by the pending selection; None when no selection is being saved.
	val modelsSaving: List<String>? = null,
	val env: List<EnvVar>,
	val usedBy: List<String>,
	val loginCommand: String,
	/// On the machine's own login of its runtime: not edited (but for its models) or signed in here; removing it stops using that login.
	val machine: Boolean? = null,
	/// Whether a message to a running Claude Code turn moves what it waits on to the background first; None from a
	/// station older than the setting.
	val backgroundOnMessage: Boolean? = null,
	val fast: Boolean? = null,
	val check: ProfileCheck? = null,
	val login: LoginJob? = null,
	val quota: Quota? = null,
	val checkText: String,
	val checkTone: Tone,
	/// The first problem to resolve, with its next step; absent when nothing needs attention.
	val trouble: ProfileTrouble? = null,
	/// The makers of its models, and of those its check found, by model.
	val makers: Map<String, Maker?>,
	/// Its models, its default and those its check found as people call them (Opus 5.5), by model.
	val names: Map<String, String>,
	/// Its models and those its check found, by series (Claude's biggest first, the rest by name; 其他 last), newest
	/// first: how the list to enable them from is laid out.
	val series: List<ModelSeries>,
	/// How many of the models it could run are enabled, in words.
	val modelsText: String,
	/// What can be enabled on it: what its provider lists, then whatever is enabled already, each once.
	val available: List<String>? = null
)

/// Used up until a time (or no one knows when), in words.
@Serializable
data class Spent (
	val until: Double? = null,
	val text: String,
	val back: String? = null
)

/// What is left of an account's allowance, in a few words: every window in gray, or only the one running low, with
/// its level.
@Serializable
data class QuotaLine (
	val text: String,
	val level: Level? = null
)

/// A profile that can run a model: `current` it runs on it now.
@Serializable
data class RunnableProfile (
	/// The chosen model’s reasoning levels on this account.
	val efforts: List<String>? = null,
	val id: String,
	val name: String,
	val current: Boolean,
	val spent: Spent? = null,
	val kind: AccessKind? = null,
	val runtime: RuntimeKind? = null,
	val quota: Quota? = null,
	/// What is left of its allowance, in a few words (a core from before it says nothing).
	val quotaLine: QuotaLine? = null
)

/// A model a station can run: its maker, the runtimes it runs on, and for each how hard it can think and who runs it.
@Serializable
data class ModelOption (
	/// The spelling a client sends: the one that is its key when a profile has that, else the first.
	val model: String,
	/// As people call it (Opus 5.5).
	val name: String,
	/// Its series (Opus, GPT), what a list groups it under; none when not known. Lists come by series, newest first.
	val family: String? = null,
	/// Every spelling of it the station's profiles have enabled (openai/gpt-6-astra, gpt-6-astra): one model.
	val ids: List<String>,
	val maker: Maker? = null,
	val runtimes: List<RuntimeKind>,
	val efforts: Map<String, List<String>>,
	val accounts: Map<String, List<RunnableProfile>>,
	val spent: Spent? = null
)

@Serializable
data class TurnRecord (
	val id: String,
	val kind: String,
	val outcome: String? = null,
	val declared: String? = null,
	/// In today's words (TurnSummary::ending).
	val ending: String? = null,
	/// For waiting: at most how long, in seconds, until the agent is asked again (a station yet to update says none).
	val waitSeconds: Long? = null,
	val detail: String? = null,
	val startedAt: Long,
	val endedAt: Long? = null
)

@Serializable
data class Membership (
	val thread: Long,
	val session: String,
	val connect: String,
	val joinedAt: Long
)

@Serializable
data class Quote (
	val author: String,
	val text: String,
	val comment: String,
	val ts: String? = null,
	/// agent | person | page (a mark on a previewed page) | image (a numbered mark on an image)
	val role: String? = null,
	/// The name of the file, among the message's attachments, that goes with it (a preview mark's screenshot).
	val file: String? = null
)

/// A message as merged from its thread's entries. In a chat, the core says whose it is and who said it.
@Serializable
data class Message (
	val seq: Long,
	val thread: Long,
	val ts: String,
	/// person | agent | ember
	val authorKind: String,
	val author: String,
	val authorName: String? = null,
	val text: String,
	val attachments: List<Attachment>,
	val quotes: List<Quote>,
	/// An agent's post that ended its turn: final, block (the words from before; `ending` has today's).
	val declared: String? = null,
	/// all_done, need_decision, need_help: how the post ended its agent's turn. A station yet to update says nothing.
	val ending: String? = null,
	val createdAt: Long,
	val editedAt: Long? = null,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null
)

/// A thread: a Slack thread or a chat on ember's page.
@Serializable
data class ChatThread (
	val id: Long,
	/// "slack:<team id>" or "ember".
	val surface: String,
	val channel: String,
	val channelName: String? = null,
	val threadTs: String,
	val title: String? = null,
	val createdBy: String? = null,
	val creator: Creator? = null,
	val createdAt: Long,
	val sessions: List<Membership>,
	val last: Long,
	val lastMessage: Message? = null,
	val read: Long,
	val unread: Long,
	val people: List<Creator>,
	val firstText: String? = null,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null
)

/// Something a job said, and when; `ago` (3 分钟前) and `clock` (13:04, 9/27 13:04) put in by the core.
@Serializable
data class JobNotice (
	val at: Long,
	val text: String,
	val ago: String? = null,
	val clock: String? = null
)

/// A part of a job's line: `word` its state's word (coloured as its dot), `notice` what it said (in the text's colour),
/// none the rest.
@Serializable
data class JobPart (
	val text: String,
	val kind: String? = null
)

/// The chat an open job is in.
@Serializable
data class JobChat (
	val id: String,
	val title: String? = null,
	val archived: Boolean? = null
)

/// A background job an agent started (a web service when it has a port): shown by its name; the port is how the
/// station reaches a service, not for people.
@Serializable
data class Job (
	val id: String,
	/// The session that started it (a chat's agents each have their own).
	val session: String? = null,
	val name: String,
	/// running | exited | stopped | failed (a service that exited is being started again)
	val state: String,
	val port: Long? = null,
	val exitCode: Long? = null,
	val startedAt: Long,
	val endedAt: Long? = null,
	/// What it runs (sh -c).
	val command: String? = null,
	/// How often a service was started again after it ended.
	val restarts: Long? = null,
	/// What it said lately (`ember-job notify`), newest first: how people see what a long-running job is up to.
	val notices: List<JobNotice>? = null,
	/// Started to keep watch (`job_start` watch). A station from before watches says none.
	val watch: Boolean? = null,
	/// When its output last grew; absent when it has none.
	val outputAt: Long? = null,
	/// Its dot: up (a service up), live (a job alive), restart (a service being started again), fail, off (over).
	val tone: String? = null,
	/// A web service (it has a port).
	val service: Boolean? = null,
	/// A service whose page can be opened: up, or being started again.
	val open: Boolean? = null,
	/// Over, so clearing takes it away (stopped, failed, ended by itself; not a service started again).
	val ended: Boolean? = null,
	/// It matters now: up, alive, restarting, or died lately (a day).
	val current: Boolean? = null,
	/// Its state in a word (在线, 在盯着, 意外退出…), coloured as its dot.
	val word: String? = null,
	/// The line under its name, in parts (see `JobPart`).
	val meta: List<JobPart>? = null,
	/// Its state, how long, and how many notices, as a detail's head says it: 在盯着 · 3 分钟 · 2 条通知.
	val detail: String? = null,
	/// When its output last grew, in words: 最后输出 · 3 分钟前.
	val outputSaid: String? = null,
	/// How long it has been up: 3 小时.
	val age: String? = null,
	/// Among the open ones (`longJobs`): its station, that station's name when there are several, the chat it is in as
	/// the viewer's sidebar has it, and all that in a line (studio · 修登录 · 已归档).
	val station: String? = null,
	val stationName: String? = null,
	val chat: JobChat? = null,
	val whereText: String? = null
)

/// An agent of a chat: its session, the connect that started it, its profile, and what it can move to.
@Serializable
data class ChatAgent (
	val session: Session,
	val status: Status,
	val badge: Badge? = null,
	val connect: Connect? = null,
	val profile: Profile? = null,
	val profiles: List<RunnableProfile>,
	/// The models it can move to, as its model control offers them; the account it runs on now.
	val choices: List<ModelOption>,
	val account: RunnableProfile? = null,
	val attention: List<Attention>,
	/// When its running turn began; absent when none runs.
	val since: Long? = null,
	/// While it waits on work it started (its turn ended as waiting): since when, and for how long at most.
	val wait: AgentWait? = null,
	/// Seen starting its turn while the chat shows (not at work already when first seen): its activity comes in.
	val started: Boolean? = null,
	val turns: List<TurnRecord>,
	val threads: List<ChatThread>,
	/// Its background jobs, newest first; those with a port are web services, shown by their names.
	val jobs: List<Job>
)

/// An agent of a sidebar row, with what its mark shows.
@Serializable
data class RowAgent (
	val key: String,
	val runtime: RuntimeKind,
	val model: String? = null,
	val effort: String? = null,
	val process: String,
	val pending: Long,
	val lastTurn: TurnSummary? = null,
	val agentText: String,
	val maker: Maker? = null,
	val mark: Badge? = null,
	val statusText: String,
	val badgeText: String? = null,
	/// Keeping watch, as its session's `watch`.
	val watch: Watching? = null
)

/// Who said a row's last thing: an agent (its state riding on its picture), a person, or ember.
@Serializable
data class LastBy (
	/// agent | person | ember
	val kind: String,
	val name: String,
	val mine: Boolean,
	val model: String? = null,
	val runtime: RuntimeKind? = null,
	/// block | run | failed
	val state: Badge? = null,
	val id: String? = null,
	val picture: String? = null,
	/// What its picture says when pointed at: who, and an agent's state.
	val label: String,
	val maker: Maker? = null
)

/// A row's last message, its text cut to 200 characters; `preview` its line.
@Serializable
data class RowMessage (
	val seq: Long,
	val authorKind: String,
	val author: String,
	val authorName: String? = null,
	val text: String,
	val createdAt: Long,
	val by: LastBy? = null,
	val preview: String,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null
)

@Serializable
data class Origin (
	val teamName: String? = null,
	val channel: String,
	val channelName: String? = null,
	val threadTs: String
)

/// Someone in a chat, named as the core names them.
@Serializable
data class Person (
	val id: String,
	val name: String,
	val email: String? = null,
	val via: String,
	val shown: PersonShown
)

/// A watching chat (core, present.rs): what it watches in words (监控中：盯 CI), and what archiving it by hand asks
/// first (`ask`: it runs on in the archive).
@Serializable
data class RowWatch (
	val text: String,
	val ask: String
)

/// One answer a decision offers (an agent's block post with chat_post `options`): a short phrase that reads on its own,
/// a line on what it leads to, and whether the agent recommends it.
@Serializable
data class DecisionOption (
	val label: String,
	val detail: String? = null,
	val recommended: Boolean? = null
)

/// What an agent's message asks people to answer it with (core decisions.rs): `type` options (`options`, as shown: the
/// recommended one last; a tap answers, `decision.answer`) or text (a field to write in, with a `placeholder`;
/// `decision.reply`). A type a UI does not know: answered by writing in the chat.
@Serializable
data class MessageCard (
	/// The person the agent asks to decide, by email. Absent on legacy cards.
	val assignee: String? = null,
	/// Who needs to decide, in the viewer's words; prepared by the core.
	val assigneeText: String? = null,
	/// options | text
	val type: String,
	val options: List<DecisionOption>? = null,
	val placeholder: String? = null
)

/// A chat's card still pending (a row's, a chat page's; named for when the only cards were decisions): its post's entry,
/// the card as shown, an options card's options in the order they are shown (the recommended one last; empty for a
/// text card), whether the viewer dismissed it, and its line (奏 · …) while it is the viewer's.
@Serializable
data class RowDecision (
	val seq: Long,
	val options: List<DecisionOption>,
	/// The card itself. A core before cards says none: an options card.
	val card: MessageCard? = null,
	val dismissed: Boolean? = null,
	/// 奏 · <the post's first line, cut to about 40 characters>. Absent once dismissed.
	val text: String? = null
)

/// An item of the sidebar, as its station puts it together for the viewer, and where it is.
@Serializable
data class ChatItem (
	val id: String,
	val session: String,
	val thread: Long? = null,
	val title: String,
	val agents: List<RowAgent>,
	val last: RowMessage? = null,
	val unread: Boolean,
	val mine: Boolean,
	val lastActiveAt: Long,
	val connect: String? = null,
	val origin: Origin? = null,
	val station: String,
	val stationName: String,
	/// block | run | failed
	val state: Badge? = null,
	/// Where it came from (Slack · workspace · #channel), for a Slack chat.
	val originText: String? = null,
	/// Its station is offline, in words ("Studio 离线"): the row is shown greyed and marked. Absent while online.
	val offline: String? = null,
	/// Its station's link coming back, or failing and retried, in words ("正在重连 Studio…"): the row is marked with a
	/// turning ring. Absent while linked (and while offline).
	val reconnecting: String? = null,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null,
	/// A new chat asked for here that its station has not made yet. Absent otherwise.
	val pending: Boolean? = null,
	/// Who is in it, for its pictures: who started it first, then everyone who wrote in it, each once. From a
	/// station that does not say: absent.
	val people: List<Person>? = null,
	/// Who started it, as in `people`.
	val creator: Creator? = null,
	/// Its people in words, who started it said ("小王 发起 · Lina、你"), with `people`.
	val peopleText: String? = null,
	/// The key a chat asked for here went by before its station made it: the list keeps it one row throughout. Older stations do not say it.
	val clientKey: String? = null,
	/// Pinned by the viewer to the top of their list. Absent when its station does not know pins (it cannot be pinned).
	val pinned: Boolean? = null,
	/// A watching chat (one of its agents keeps watch): archiving it by hand asks first. Absent otherwise.
	val watch: RowWatch? = null,
	/// The card it waits on (an agent's post with a card no one has answered yet), as the viewer sees it. Absent when
	/// there is none (and from a station before decisions).
	val decision: RowDecision? = null,
	/// Nothing is left in it: each of its agents ended all_done, nothing at work, no card waiting for the viewer,
	/// nothing unread. Drawn faded, below the rest of its day (the core orders it so). Absent otherwise.
	val settled: Boolean? = null,
	/// With `settled`: offer to archive it with one tap (`chat.archive`). Absent otherwise.
	val archivable: Boolean? = null,
	/// Where it stands, in words, for its second line, its agents' states first: 要你帮忙：…, 出问题：…; then 奏 · … (a
	/// card waiting for the viewer, even while an agent works); then 在等：…, 做完了(：…). Absent while it is at work with
	/// no card waiting, or with nothing to say.
	val stateText: String? = null,
	/// The message `stateText` is about (a seq in this chat): the card, or the one the agent's state names. Opening the
	/// chat from the line may go to it. Absent when none.
	val stateAbout: Long? = null,
	/// Its mark, the most urgent first: alert (an agent failed), wait (a card waits, not dismissed by the viewer; or an
	/// agent needs them: need_help), busy (at work), done (something unread). Absent for none.
	val tone: String? = null
)

/// A day of the list, with its heading (今天, 昨天, 星期三, 9月20日); or, above them all, the chats the viewer pinned
/// (`pinned`, `daysAgo` -1, headed 已固定).
@Serializable
data class ChatDay (
	val daysAgo: Long,
	val at: Double,
	val label: String,
	val items: List<ChatItem>,
	val pinned: Boolean? = null
)

/// A chat's services and background jobs as its pages show them (the `chatJobs` view): every one, those that matter
/// now first (died, restarting, up and alive, over; newest first within each); what the button's dot says; each
/// group's head's note; how many matter now, how many are over and whose they are (clearing them is per session).
@Serializable
data class ChatJobsView (
	val jobs: List<Job>,
	/// fail: one died lately; restart: a service is being started again.
	val alarm: String? = null,
	/// 2 个在线，1 个在重启; 1 个在盯着 (empty: nothing to say).
	val servicesNote: String,
	val jobsNote: String,
	val current: Long,
	val ended: Long,
	/// The sessions whose jobs that are over clearing takes away (`job.clearEnded` each).
	val clear: List<String>,
	/// 全部 5 个; 清掉 2 个已结束的; 另有 2 个已停止或结束.
	val allText: String,
	val clearText: String,
	val hiddenText: String
)

/// Who said a message, as its line shows them: an agent by its label and mark, a person by name and picture.
@Serializable
data class MessageBy (
	val name: String,
	val agent: String? = null,
	val maker: Maker? = null,
	val runtime: RuntimeKind? = null,
	val picture: String? = null
)

/// Where a decision in a chat's messages stands (core, decisions.rs): still waiting (no person has written since it was
/// asked, and no newer one replaced it), or `resolved`, with who answered and whether by picking an option.
@Serializable
data class MessageDecision (
	val resolved: Boolean,
	/// Still waiting, and the viewer dismissed it (off their list; the options still work).
	val dismissed: Boolean? = null,
	/// Who answered it (the first person to write after it), by name; absent while it waits, or when a newer decision
	/// replaced it.
	val answeredBy: String? = null,
	/// The option they picked (their message quoted it with an option's label), its label.
	val chosen: String? = null,
	/// Resolved, in words: 林晓 选了「先不改」, 林晓 回复了, 已换成新的问题.
	val text: String? = null
)

/// A message of a chat, with what the core decides of it: the viewer's (their bubble), ember's own notice, who said
/// it, and whether its agents have yet to take it.
@Serializable
data class ChatMessage (
	/// The local outbox identity this message replaced, when sent from this core.
	val outgoing: String? = null,
	val seq: Long,
	val thread: Long,
	val ts: String,
	/// person | agent | ember
	val authorKind: String,
	val author: String,
	val authorName: String? = null,
	val text: String,
	val attachments: List<Attachment>,
	val quotes: List<Quote>,
	/// An agent's post that ended its turn: final, block (the words from before; `ending` has today's).
	val declared: String? = null,
	/// all_done, need_decision, need_help: how the post ended its agent's turn. A station yet to update says nothing.
	val ending: String? = null,
	val createdAt: Long,
	val editedAt: Long? = null,
	val mine: Boolean,
	val system: Boolean,
	/// ember's notice about one of the station's profiles (its sign-in failed): that profile's id, for a link to it.
	val profile: String? = null,
	val by: MessageBy,
	val waiting: Boolean,
	/// Said while the chat shows (told as it was said, not caught up on): it comes in rather than being there at once.
	/// Decided by the core once, when first seen (attend.rs).
	val said: Boolean? = null,
	/// Its times in words, by field (`createdAt`).
	val time: Map<String, Stamp>? = null,
	/// An agent's post with an options card: the answers to pick, in the order they are shown (the one the agent
	/// recommends last), as `card.options`; drawn under the message. Absent for every other message.
	val options: List<DecisionOption>? = null,
	/// The card it carries (options to pick, or a text field), as shown. Absent for a message with none.
	val card: MessageCard? = null,
	/// With a card: whether it still waits for an answer, and who answered it how.
	val decision: MessageDecision? = null
)

/// The chats a few words find (the `chatSearch` topic): as the sidebar has them, those whose title has the words
/// first. What the composer's `@` menu and the switcher list.
@Serializable
data class ChatSearchView (
	val items: List<ChatItem>
)

/// Who is looking: the account that reaches the workspace, by its email.
@Serializable
data class Me (
	val id: String? = null,
	val email: String? = null
)

/// A message sent from here that the chat does not show yet (sending | failed); `seq` once the station has it.
@Serializable
data class Outgoing (
	val id: String,
	val text: String,
	val attachments: List<Attachment>,
	val quotes: List<Quote>,
	val createdAt: Long,
	val state: String,
	val error: String? = null,
	val seq: Long? = null,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null
)

/// A station's mesh link: connecting | online | offline | error.
@Serializable
data class Link (
	val state: String,
	val message: String? = null
)

/// A chat's link to its station while it is not as it should be: `tone` trouble (down; `detail` why) | busy (coming
/// back), and the line that says it.
@Serializable
data class LinkShown (
	val tone: String,
	val text: String,
	val detail: String? = null
)

/// An item's page: its chat (with the viewer's read position), or its agent before it has one.
@Serializable
data class ChatView (
	/// The newest message asks for attention or gives a final result: dim earlier messages only at the scroll end.
	val focusLast: Boolean? = null,
	/// Archived chats must be restored before composing another message.
	val archived: Boolean? = null,
	/// Pinned to the top of the viewer's list. Absent when its station does not know pins (it cannot be pinned).
	val pinned: Boolean? = null,
	val me: Me,
	val thread: ChatThread? = null,
	val title: String,
	/// Where a Slack chat is (#channel, 私信), and its link in Slack while its connect is signed in.
	val place: String? = null,
	val slackUrl: String? = null,
	val people: List<Person>,
	val agents: List<ChatAgent>,
	val messages: List<ChatMessage>,
	val more: Boolean,
	/// Entries after those loaded: the chat shows a window short of its end (`chat.newer` loads the next page,
	/// `chat.latest` goes to the end). What is said meanwhile waits there, counted in its thread's `unread`.
	val newer: Boolean? = null,
	/// The entry the chat opened at when not at its end (its first unread, or where it was left): the list shows it
	/// at its top. Absent when it opened at its end.
	val at: Long? = null,
	/// Opened where it was left (`at`): how far below the top of the list that entry's top was then, as the client
	/// that left it said (`chat.place`). Absent otherwise, and from a core before it.
	val atOffset: Double? = null,
	/// The last message caught up on (read: kept on the device, a page, what was missed) rather than said while the
	/// chat is open. The core decides from it which come in (`ChatMessage::said`); clients go by that.
	val caught: Long? = null,
	/// The message the unread line goes over: the first the viewer had not read when the chat was opened (not
	/// theirs); none while older pages are loaded to find it, or with nothing unread. Absent from a core before it.
	val unreadLine: Long? = null,
	/// The unread line lies above the messages loaded: older pages are being loaded to find it.
	val unreadAbove: Boolean? = null,
	val outbox: List<Outgoing>,
	val link: Link,
	val offline: Boolean,
	/// One of its agents keeps watch: archiving it by hand asks first. Absent otherwise.
	val watch: RowWatch? = null,
	/// A new chat asked for here that its station has not made yet: what is sent to it waits in its outbox.
	val pending: Boolean? = null,
	/// The key its station gave a chat asked for here, once made: the page, opened under the core's key, goes by it.
	val key: String? = null,
	/// Why the station could not make it, the last time it was tried.
	val failed: String? = null,
	/// Its link while it is down or coming back, in words; absent while it is up (and from a core before it).
	val connection: LinkShown? = null,
	/// The card it waits on, as its row has it. Absent when there is none.
	val decision: RowDecision? = null,
	/// Nothing is left in it (as its row's `settled`), and it is not archived: offer to archive it with one tap
	/// (`chat.archive`). Absent otherwise.
	val archivable: Boolean? = null
)

@Serializable
data class StationState (
	val station: String,
	val id: String,
	val name: String,
	/// online | connecting | offline | error
	val state: String,
	val message: String? = null
)

/// What is wrong with the workspace's stations, in a line, and the worst of it: offline | error | reconnecting.
/// `retry`: always false now (a station down is tried again from the stations' page); true from older cores while down.
@Serializable
data class StationTrouble (
	val text: String,
	val state: String,
	val retry: Boolean? = null
)

/// Whose pictures lead the rows of a list (`ChatsView::leading`).
typealias Lead = String

/// The stations at a glance (the glyph): how many are online, offline or connecting (`dim`), failing, and at work; the
/// line beside it while all is well (the one station by name, else how many; and who works), and all of it in words.
@Serializable
data class StationsGlyph (
	val online: Long,
	val dim: Long,
	val failing: Long,
	val working: Long,
	val summary: String,
	val label: String
)

@Serializable
data class StationFailing (
	val station: String,
	val text: String,
	val message: String? = null
)

/// What a list with no rows to show says in their place: it is still reading, the stations it cannot reach (`text`
/// says so, `message` why), or there is nothing (`empty`). All false and none with rows to show.
@Serializable
data class ListNote (
	val reading: Boolean,
	val failing: List<StationFailing>,
	val empty: Boolean
)

@Serializable
data class ChatsView (
	val me: Me,
	val stations: List<StationState>,
	val loading: Boolean,
	val days: List<ChatDay>,
	/// The stations not working as they should, in a line ("MBA 离线", "正在重连 Studio", "2 台 station 异常"), for a
	/// corner of the list; absent while all are (a station first connecting is not one).
	val trouble: StationTrouble? = null,
	/// How many people the scope has, for how rows are pictured; absent until known.
	val members: Long? = null,
	/// Whose pictures lead the rows: the device's setting (`prefs`), 自动 by `members` (unknown: as if alone).
	val leading: Lead? = null,
	/// The stations at a glance, and what the list says with no rows; absent from a core before them.
	val glyph: StationsGlyph? = null,
	val note: ListNote? = null
)

@Serializable
data class ConfigTokenOwner (
	val team: String,
	val teamDomain: String? = null,
	val teamIcon: String? = null,
	val user: String,
	val email: String? = null,
	val image: String? = null
)

@Serializable
data class ConnectAppSettings (
	val name: String,
	val displayName: String,
	val description: String,
	val longDescription: String,
	val backgroundColor: String,
	val groups: Map<String, Boolean>
)

@Serializable
data class SlackTeam (
	val teamId: String,
	val name: String,
	val owner: ConfigTokenOwner? = null
)

@Serializable
data class SlackAppLinks (
	val settings: String,
	val install: String,
	val appToken: String,
	val oauth: String
)

/// A Slack app ember made that no connect has taken yet, as its maker sees it (never its secrets or tokens).
@Serializable
data class MadeSlackApp (
	val appId: String,
	val name: String,
	val teamId: String,
	/// The Slack workspace's name, when its configuration token says.
	val team: String? = null,
	val created: Long,
	val links: SlackAppLinks,
	/// The link that installs it through Slack's OAuth (a station in still.fail cloud); none when its tokens are copied by hand.
	val install: String? = null,
	/// Its install's state, what a connect names it by.
	val state: String? = null,
	val installed: Boolean,
	val installedTeam: String? = null
)

/// What a chat runs on: `model` none when none is chosen; `effort` none the default depth; `profile` none the
/// station's pick.
@Serializable
data class Picked (
	val model: String? = null,
	val runtime: RuntimeKind,
	val effort: String? = null,
	val fast: Boolean? = null,
	val profile: String? = null
)

/// The account a model control names: kept to (`auto` false), or the station's pick; `level` its window running low.
@Serializable
data class PickAccount (
	val text: String,
	val auto: Boolean,
	val level: Level? = null,
	val profile: RunnableProfile? = null
)

/// A model control (the `pick` topic): what runs it now (`value`), what is picked in its panel so far (`draft`,
/// until `pick.save`), and what they say. An account kept to that does not run the model picked gives way to the
/// station's pick, said so (`dropped`, `force`).
@Serializable
data class PickView (
	val fastAvailable: Boolean? = null,
	val fastText: String? = null,
	val options: List<ModelOption>,
	val runtimeFixed: Boolean,
	val value: Picked,
	val valueOption: ModelOption? = null,
	/// The account the control names; none: it names none (a new chat's, while the station's pick is fine).
	val account: PickAccount? = null,
	val draft: Picked,
	/// The option picked in the panel, by its `model`.
	val option: String? = null,
	/// The runtimes offered for it (none: not asked), how hard it can think there, who can run it.
	val runtimes: List<RuntimeKind>,
	val efforts: List<String>,
	val accounts: List<RunnableProfile>,
	val dropped: String? = null,
	/// The way to the accounts in the panel's foot: the one kept to, short, or 账号; amber when one gave way or the
	/// station's pick runs low.
	val who: String,
	val whoLevel: Level? = null,
	/// The station's pick, said: who it is on now, or what it does.
	val autoNote: String,
	val changed: Boolean,
	/// Full screen (the phone's): the model, depth and account as they were and as they become; why the account
	/// must change; the model and account picked in words; what the button says.
	val was: List<String>,
	val becomes: List<String>,
	val force: String? = null,
	val modelText: String,
	val maker: Maker? = null,
	val accountText: String,
	val accountNote: String,
	val accountWarn: Boolean,
	val saveText: String
)

/// One transient connect wizard. Decisions and navigation come from the core on every client.
@Serializable
data class ConnectFlowView (
	val step: String,
	val title: String,
	val back: String,
	val number: UInt,
	val total: UInt,
	val resume: String? = null,
	val mobile: Boolean,
	val team: String? = null,
	val adding: Boolean,
	val settings: ConnectAppSettings,
	val icon: String? = null,
	val iconError: String? = null,
	val madeId: String? = null,
	val config: String,
	val configReady: Boolean,
	val configError: String? = null,
	val mode: ConnectMode,
	val requireMention: Boolean,
	val gettingToken: Boolean,
	val noProfile: Boolean,
	val canMake: Boolean,
	val canCreate: Boolean,
	val teams: List<SlackTeam>,
	val chosen: SlackTeam? = null,
	val made: MadeSlackApp? = null,
	val pick: PickView? = null
)

@Serializable
data class ConnectItem (
	val station: String,
	val stationName: String,
	val connect: Connect,
	/// Its latest dozen; the one it delivers into; those it could deliver into instead.
	val sessions: List<Session>,
	val bound: Session? = null,
	val candidates: List<Session>,
	val running: Long
)

/// One thing waited on: what (`text`), how long or how much (`detail`), and whether it is slow | trouble.
@Serializable
data class StatusItem (
	val state: String,
	val text: String,
	val detail: String
)

/// What a chat says of its connection (the `connection` topic; client/core/src/pill.rs), all decided in the core:
/// `tone` busy (its link coming back, or something of its workspace waited on a while) | trouble (down) | back (up
/// again, for a moment after a busy or trouble was shown), absent while there is nothing to say; `text` the line,
/// `detail` beside it, `items` each thing waited on (on hover).
@Serializable
data class ConnectionView (
	val tone: String? = null,
	val text: String? = null,
	val detail: String? = null,
	val items: List<StatusItem>
)

@Serializable
data class ConnectsView (
	val me: Me,
	val items: List<ConnectItem>,
	val loading: Boolean
)

@Serializable
data class Counts (
	val sessions: Long,
	val running: Long,
	val warm: Long
)

/// One card on the 奏 page: where it is, the post that asks (as a chat shows messages, with its card) and the messages
/// just before it, the card (an options card's options as shown, also as `options`), and whether the viewer set it
/// aside on this device. An options card is answered with `decision.answer`, a text card with `decision.reply`.
@Serializable
data class DecisionItem (
	val station: String,
	val stationName: String,
	/// Its chat's item id (its session's key): what its page opens by.
	val session: String,
	val thread: Long,
	/// Its chat's title.
	val title: String,
	val seq: Long,
	val message: ChatMessage,
	/// The one or two messages before it, oldest first.
	val before: List<ChatMessage>,
	val options: List<DecisionOption>,
	/// The card. A core before cards says none: an options card.
	val card: MessageCard? = null,
	/// Set aside (待定) on this device: last in the list, still pending.
	val deferred: Boolean? = null,
	/// 奏 · <the post's first line>
	val text: String
)

/// The cards waiting in a workspace's chats for the viewer (the `decisions` view, the 奏 page, core decisions.rs):
/// pending whatever their agents do, not dismissed by them, those they set aside (待定) last; `count` for 奏 N.
@Serializable
data class DecisionsView (
	val items: List<DecisionItem>,
	val count: UInt,
	/// Some station's chats are still being read: more may come.
	val loading: Boolean
)

/// What this device is, as its host told the core at start (`client.device`), and what follows from it.
@Serializable
data class DeviceView (
	/// `web`, `desktop` or `android`; empty until told.
	val app: String? = null,
	/// A phone (the Android app, or a phone's browser).
	val phone: Boolean? = null,
	/// An item's link from outside is offered to the desktop app first (a computer's browser).
	val handoff: Boolean? = null
)

@Serializable
data class Disk (
	val path: String,
	val totalBytes: Long,
	val freeBytes: Long
)

@Serializable
data class DiskRoom (
	val freeBytes: Long,
	val totalBytes: Long
)

/// A call under way: its name (`job.stop`), its params that are words, numbers or yes/no, as words (what a page
/// matches it by), and since when; `stage` running, rechecking (its station went quiet before it answered: asked again
/// once it is back, `note` saying so), or failed (kept a few seconds, `error` saying why). A core from before stages
/// gives none: running.
@Serializable
data class DoingItem (
	val call: String,
	val params: Map<String, String>,
	val since: Long,
	val stage: String? = null,
	val error: String? = null,
	val note: String? = null
)

/// What people set going on this device and the core has not finished (the `doing` topic; client/core/src/doing.rs),
/// oldest first.
@Serializable
data class DoingView (
	val doing: List<DoingItem>
)

/// What is being written to a chat on this device (the `draft` topic, `draft.put`): its text as typed, the passages
/// it quotes with what is said about them, and the files already up (the station keeps them in no chat until a
/// message takes them). Files still going up are the page's own.
@Serializable
data class DraftView (
	val text: String,
	val quotes: List<Quote>,
	val files: List<Attachment>
)

@Serializable
data class FootprintConfirm (
	val title: String,
	val text: String,
	val action: String,
	val danger: Boolean
)

/// One way to clean: `call` (footprint.rebuild, footprint.delete, footprint.evict) with `keys`, after each of `confirms` is agreed
/// to in turn; `done` is said after.
@Serializable
data class FootprintChoice (
	val label: String,
	val call: String,
	val keys: List<String>,
	val confirms: List<FootprintConfirm>,
	val done: String
)

/// A clean-up offered: its line, and the choices it has (one, or several: all archived chats, or the older ones).
@Serializable
data class FootprintAction (
	val id: String,
	val title: String,
	val note: String,
	/// The button's words.
	val action: String,
	val danger: Boolean,
	/// Asked first when there are several: which one.
	val pick: String? = null,
	val choices: List<FootprintChoice>
)

/// How much of the disk a station takes, for the row that opens its footprint page.
@Serializable
data class FootprintBrief (
	/// None before its first measure.
	val bytes: Long? = null,
	val scanning: Boolean? = null,
	/// What the core says of it: 12.3 GB, 正在统计….
	val text: String? = null
)

/// A chat's directory: its size, what can be made again in it, how long since it was used, and what can be done.
@Serializable
data class FootprintChat (
	val key: String,
	/// The chat to open, by its id in the list.
	val chat: String? = null,
	val title: String,
	val archived: Boolean,
	val text: String,
	val note: String,
	val choices: List<FootprintChoice>
)

@Serializable
data class FootprintLegend (
	val text: String,
	/// Its dot's colour (as FootprintSegment's), or none for words alone.
	val tone: String,
	val level: Level
)

/// A part of the data directory (or a place beside it): `chats` opens the list of chats.
@Serializable
data class FootprintPart (
	val id: String,
	val label: String,
	val note: String,
	val text: String,
	val tone: String,
	val opens: Boolean
)

/// A line of the memory part: the station, the agents together, or one agent's process (`key`: its chat's session).
@Serializable
data class FootprintRow (
	val label: String,
	val text: String,
	val note: String? = null,
	/// Under the line before it (an agent's process under the agents).
	val nested: Boolean,
	val chat: String? = null,
	val choice: FootprintChoice? = null
)

/// A piece of the disk's bar: `tone` is the part's colour (chart-1…6), `rest` (used by others) or `free`.
@Serializable
data class FootprintSegment (
	val id: String,
	val percent: Double,
	val tone: String
)

/// How much of the machine a station takes, as its footprint page shows it: everything in words, with what can be cleaned
/// and how (each clean a choice: the call, the chats it is for and the questions asked before it, in order).
@Serializable
data class FootprintView (
	/// Measured at least once: before, the page says it is being measured.
	val measured: Boolean,
	val scanning: Boolean,
	/// The viewer may clean up (an owner or admin).
	val manage: Boolean,
	/// 3 分钟前统计, 正在统计….
	val checkedText: String,
	/// still.fail 在这台机器上占用.
	val lead: String,
	val totalText: String,
	/// The disk in one bar: the station's parts, the rest that is used, and what is free (percent of the disk).
	val bar: List<FootprintSegment>,
	val legend: List<FootprintLegend>,
	val parts: List<FootprintPart>,
	/// Beside the data directory: shown, not counted or cleaned.
	val elsewhere: List<FootprintPart>,
	val elsewhereNote: String,
	/// What can be cleaned up (only for those who may).
	val actions: List<FootprintAction>,
	/// Why there is nothing to clean, or why the viewer cannot.
	val actionsNote: String? = null,
	val chats: List<FootprintChat>,
	/// 213 个 chat · 8.6 GB.
	val chatsText: String,
	/// Chats of others the viewer cannot see, counted.
	val unseenText: String? = null,
	/// 内存 · 共 6 GB，已用 5.2 GB.
	val memoryTitle: String,
	val memory: List<FootprintRow>
)

/// One-click model and depth for a new chat; ranked and labelled by the core.
@Serializable
data class FrequentCombo (
	val model: String,
	val runtime: RuntimeKind,
	val effort: String? = null,
	val label: String,
	val selected: Boolean
)

@Serializable
data class HistoryFrom (
	val name: String,
	val slackUser: String? = null,
	val bound: Boolean
)

@Serializable
data class HistoryThought (
	val text: String,
	val first: String
)

@Serializable
data class HistoryStep (
	val said: String? = null,
	val name: String,
	val hint: String,
	val meta: String,
	val failed: Boolean,
	val call: String,
	val result: String? = null
)

/// Tool calls and thinking between two boundaries: named by its latest call, what it did by kind (`title`), how many
/// failed and are running.
@Serializable
data class HistoryGroup (
	val summary: String,
	val title: String,
	val failures: Long,
	val pending: Long,
	val thinking: List<HistoryThought>,
	val steps: List<HistoryStep>
)

/// What an item of the history is.
@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator("kind")
@Serializable
sealed class HistoryBody {
	@Serializable
	@SerialName("received")
	data class Received(val content: HistoryReceived): HistoryBody()
	@Serializable
	@SerialName("text")
	data class Text(val content: HistoryText): HistoryBody()
	@Serializable
	@SerialName("post")
	data class Post(val content: HistoryPost): HistoryBody()
	@Serializable
	@SerialName("mark")
	data class Mark(val content: HistoryMark): HistoryBody()
	@Serializable
	@SerialName("group")
	data class Group(val content: HistoryGroup): HistoryBody()
}

/// One item of an execution history, and the transcript entries it draws (`entries`: first, last).
@Serializable
data class HistoryItem (
	val key: String,
	val entries: List<Long>,
	val body: HistoryBody
)

@Serializable
data class HistoryLive (
	val id: String,
	val text: String
)

/// A wait in an agent's history: from its mark (`since`) until the next word brought it back (`until`, absent while it
/// still waits: count on from `since`), at most `seconds`.
@Serializable
data class HistoryWait (
	val since: Long,
	val until: Long? = null,
	val seconds: Long? = null
)

/// A state the agent marked, in words; `wait` when it went to wait on work it started (drawn with an hourglass).
@Serializable
data class HistoryMark (
	val text: String,
	val wait: HistoryWait? = null
)

/// A place a message came from or went to: a chat on ember's page (`session`: the agent it opens), or a Slack thread.
@Serializable
data class Place (
	/// An ember chat's title, or a Slack thread's workspace and channel (`Cue#ops`).
	val name: String,
	/// ember | slack
	val surface: String,
	val session: String? = null,
	/// A Slack thread's link in Slack, while a connect is signed in to its workspace.
	val url: String? = null
)

@Serializable
data class HistoryMessage (
	val key: String,
	val from: HistoryFrom,
	val text: String,
	val place: Place? = null
)

@Serializable
data class HistoryPhase (
	val phase: String,
	val text: String,
	val since: Long
)

/// A message the agent posted: where to, whether it ended its work blocked, whether it failed.
@Serializable
data class HistoryPost (
	val text: String,
	val place: Place? = null,
	val block: Boolean,
	val failed: Boolean
)

/// What a prompt carried: ember's own words around them (`note`), then the messages.
@Serializable
data class HistoryReceived (
	val note: String? = null,
	val messages: List<HistoryMessage>
)

/// The agent's own words; `subagent`: a sub-agent's.
@Serializable
data class HistoryText (
	val text: String,
	val subagent: Boolean
)

@Serializable
data class UsageLine (
	val label: String,
	val value: String
)

/// An agent's execution history, read for people (history.rs).
@Serializable
data class HistoryView (
	val items: List<HistoryItem>,
	val live: List<HistoryLive>,
	val phase: HistoryPhase? = null,
	val usage: List<UsageLine>? = null,
	val usageLine: String? = null,
	/// What shows at its top: where the session begins, or why there is nothing (yet).
	val edge: String,
	val empty: Boolean,
	val loaded: Boolean,
	/// Older entries exist: `history.older` loads the page before them.
	val more: Boolean? = null
)

@Serializable
data class Memory (
	val totalBytes: Long,
	val usedBytes: Long,
	val swapUsedBytes: Long? = null
)

/// CPU, memory or disk: how full (and how bad: ok | amber | red), in words.
@Serializable
data class Meter (
	val label: String,
	val short: String,
	val percent: Long,
	val level: Level,
	val value: String,
	/// Remaining capacity for an alert chip; absent for CPU and older cores.
	val remaining: String? = null,
	val note: String? = null
)

/// The machine a station runs on, with it in words.
@Serializable
data class Host (
	val hostname: String,
	val os: String,
	val arch: String,
	val cpus: Long,
	val cpuModel: String,
	/// 1-minute load average divided by CPU count, 0–1+.
	val load: Double,
	/// How busy the CPUs are, all together, 0–1 (stations before it: absent).
	val cpuBusy: Double? = null,
	val uptimeSec: Double,
	val memory: Memory,
	val disk: Disk,
	val emberRssBytes: Long,
	val checkedAt: Long,
	val summary: String,
	val line: String,
	val facts: List<String>,
	val meters: List<Meter>,
	val emberText: String
)

/// A job's output as it grows (the `jobLog` topic): its last lines, when it last grew, its state (absent from a
/// station yet to say), and, put in by the core, its last line and when in words (absent: nothing to say).
@Serializable
data class JobLogView (
	val text: String,
	val outputAt: Long? = null,
	val state: String? = null,
	val last: String? = null,
	val said: String? = null
)

/// A chat's history tabs as last left: which are open, which is in front.
@Serializable
data class KeptTabs (
	val tabs: List<String>,
	val active: String? = null
)

/// What one of still.fail's links opens in the app (`link.parse`): `invite` (`token`), a chat's page (`chat`), or an
/// item (`item`: its `session`, and `service` its web service); the call answers null for any other link.
@Serializable
data class LinkTarget (
	val opens: String,
	val token: String? = null,
	val workspace: String? = null,
	val station: String? = null,
	val chat: String? = null,
	val session: String? = null,
	val service: String? = null
)

@Serializable
data class TimelineEntry (
	val at: String? = null,
	/// user | assistant | thinking | tool_call | tool_result
	val kind: String,
	val text: String,
	val tool: String? = null,
	val ok: Boolean? = null,
	val callId: String? = null,
	val subagent: Boolean? = null
)

@Serializable
data class TranscriptUsage (
	val modelCalls: Long,
	val inputTokens: Long,
	val cachedTokens: Long,
	val outputTokens: Long,
	val model: String? = null
)

/// A step in flight; an ended one stays until the transcript entry that records it arrives.
@Serializable
data class LiveStep (
	val id: String,
	/// text | thinking | tool
	val step: String,
	val tool: String? = null,
	val subagent: Boolean? = null,
	val parent: String? = null,
	val input: String,
	val startedAt: Long,
	val ended: Boolean? = null
)

/// Where the turn stands with the model (starting | requesting | responding | working), since when.
@Serializable
data class Phase (
	val phase: String,
	val since: Long
)

/// A session as it runs: its transcript (its latest entries once `loaded`, from entry `first`; `history.older` loads
/// those before), the model's use, the steps in flight, where the turn stands, how fast it writes, and its activity.
@Serializable
data class Live (
	val loaded: Boolean,
	val first: Long? = null,
	val timeline: List<TimelineEntry>,
	val usage: TranscriptUsage? = null,
	val steps: List<LiveStep>,
	val phase: Phase? = null,
	val rate: Long? = null,
	val activity: Activity? = null,
	/// Its station is offline: this is what was kept.
	val offline: Boolean? = null
)

@Serializable
data class LongJobsGroup (
	/// services | jobs
	val key: String,
	/// 开了很久的网页服务 · 3
	val head: String,
	val jobs: List<Job>
)

/// The services and jobs left up a long while (an hour) on a scope's stations that are up (the `longJobs` view),
/// oldest first, in groups: web services, then background jobs; none while empty.
@Serializable
data class LongJobsView (
	val groups: List<LongJobsGroup>
)

/// Who the station machine's own Claude Code or Codex is signed in as (only read: ember never takes the login over).
@Serializable
data class MachineLogin (
	val runtime: RuntimeKind,
	val installed: Boolean,
	val loggedIn: Boolean,
	val email: String? = null,
	val plan: String? = null,
	/// A profile can use it as it is (kept in a file, not only in the keychain).
	val usable: Boolean? = null,
	/// Its allowance, as a profile on it would show (none until read, or when it cannot be).
	val quota: Quota? = null,
	/// In a line, as the pages show it.
	val text: String,
	/// Offered for a profile: signed in, on a plan, and no profile on it yet.
	val offered: Boolean? = null
)

@Serializable
data class MemoryFile (
	val path: String,
	val text: String
)

@Serializable
data class MeshStatus (
	/// off | missing | running | restarting
	val state: String,
	val origin: String? = null,
	val station: String? = null,
	val workspace: String? = null,
	val workspaceId: String? = null,
	val name: String? = null
)

/// A figure in words, and how bad it is.
@Serializable
data class NetFigure (
	val text: String,
	val level: Level
)

/// The way through one relay: its round trip, or none if it was not reached in time.
@Serializable
data class NetRelay (
	/// What still.fail calls it (北京), or its host.
	val name: String,
	val rtt: NetFigure? = null,
	/// The connection goes through it now.
	val current: Boolean
)

/// A station's ways through each relay as last measured, and whether they are being measured again.
@Serializable
data class NetMeasured (
	val measuring: Boolean,
	val relays: List<NetRelay>,
	/// The relay the connection moved to as they were measured (its name), if it did.
	val moved: String? = null
)

@Serializable
data class RuntimeModels (
	val runtime: RuntimeKind,
	val models: List<String>
)

/// Who is looking: local | access (`email`) | mesh (`email`, `name`, `sub`, `role`, `workspace`, `device`).
@Serializable
data class Viewer (
	val via: String,
	val email: String? = null,
	val name: String? = null,
	val sub: String? = null,
	val role: String? = null,
	val workspace: String? = null,
	val device: String? = null
)

@Serializable
data class PendingLogin (
	val id: String,
	val runtime: RuntimeKind,
	val job: LoginJob? = null,
	val created: String? = null,
	/// Why a sign-in that succeeded made no profile.
	val error: String? = null
)

/// A piece of software on a station and whether a newer one is out (updates.rs): the station itself (`station`) or a
/// runtime (`claude`, `codex`).
@Serializable
data class SoftwareVersion (
	/// station | claude | codex
	val id: String,
	val name: String,
	/// On the machine (a runtime may not be: then `updatable` says it can be installed from here).
	val installed: Boolean,
	/// What runs now; none when it is not installed, or not a release (a clone).
	val version: String? = null,
	/// The latest out, when it could be read.
	val latest: String? = null,
	/// The latest is newer than what runs.
	val newer: Boolean,
	/// The station's, switched back from the test channel: the latest is the stable release, older than the beta that
	/// runs, and going back to it is offered (回到正式版). False from a station older than channels.
	val downgrade: Boolean? = null,
	/// The station's: which releases it is updated to, `stable` or `beta`; none where it cannot be updated from here,
	/// and from a station older than channels.
	val channel: String? = null,
	/// The station's: whether it updates itself when a newer release of its channel is out (自动更新); none where it
	/// cannot be updated from here, and from a station older than it.
	val auto: Boolean? = null,
	/// The pages can update it (or install it, when it is not installed).
	val updatable: Boolean,
	/// Why it cannot be updated from here (the desktop app's station, a runtime installed another way…).
	val note: String? = null,
	/// idle | updating | failed
	val state: String,
	/// The station's, while it is updating: where the update is, in a line (正在下载新版本…). None from a station
	/// older than it, or an installer that does not say.
	val progress: String? = null,
	/// A runtime's, while what its install or update downloads comes in: how much of it is, 0–100 (drawn as a bar
	/// beside `progress`). None when that is not known, and from a station older than it.
	val percent: Long? = null,
	/// The station's, for a while after an update ended well: how it went (已更新到 0.1.1300，agent 没有中断).
	val done: String? = null,
	/// What the last update that failed said.
	val message: String? = null,
	/// When what is out was last read.
	val checkedAt: Long? = null
)

/// A station's overview, with what the clients show of its connects and profiles.
@Serializable
data class Overview (
	val viewer: Viewer,
	val connects: List<Connect>,
	val profiles: List<Profile>,
	val processes: List<AgentProcess>,
	val counts: Counts,
	val mesh: MeshStatus? = null,
	val slackUsers: List<String>,
	val slackTeams: List<SlackTeam>,
	val slackApps: List<MadeSlackApp>? = null,
	val disk: DiskRoom? = null,
	val logins: List<PendingLogin>,
	/// This machine's own logins (none from a station older than them).
	val machineLogins: List<MachineLogin>? = null,
	/// The station's and its runtimes' versions, and whether newer ones are out (none from a station older than them).
	val updates: List<SoftwareVersion>? = null,
	/// Its agents' processes, in a line.
	val processesText: String,
	/// How much of the disk it takes (none from a station older than the footprint page, which then is not offered).
	val footprint: FootprintBrief? = null
)

/// This device's connection to a station, in words (its card's network line): how it goes, its round trip now and
/// over the last minute, and what goes over it.
@Serializable
data class StationNet (
	/// 直连, 北京中继 (the relay's name, or 中继 host), or 正在选路.
	val path: String,
	val rtt: NetFigure? = null,
	/// Round trips over the last minute, oldest first, in milliseconds.
	val rttHistory: List<Double>,
	/// Bytes a second now, each way: 1.4 MB/s.
	val down: String,
	val up: String,
	/// What went over it today on this device: 今天共 ↓ 212 MB · ↑ 9.6 MB (a core from before: 本次共, since it opened).
	val total: String,
	/// The same each way: 212 MB. Missing from a core from before.
	val downTotal: String? = null,
	val upTotal: String? = null,
	/// Packets lost over the last minute, when some were.
	val loss: NetFigure? = null,
	/// The way through each relay as last measured, once it was (natively and in the browser: the mesh). Missing from
	/// a core from before.
	val measured: NetMeasured? = null
)

@Serializable
data class StationView (
	val station: String,
	val id: String,
	val name: String,
	/// Its line in a list: offline since when, or what it is and whether its agents work.
	val summary: String,
	/// Its buddy's face: offline | working | idle; and what it is under its name (its processor, else 在线/离线).
	val face: String? = null,
	val line: String? = null,
	val online: Boolean,
	/// Seconds, from still.fail cloud.
	val lastSeen: Long? = null,
	val version: String? = null,
	val link: Link,
	val runtimes: List<RuntimeModels>,
	val models: List<ModelOption>,
	val overview: Overview? = null,
	/// Its versions offer the 测试版 switch: it can be put on a channel (its station's version says one), and the
	/// account that reaches it is in the beta or it is on the test channel already (to be switched back).
	val betaOffered: Boolean? = null,
	val host: Host? = null,
	/// How this device's connection to it runs; none for a station reached without one of its own (the page's own)
	/// or before one is open.
	val net: StationNet? = null,
	/// Its times in words, by field (`createdAt`, `lastActiveAt`, …).
	val time: Map<String, Stamp>? = null
)

/// A new chat's page (the `newChat` topic): the stations it can start on, the one it starts on, and what it runs
/// there, as last picked on this device (`newChat.pick`); what the station no longer has gives way to the first it has.
@Serializable
data class NewChatView (
	/// The station last started on (or picked) in the scope, its id: the page holds its place with it until the
	/// stations are known.
	val kept: String,
	/// The scope's stations up now; none until its workspace has been read (`error`: why it could not be).
	val stations: List<StationView>? = null,
	val error: String? = null,
	/// Whether the scope has any station, up or not.
	val any: Boolean,
	/// The one it starts on: the one kept, else the first up; none when none is up.
	val station: StationView? = null,
	val model: ModelOption? = null,
	val runtime: RuntimeKind? = null,
	val effort: String? = null,
	val fast: Boolean? = null,
	/// The account kept to, while it still runs the model there; none: the station's pick.
	val profile: String? = null,
	/// How hard it can think there, and who can run it (offered when more than one can: `pickAccount`).
	val efforts: List<String>,
	val accounts: List<RunnableProfile>,
	val pickAccount: Boolean,
	/// Its profiles are being read.
	val waiting: Boolean,
	/// What keeps a chat from starting: `profile` (none added) or `models` (none enabled).
	val blocked: String? = null,
	/// In a line under the page's words: the profiles being read, or no model enabled.
	val problem: String? = null,
	/// Every account of the model has used up its allowance: what is sent waits for it.
	val spent: String? = null,
	/// Its model control (the `pick` topic of `new` on the station), with the page.
	val pick: PickView? = null,
	/// Up to four combinations used on this device in this workspace, filtered to this station.
	val frequent: List<FrequentCombo>? = null
)

/// A chat that wants its person: its agent is blocked on them (`block`), failed (`failed`), finished with something
/// new to read (`done`), or someone else said something (`message`). `tag` names the chat (one notification each),
/// `url` opens it.
@Serializable
data class Notice (
	val id: String,
	val kind: String,
	val station: String,
	val workspace: String,
	val stationId: String,
	val session: String,
	val thread: Long? = null,
	val title: String,
	val body: String,
	val tag: String,
	val url: String,
	val at: Long
)

/// What a person hears about while the client runs (the `notices` topic; docs/notifications.md), oldest first.
@Serializable
data class NoticesView (
	val items: List<Notice>
)

/// Notifications on this device (the `notify` topic; `notify.set`, `notice.claim`): whether they are on, whether the
/// system was asked to allow them, whether the device should hold a push registration, and the notices a page is to
/// show now, each taken by one page (`notice.claim`).
@Serializable
data class NotifyView (
	val on: Boolean,
	val asked: Boolean,
	val push: Boolean,
	val show: List<Notice>
)

/// A chat to go back to: its station's address and the key its page goes by.
@Serializable
data class OpenChat (
	val station: String,
	val key: String
)

/// How the pages look: as the system does (the default), or always light, or always dark.
typealias Appearance = String

/// Whose pictures lead a chat's row: by how many people the scope has (the default), or always the agents', or the
/// people's.
typealias RowPictureSetting = String

/// What this device keeps of how its person likes it (the `prefs` topic, `prefs.set`), and what it is.
@Serializable
data class PrefsView (
	/// The lists show only the chats and connects the viewer takes part in.
	val onlyMine: Boolean? = null,
	/// The chat list shows only the watching chats (监控中); never with `only_mine`.
	val onlyWatching: Boolean? = null,
	val appearance: Appearance? = null,
	val rowPicture: RowPictureSetting? = null,
	/// Times are shown as dates rather than "3 分钟前".
	val absoluteTime: Boolean? = null,
	/// Keys changed for an action (the desktop app's), by action.
	val keys: Map<String, List<String>>? = null,
	/// The workspace last open (the Android app's).
	val workspace: String? = null,
	/// The chat page last open, by scope (a workspace; `local` in what a station's own page kept, before it went).
	val lastChat: Map<String, String>? = null,
	/// The chat last open, by workspace, as the core keeps it from `client.focus` (a settings page leaves it as it
	/// was): what the workspace's page goes back to.
	val openChat: Map<String, OpenChat>? = null,
	/// Each chat's history tabs, by `<station>:<chat>` (the latest 200).
	val chatTabs: Map<String, KeptTabs>? = null,
	/// A Slack app made for a new connect, to go on with, by station (the Android app's).
	val resume: Map<String, String>? = null,
	/// The invite code a page was opened with, kept through signing in until a workspace is made with it.
	val invite: String? = null,
	val device: DeviceView? = null
)

/// A session with its threads and turns (`session` topic).
@Serializable
data class SessionDetail (
	val session: Session,
	val threads: List<ChatThread>,
	val turns: List<TurnRecord>
)

/// A skill: `body` its text as people read it (no frontmatter), `about` when it applies (a project's without its
/// 项目记忆：); both absent from a core before them.
@Serializable
data class SkillFile (
	val name: String,
	val description: String,
	val project: Boolean,
	val builtin: Boolean,
	val text: String,
	val body: String? = null,
	val about: String? = null
)

/// Address of a transient Slack token form, shared by calls and topic subscriptions.
@Serializable
data class SlackTokenForm (
	val station: String,
	val form: String
)

/// A Slack token form: a transient core draft, never saved to device storage.
@Serializable
data class SlackTokensView (
	val appToken: String,
	val botToken: String,
	val verified: SlackIdentity? = null,
	val errors: List<String>,
	val ready: Boolean
)

/// The agents' memory on a station (`memory.get`): the global one, and the skills (projects' memories among them).
@Serializable
data class StationMemory (
	val global: MemoryFile,
	val skills: List<SkillFile>
)

/// What the core is waiting on (the `status` topic), when it is worth saying: `state` slow (something has taken a
/// while) | trouble (a connection down), absent while all goes as it should; `text` says it in one line.
@Serializable
data class StatusView (
	val state: String? = null,
	val text: String? = null,
	val items: List<StatusItem>
)

/// Where a chat in the usage lists opens: its station, and its thread, or its agent's session.
@Serializable
data class UsageChat (
	val station: String,
	val thread: Long? = null,
	val session: String? = null
)

/// A day (`day` 2026-10-01, `label` 10/1): what it cost, split as `series` (`parts`, in dollars, and in words), and its
/// calls.
@Serializable
data class UsageDay (
	val day: String,
	val label: String,
	val today: Boolean,
	val cost: Double,
	val costText: String,
	val calls: Double,
	val callsText: String,
	val parts: List<Double>,
	val partsText: List<String>
)

/// A person, chat, account or model, and what it spent: `share` of the total cost (of the calls, when nothing was
/// priced), `detail` its calls and tokens in a line. A person's `person` (with `shown`); a chat's page (`chat`), when
/// it is still there.
@Serializable
data class UsageItem (
	val key: String,
	val title: String,
	val sub: String? = null,
	val cost: Double,
	val costText: String,
	val share: Double,
	val shareText: String,
	val calls: Double,
	val detail: String,
	val person: Creator? = null,
	val chat: UsageChat? = null
)

/// 按人 / 按对话 / 按账号 / 按模型 (`key` people, chats, profiles, models), the most spent first.
@Serializable
data class UsageList (
	val key: String,
	val title: String,
	val items: List<UsageItem>
)

@Serializable
data class UsageRate (
	val label: String,
	val value: String
)

@Serializable
data class UsagePriceRow (
	val model: String,
	val rates: List<UsageRate>
)

/// A station's own price table; its note explains missing data on older/offline stations.
@Serializable
data class UsagePriceTable (
	val station: String,
	val note: String,
	val rows: List<UsagePriceRow>
)

/// A part of each day's bar: a person (`key` their email or reference), or the rest (`key` empty).
@Serializable
data class UsageSeries (
	val key: String,
	val name: String
)

/// 折合费用 $1,911 (按 API 价算).
@Serializable
data class UsageTile (
	val label: String,
	val value: String,
	val sub: String
)

/// What the agents of a workspace spent over its last `days` (the `usage` view, client/core/src/views/usage.rs): a few
/// totals (`tiles`), each day's cost split by the people who spent most (`series`, the rest as 其他), and lists of who,
/// which chats, which accounts and which models spent the most, at the providers' API prices (`basis` says what that
/// means). `notes`: what is missing or still being read, in lines; `loading` while a station has not answered.
@Serializable
data class UsageView (
	val days: UInt,
	val loading: Boolean,
	val empty: Boolean,
	val tiles: List<UsageTile>,
	val series: List<UsageSeries>,
	val daily: List<UsageDay>,
	/// The most a day cost (what the bars are drawn against).
	val max: Double,
	val lists: List<UsageList>,
	val notes: List<String>,
	val basis: String,
	/// Each station's own calculation table; absent with older cores.
	val prices: List<UsagePriceTable>? = null
)

/// A workspace's mark: of the chats its person takes part in, how many want them (blocked or failed) and how many
/// have something unread; of all its chats, how many have a decision waiting (`wait`); its `tone` (alert | wait | done, as a
/// chat's mark) and in words, none when it is 0 and 0; the chat last
/// open in it.
@Serializable
data class WorkspaceMark (
	val alert: UInt,
	val unread: UInt,
	/// How many have a card waiting (not dismissed by them) or an agent needing them (need_help), not counted in
	/// `alert`. Absent for 0.
	val wait: UInt? = null,
	/// How many cards wait in it for them in all (奏 N). Absent for 0.
	val decisions: UInt? = null,
	val tone: String? = null,
	/// 2 个需要处理 · 1 个在等你 · 3 个有新消息
	val label: String? = null,
	val chat: OpenChat? = null
)

/// What each workspace has waiting for its person, for where workspaces are switched (the `workspaceMarks` view):
/// by workspace id; and of those other than the one in view, the most urgent.
@Serializable
data class WorkspaceMarksView (
	val workspaces: Map<String, WorkspaceMark>,
	/// alert | wait | done: the others' mark; none when nothing there wants anyone.
	val others: String? = null,
	/// 其他 workspace：1 个需要处理 · 2 个有新消息
	val othersLabel: String? = null
)

