#!/usr/bin/env python3
"""still.fail's own icons (design/icons, drawn for still.fail by astra) for both clients: web/src/icons.tsx (React components)
and the Android app's ui/Icons.kt (ImageVectors). With them the icons a station can have (design/station-icons, in the order
of its manifest.json, each with the emoji kept beside it for older clients). The SVGs are the one source; `python3 scripts/icons.py --check`
fails when the generated files are not what they make."""
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design/icons"
STATION = ROOT / "design/station-icons"
WEB = ROOT / "web/src/icons.tsx"
ANDROID = ROOT / "apps/android/app/src/main/kotlin/fail/still/android/ui/Icons.kt"
NS = "{http://www.w3.org/2000/svg}"


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("-"))


def num(v: str) -> float:
    return float(v)


def fmt(v: float) -> str:
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def shapes(path: Path):
    """An icon's elements: (tag, attributes, filled)."""
    root = ET.parse(path).getroot()
    out = []
    for el in root.iter():
        tag = el.tag.replace(NS, "")
        if tag == "svg":
            continue
        if tag not in ("path", "circle", "rect"):
            raise SystemExit(f"{path.name}: <{tag}> is not drawn here")
        filled = el.get("fill") == "currentColor"
        out.append((tag, dict(el.attrib), filled))
    return out


def as_path(tag: str, a: dict) -> str:
    """An element as path data, for Android."""
    if tag == "path":
        return a["d"]
    if tag == "circle":
        cx, cy, r = num(a["cx"]), num(a["cy"]), num(a["r"])
        return f"M{fmt(cx - r)} {fmt(cy)}a{fmt(r)} {fmt(r)} 0 1 0 {fmt(2 * r)} 0a{fmt(r)} {fmt(r)} 0 1 0 {fmt(-2 * r)} 0Z"
    x, y, w, h = num(a.get("x", "0")), num(a.get("y", "0")), num(a["width"]), num(a["height"])
    r = min(num(a.get("rx", a.get("ry", "0"))), w / 2, h / 2)
    if not r:
        return f"M{fmt(x)} {fmt(y)}h{fmt(w)}v{fmt(h)}h{fmt(-w)}Z"
    return (f"M{fmt(x + r)} {fmt(y)}h{fmt(w - 2 * r)}a{fmt(r)} {fmt(r)} 0 0 1 {fmt(r)} {fmt(r)}v{fmt(h - 2 * r)}"
            f"a{fmt(r)} {fmt(r)} 0 0 1 {fmt(-r)} {fmt(r)}h{fmt(-(w - 2 * r))}a{fmt(r)} {fmt(r)} 0 0 1 {fmt(-r)} {fmt(-r)}"
            f"v{fmt(-(h - 2 * r))}a{fmt(r)} {fmt(r)} 0 0 1 {fmt(r)} {fmt(-r)}Z")


def jsx(tag: str, a: dict, filled: bool) -> str:
    keep = {k: v for k, v in a.items() if k in ("d", "cx", "cy", "r", "x", "y", "width", "height", "rx", "ry")}
    attrs = " ".join(f'{k}="{v}"' for k, v in keep.items())
    if filled:
        attrs += ' fill="currentColor" stroke="none"'
    return f"<{tag} {attrs} />"


def station_icons():
    """The icons a station can have, in the picker's order: (name, emoji, elements)."""
    return [(m["name"], m["emoji"], shapes(STATION / f"{m['name']}.svg")) for m in json.loads((STATION / "manifest.json").read_text())]


def web(icons, stations) -> str:
    lines = [
        "// Generated by scripts/icons.py from design/icons (still.fail's own icons, drawn for it by astra): do not edit.",
        "import type { SVGProps } from \"react\";",
        "",
        "/** An icon's props: its size (px), its line's weight, and whatever an <svg> takes. */",
        "export type IconProps = Omit<SVGProps<SVGSVGElement>, \"ref\"> & { size?: number | string; strokeWidth?: number | string };",
        "",
        "export function Svg({ size = 24, strokeWidth = 1.75, children, ...rest }: IconProps & { children: React.ReactNode }) {",
        "  return (",
        "    <svg xmlns=\"http://www.w3.org/2000/svg\" width={size} height={size} viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"",
        "      strokeWidth={strokeWidth} strokeLinecap=\"round\" strokeLinejoin=\"round\" aria-hidden=\"true\" {...rest}>",
        "      {children}",
        "    </svg>",
        "  );",
        "}",
        "",
    ]
    for name, els in icons:
        body = "".join(jsx(*e) for e in els)
        lines.append(f"export function {pascal(name)}(props: IconProps) {{")
        lines.append(f"  return <Svg {{...props}}>{body}</Svg>;")
        lines.append("}")
        lines.append("")
    lines.append("/** Every icon by its name in design/icons, as the core names them (activity rows). */")
    lines.append("export const ICONS: Record<string, (props: IconProps) => React.JSX.Element> = {")
    for name, _ in icons:
        lines.append(f"  \"{name}\": {pascal(name)},")
    lines.append("};")
    lines.append("")
    for name, _, els in stations:
        body = "".join(jsx(*e) for e in els)
        lines.append(f"function Station{pascal(name)}(props: IconProps) {{")
        lines.append(f"  return <Svg {{...props}}>{body}</Svg>;")
        lines.append("}")
        lines.append("")
    lines.append("/** The icons a station can have (design/station-icons), in the picker's order, each with the emoji kept beside it for older clients. */")
    lines.append("export const STATION_ICONS: readonly { emoji: string; name: string; Icon: (props: IconProps) => React.JSX.Element }[] = [")
    for name, emoji, _ in stations:
        lines.append(f"  {{ emoji: \"{emoji}\", name: \"{name}\", Icon: Station{pascal(name)} }},")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def android(icons, stations) -> str:
    lines = [
        "// Generated by scripts/icons.py from design/icons (still.fail's own icons, drawn for it by astra): do not edit.",
        "// Drawn in the colour of what they sit in (tinted), at the set's 1.75 line.",
        "package fail.still.android.ui",
        "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.graphics.SolidColor",
        "import androidx.compose.ui.graphics.StrokeCap",
        "import androidx.compose.ui.graphics.StrokeJoin",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import androidx.compose.ui.graphics.vector.addPathNodes",
        "import androidx.compose.ui.unit.dp",
        "",
        "/** One icon: its line paths, and its solid dots. */",
        "private fun icon(name: String, lines: List<String>, dots: List<String>) = ImageVector.Builder(name, 24.dp, 24.dp, 24f, 24f).apply {",
        "    for (d in lines) addPath(addPathNodes(d), fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 1.75f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round)",
        "    for (d in dots) addPath(addPathNodes(d), fill = SolidColor(Color.Black))",
        "}.build()",
        "",
        "object Icons {",
    ]
    for name, els in icons:
        stroked = [as_path(t, a) for t, a, f in els if not f]
        dots = [as_path(t, a) for t, a, f in els if f]
        q = lambda xs: ", ".join('"' + x.replace('"', '\\"') + '"' for x in xs)
        lines.append(f"    val {pascal(name)} = icon(\"{name}\", listOf({q(stroked)}), listOf({q(dots)}))")
    lines.append("")
    lines.append("    /** Every icon by its name in design/icons, as the core names them (activity rows). */")
    lines.append("    val byName = mapOf(" + ", ".join(f"\"{n}\" to {pascal(n)}" for n, _ in icons) + ")")
    lines.append("}")
    lines.append("")
    lines.append("/** One of the icons a station can have: its name (kept as glyph:<name>), the emoji kept beside it for older clients, and it drawn. */")
    lines.append("data class StationGlyph(val name: String, val emoji: String, val icon: ImageVector)")
    lines.append("")
    lines.append("/** The icons a station can have (design/station-icons), in the picker's order. */")
    lines.append("object StationIcons {")
    lines.append("    val all: List<StationGlyph> = listOf(")
    for name, emoji, els in stations:
        stroked = [as_path(t, a) for t, a, f in els if not f]
        dots = [as_path(t, a) for t, a, f in els if f]
        q = lambda xs: ", ".join('"' + x.replace('"', '\\"') + '"' for x in xs)
        lines.append(f"        StationGlyph(\"{name}\", \"{emoji}\", icon(\"{name}\", listOf({q(stroked)}), listOf({q(dots)}))),")
    lines.append("    )")
    lines.append("")
    lines.append("    private val byName = all.associateBy { it.name }")
    lines.append("")
    lines.append("    /** The one a station's icon names (glyph:<name>); null for a picture, none, or one this build does not know. */")
    lines.append("    fun of(icon: String?): StationGlyph? = icon?.takeIf { it.startsWith(\"glyph:\") }?.let { byName[it.removePrefix(\"glyph:\")] }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    icons = [(p.stem, shapes(p)) for p in sorted(SOURCE.glob("*.svg"))]
    stations = station_icons()
    out = {WEB: web(icons, stations), ANDROID: android(icons, stations)}
    if "--check" in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, text in out.items() if not p.exists() or p.read_text() != text]
        if stale:
            raise SystemExit("icons are not what design/icons makes: run python3 scripts/icons.py (" + ", ".join(stale) + ")")
        return
    for p, text in out.items():
        p.write_text(text)


if __name__ == "__main__":
    main()
