#!/usr/bin/env python3
"""Generate UI operation bindings from contracts beside the core's routes.

The optional fields preserve omitted versus explicit null. Bodies left open by the
core (input/settings/state/access) remain JSON; identities and scalar fields are typed.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent


def contracts():
    src = (ROOT / 'client/core/src/ops.rs').read_text().split('#[cfg(test)]')[0]
    sections = src.split('fn cloud_op(', 1)
    result = []
    for scope, section in zip(('station', 'account'), sections):
        names = re.findall(r'^        "([\w.]+)" =>', section, re.M)
        rows = re.findall(r'^        // @params *(.*)\n        "([\w.]+)" =>', section, re.M)
        if names != [name for _, name in rows]:
            raise ValueError('Every operation needs a @params contract beside its route')
        for raw, name in rows:
            fields = []
            for word in raw.split():
                field, typ = word.split(':')
                fields.append((field.rstrip('?'), typ, not field.endswith('?')))
            # Contracts may refine raw JSON but must name exactly the inputs consumed by the route.
            arm = section.split('"' + name + '" =>', 1)[1]
            arm = re.split(r'^        (?:// @params|_ => return None)', arm, maxsplit=1, flags=re.M)[0]
            used = set(re.findall(r'p\.(?:str|at|word|u64|bool|value)\("(\w+)"\)', arm))
            used.update(re.findall(r'p\.0\.get\("(\w+)"\)', arm))
            for pick in re.findall(r'p\.pick\(&\[(.*?)\]\)', arm, re.S):
                used.update(re.findall(r'"(\w+)"', pick))
            if 'ws()' in arm: used.add('workspace')
            declared = {k for k,_,_ in fields}
            if used != declared:
                raise ValueError(f'{name}: @params differs from route inputs: {used ^ declared}')
            result.append((scope, name, fields))
    return result


def camel(name):
    a, b = name.split('.')
    return a + b[0].upper() + b[1:]


def generate():
    rows = contracts()
    routes = (ROOT / 'client/core/src/ops.rs').read_text().split('#[cfg(test)]')[0]
    untracked = []
    for _, name, _ in rows:
        arm = routes.split('"' + name + '" =>', 1)[1]
        arm = re.split(r'^        (?:// @params|_ => return None)', arm, maxsplit=1, flags=re.M)[0]
        if re.search(r'op\(\s*"GET"', arm): untracked.append(name)
    doing = (ROOT / 'client/core/src/doing.rs').read_text()
    excluded = re.search(r'Call::Op\(op\).*?!matches!\(name, ([^)]*)\)', doing)
    if not excluded: raise ValueError('Review operation feedback policy in doing.rs')
    untracked += re.findall(r'"([\w.]+)"', excluded[1])
    ts = ['// Generated by scripts/operations.py from client/core/src/ops.rs. Do not edit.',
          'export interface OperationParams {']
    types = dict(string='string', number='number', boolean='boolean', strings='string[]', json='unknown')
    for scope, name, fields in rows:
        fields_ts = '; '.join(f'{k}{"" if req else "?"}: {types[t]}{"" if req or t == "json" else " | null | undefined"}' for k,t,req in fields)
        ts.append(f'  "{name}": {{ {fields_ts} }};')
    ts += ['}', '', 'export const UNTRACKED_OPERATIONS = new Set(' + str(sorted(set(untracked))).replace("'", '"') + ');', '', 'type Call = (name: string, params: Record<string, unknown>) => Promise<unknown>;', '']
    for scope, cls in [('station','Station'),('account','Cloud')]:
        ts.append(f'export function bind{cls}Operations(call: Call) {{')
        ts.append('  return {')
        for sc,name,fields in rows:
            if sc != scope: continue
            default = '' if any(req for _,_,req in fields) else ' = {}'
            ts.append(f'    {camel(name)}: <T = unknown>(params: OperationParams["{name}"]{default}) => call("{name}", params) as Promise<T>,')
        ts += ['  };', '}', '']
    kt = ['// Generated by scripts/operations.py from client/core/src/ops.rs. Do not edit.',
          'package fail.still.android.data', '', 'import kotlinx.serialization.json.*',
          'import kotlin.properties.ReadWriteProperty', 'import kotlin.reflect.KProperty', '',
          '/** A field is absent until assigned; assigning null sends JSON null (reset to default). */',
          'val UNTRACKED_OPERATIONS = setOf(' + ', '.join('"' + n + '"' for n in sorted(set(untracked))) + ')', '',
          'open class OperationFields {',
          '    internal val fields = mutableMapOf<String, JsonElement>()',
          '    protected fun <T> field(name: String, encode: (T) -> JsonElement) = object : ReadWriteProperty<Any?, T?> {',
          '        private var value: T? = null',
          '        override fun getValue(thisRef: Any?, property: KProperty<*>): T? = value',
          '        override fun setValue(thisRef: Any?, property: KProperty<*>, value: T?) {',
          '            this.value = value; fields[name] = value?.let(encode) ?: JsonNull',
          '        }', '    }', '}', '']
    ktypes=dict(string='String',number='Long',boolean='Boolean',strings='List<String>',json='JsonElement')
    enc=dict(string='JsonPrimitive(it)',number='JsonPrimitive(it)',boolean='JsonPrimitive(it)',strings='JsonArray(it.map(::JsonPrimitive))',json='it')
    for scope,cls in [('station','Station'),('account','Cloud')]:
        kt.append(f'class {cls}Operations(private val call: suspend (String, JsonObject) -> JsonElement) {{')
        for sc,name,fields in rows:
            if sc!=scope:continue
            method=camel(name);klass=method[0].upper()+method[1:]+'Fields'
            required=[(k,t) for k,t,r in fields if r]; optional=[(k,t) for k,t,r in fields if not r]
            if optional:
                kt.append(f'    class {klass} : OperationFields() {{')
                for k,t in optional: kt.append(f'        var {k}: {ktypes[t]}? by field<{ktypes[t]}>("{k}") {{ {enc[t]} }}')
                kt.append('    }')
            params=[f'{k}: {ktypes[t]}' for k,t in required]
            if optional: params.append(f'fill: {klass}.() -> Unit = {{}}')
            kt.append(f'    suspend fun {method}({", ".join(params)}): JsonElement {{')
            kt.append(f'        val values = {klass}().apply(fill).fields' if optional else '        val values = mutableMapOf<String, JsonElement>()')
            for k,t in required:
                encoded = re.sub(r"\bit\b", k, enc[t])
                kt.append(f'        values["{k}"] = {encoded}')
            kt += [f'        return call("{name}", JsonObject(values))', '    }']
        kt += ['}', '']
    return {'web/src/core/operations.ts':'\n'.join(ts), 'apps/android/app/src/main/kotlin/fail/still/android/data/Operations.kt':'\n'.join(kt)}


if __name__ == '__main__':
    for path, text in generate().items():
        file = ROOT / path
        if '--check' in sys.argv:
            if not file.exists() or file.read_text() != text:
                sys.exit(f'{path} is stale; run python3 scripts/operations.py')
        else:
            file.write_text(text)
