#!/bin/sh
# The clients' types, generated from what the core declares it gives them (client/shapes): web/src/core/shapes.ts and
# the Android app's data/Shapes.kt. `sh scripts/shapes.sh --check` fails when they are not what the shapes make (the
# web's typecheck and the Android build run it).
set -eu
cd "$(dirname "$0")/.."
export PATH="$HOME/.cargo/bin:$PATH"
command -v typeshare >/dev/null || cargo install typeshare-cli --version 1.13.4 >/dev/null
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
typeshare client/shapes --lang=typescript --output-file="$tmp/shapes.ts" 2>"$tmp/log" || { cat "$tmp/log"; exit 1; }
typeshare client/shapes --lang=kotlin --java-package=fail.still.android.data --output-file="$tmp/Shapes.kt" 2>"$tmp/log" || { cat "$tmp/log"; exit 1; }
# Closed sets of words: a union of literals on the web; on Android the word itself (the core has checked it).
python3 - "$tmp/shapes.ts" "$tmp/Shapes.kt" <<'PY'
import re, sys
ts, kt = sys.argv[1], sys.argv[2]
s = open(ts).read()
def union(m):
    values = re.findall(r'= "([^"]*)"', m.group(2))
    return "export type %s = %s;" % (m.group(1), " | ".join('"%s"' % v for v in values))
s = re.sub(r'export enum (\w+) \{\n(.*?)\n\}', union, s, flags=re.S)
open(ts, "w").write(s)
k = open(kt).read()
k = re.sub(r'@Serializable\nenum class (\w+)\(val string: String\) \{\n.*?\n\}', r'typealias \1 = String', k, flags=re.S)
# A union says which it is in `kind` (serde's tag), not kotlinx's default `type`.
if "sealed class" in k:
    k = re.sub(r'@Serializable\nsealed class', '@OptIn(ExperimentalSerializationApi::class)\n@JsonClassDiscriminator("kind")\n@Serializable\nsealed class', k)
    k = k.replace("import kotlinx.serialization.SerialName\n", "import kotlinx.serialization.SerialName\nimport kotlinx.serialization.ExperimentalSerializationApi\nimport kotlinx.serialization.json.JsonClassDiscriminator\n", 1)
open(kt, "w").write(k)
PY
# Maps are plain Kotlin maps; the file says where it comes from.
sed -i.bak -e 's/HashMap</Map</g' -e 's|^ \* Generated by typeshare.*| * Generated by scripts/shapes.sh from client/shapes (typeshare): do not edit.|' "$tmp/Shapes.kt"
sed -i.bak -e 's|^ Generated by typeshare.*| Generated by scripts/shapes.sh from client/shapes (typeshare): do not edit.|' "$tmp/shapes.ts"
ts=web/src/core/shapes.ts
kt=apps/android/app/src/main/kotlin/fail/still/android/data/Shapes.kt
if [ "${1:-}" = "--check" ]; then
  cmp -s "$tmp/shapes.ts" "$ts" && cmp -s "$tmp/Shapes.kt" "$kt" || { echo "the clients' types are not what client/shapes makes: run sh scripts/shapes.sh" >&2; exit 1; }
else
  cp "$tmp/shapes.ts" "$ts"
  cp "$tmp/Shapes.kt" "$kt"
fi
