// Generated by scripts/icons.py from design/icons (ember's own icons, drawn for it by astra): do not edit.
// Drawn in the colour of what they sit in (tinted), at the set's 1.75 line.
package dev.ember.android.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

/** One icon: its line paths, and its solid dots. */
private fun icon(name: String, lines: List<String>, dots: List<String>) = ImageVector.Builder(name, 24.dp, 24.dp, 24f, 24f).apply {
    for (d in lines) addPath(addPathNodes(d), fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 1.75f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round)
    for (d in dots) addPath(addPathNodes(d), fill = SolidColor(Color.Black))
}.build()

object Icons {
    val Agent = icon("agent", listOf("M13 8H8Q4 8 4 12V17Q4 20.5 8 20.5H13Q17 20.5 17 17V14 M13 10L20 3.5 M15 3.5H20.5V9 M8 16H12"), listOf("M7 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z", "M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z"))
    val ArrowDown = icon("arrow-down", listOf("M12 4V20 M6 14L12 20L18 14"), listOf())
    val ArrowLeft = icon("arrow-left", listOf("M20 12H4 M10 6L4 12L10 18"), listOf())
    val ArrowRight = icon("arrow-right", listOf("M4 12H20 M14 6L20 12L14 18"), listOf())
    val ArrowUp = icon("arrow-up", listOf("M12 20V4 M6 10L12 4L18 10"), listOf())
    val Bot = icon("bot", listOf("M12 3.5V6 M12 6C18 6 20.5 8 20.5 12V16C20.5 19 17.5 20.5 12 20.5C6.5 20.5 3.5 19 3.5 16L4 12C4 8 6.5 6 12 6Z M9.5 17H14.5"), listOf("M7.25 12a1.25 1.25 0 1 0 2.5 0a1.25 1.25 0 1 0 -2.5 0Z", "M14.25 12a1.25 1.25 0 1 0 2.5 0a1.25 1.25 0 1 0 -2.5 0Z"))
    val Boxes = icon("boxes", listOf("M9 3.5H15Q17 3.5 17 5.5V8Q17 10 15 10H9Q7 10 7 8V5.5Q7 3.5 9 3.5Z M5 14H8Q10 14 10 16V18.5Q10 20.5 8 20.5H5Q3 20.5 3 18.5V16Q3 14 5 14Z M16 14H19Q21 14 21 16V18.5Q21 20.5 19 20.5H16Q14 20.5 14 18.5V16Q14 14 16 14Z M12 10V12H6.5V14 M12 12H17.5V14"), listOf())
    val Brain = icon("brain", listOf("M12 6C11 2.5 6 3 5.5 7Q2 8 4 12Q2.5 16 6 17Q6 21.5 10 20Q12 19.5 12 17V6C13 2.5 18 3 18.5 7Q22 8 20 12Q21.5 16 18 17Q18 21.5 14 20Q12 19.5 12 17 M5.5 7Q8.5 7 8.5 10 M4 12Q7 11 8 14 M18.5 7Q15.5 7 15.5 10 M20 12Q17 11 16 14"), listOf())
    val Camera = icon("camera", listOf("M8 6.5L9 3.5H15L16 6.5H17Q20.5 6.5 20.5 10V16.5Q20.5 20 17 20H7Q3.5 20 3.5 16.5V10Q3.5 6.5 7 6.5Z", "M8.5 13a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0Z"), listOf())
    val Chat = icon("chat", listOf("M12 3.5C17.5 3.5 20.5 6 20.5 11C20.5 16 17 18 12 18H10L5 20.5L5.5 16C4 14.5 3.5 13 3.5 11C3.5 6 6.5 3.5 12 3.5Z"), listOf())
    val Chats = icon("chats", listOf("M15 14.5C14 16 12 16.5 9 16.5H7L3.5 19L4 14.5Q3 13 3 10.5Q3 5 9 5H10 M15 3.5Q21 3.5 21 9Q21 11.5 19.5 13L20 16L16.5 14H15Q9 14 9 9Q9 3.5 15 3.5Z"), listOf())
    val CheckCircle = icon("check-circle", listOf("M20.5 12C20.5 17.5 17.5 20.5 12 20.5C6.5 20.5 3.5 17.5 3.5 12C3.5 6.5 6.5 3.5 12 3.5C17.5 3.5 20.5 6.5 20.5 12Z M7.5 12L10.5 15L16.5 8.5"), listOf())
    val Check = icon("check", listOf("M4.5 12L9.5 17L19.5 6.5"), listOf())
    val ChevronDown = icon("chevron-down", listOf("M6 9L12 15L18 9"), listOf())
    val ChevronLeft = icon("chevron-left", listOf("M15 6L9 12L15 18"), listOf())
    val ChevronRight = icon("chevron-right", listOf("M9 6L15 12L9 18"), listOf())
    val ChevronUp = icon("chevron-up", listOf("M6 15L12 9L18 15"), listOf())
    val ChevronsUpDown = icon("chevrons-up-down", listOf("M8 8L12 4L16 8 M8 16L12 20L16 16"), listOf())
    val Close = icon("close", listOf("M6 6L18 18 M18 6L6 18"), listOf())
    val Command = icon("command", listOf("M4.5 6.5L10 12L4.5 17.5 M12.5 18H20"), listOf())
    val Compose = icon("compose", listOf("M11 4H8Q3.5 4 3.5 8.5V16Q3.5 20.5 8 20.5H15.5Q20 20.5 20 16V13 M9 11.5L16.3 4.2Q17.5 3 18.7 4.2L19.8 5.3Q21 6.5 19.8 7.7L12.5 15L8 16Z M15 5.5L18.5 9"), listOf())
    val Copy = icon("copy", listOf("M8 6.5Q8 3.5 11 3.5H17Q20.5 3.5 20.5 7V13Q20.5 16 17.5 16 M7 8H13Q16 8 16 11V17Q16 20.5 12.5 20.5H7Q3.5 20.5 3.5 17V11.5Q3.5 8 7 8Z"), listOf())
    val Download = icon("download", listOf("M12 3.5V15 M7.5 10.5L12 15L16.5 10.5 M4.5 20H19.5"), listOf())
    val Edit = icon("edit", listOf("M5 14.5L15.2 4.3Q16.7 2.8 18.2 4.3L19.7 5.8Q21.2 7.3 19.7 8.8L9.5 19L3.5 20.5Z M13.5 6L18 10.5 M5 14.5L9.5 19"), listOf())
    val External = icon("external", listOf("M11 4H8Q3.5 4 3.5 8.5V16Q3.5 20.5 8 20.5H15.5Q20 20.5 20 16V13 M11 13L20 4 M14.5 3.5H20.5V9.5"), listOf())
    val File = icon("file", listOf("M13.5 3.5H8Q4.5 3.5 4.5 7V17Q4.5 20.5 8 20.5H16Q19.5 20.5 19.5 17V9L13.5 3.5Z M13 4V7.5Q13 10 15.5 10H19"), listOf())
    val Filter = icon("filter", listOf("M4 6H20 M7 12H17 M10 18H14"), listOf())
    val ImageUpload = icon("image-upload", listOf("M12 4H8Q3.5 4 3.5 8.5V16Q3.5 20.5 8 20.5H16Q20.5 20.5 20.5 16V13 M4 17L8.5 12L13 16L15.5 13.5 M18 10V3.5 M15 6.5L18 3.5L21 6.5"), listOf("M7 8a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z"))
    val Info = icon("info", listOf("M20.5 12C20.5 17.5 17.5 20.5 12 20.5C6.5 20.5 3.5 17.5 3.5 12C3.5 6.5 6.5 3.5 12 3.5C17.5 3.5 20.5 6.5 20.5 12Z M10.5 11H12V16H13.5"), listOf("M11 7.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z"))
    val Key = icon("key", listOf("M14 14L7.5 20.5H3.5V16.5L10 10 M7 13L9.5 15.5 M20.5 8.5Q20.5 13.5 15.5 13.5Q10.5 13.5 10.5 8.5Q10.5 3.5 15.5 3.5Q20.5 3.5 20.5 8.5Z"), listOf("M15 8a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z"))
    val LogIn = icon("log-in", listOf("M13 3.5H16Q20 3.5 20 7.5V16.5Q20 20.5 16 20.5H13 M3.5 12H14.5 M10 7.5L14.5 12L10 16.5"), listOf())
    val LogOut = icon("log-out", listOf("M11 3.5H8Q4 3.5 4 7.5V16.5Q4 20.5 8 20.5H11 M10 12H20.5 M16 7.5L20.5 12L16 16.5"), listOf())
    val Monitor = icon("monitor", listOf("M8 3.5H16Q20.5 3.5 20.5 8V12Q20.5 16 16 16H8Q3.5 16 3.5 12V8Q3.5 3.5 8 3.5Z M12 16V20.5 M8 20.5H16"), listOf())
    val More = icon("more", listOf(), listOf("M3.6 12a1.4 1.4 0 1 0 2.8 0a1.4 1.4 0 1 0 -2.8 0Z", "M10.6 12a1.4 1.4 0 1 0 2.8 0a1.4 1.4 0 1 0 -2.8 0Z", "M17.6 12a1.4 1.4 0 1 0 2.8 0a1.4 1.4 0 1 0 -2.8 0Z"))
    val Other = icon("other", listOf("M14 4C16 3 18 3.5 19 4L15 8L16 11L19 12L20.5 10.5C21 14 18 17 14.5 15.5L9.5 20Q8 21.5 6.5 20L4 17.5Q2.5 16 4 14.5L9 10C7.5 6.5 10.5 3 14 4Z"), listOf())
    val PanelClose = icon("panel-close", listOf("M8 4H16Q20.5 4 20.5 8.5V15.5Q20.5 20 16 20H8Q3.5 20 3.5 15.5V8.5Q3.5 4 8 4Z M14.5 4.5V19.5 M7 12H12 M9.5 9L6.5 12L9.5 15"), listOf())
    val PanelOpen = icon("panel-open", listOf("M8 4H16Q20.5 4 20.5 8.5V15.5Q20.5 20 16 20H8Q3.5 20 3.5 15.5V8.5Q3.5 4 8 4Z M14.5 4.5V19.5 M6.5 12H11.5 M9 9L12 12L9 15"), listOf())
    val Photo = icon("photo", listOf("M8 3.5H16Q20.5 3.5 20.5 8V16Q20.5 20.5 16 20.5H8Q3.5 20.5 3.5 16V8Q3.5 3.5 8 3.5Z M4 17L9 11.5L14 16.5L17 13.5L20.5 17"), listOf("M14.3 8a1.2 1.2 0 1 0 2.4 0a1.2 1.2 0 1 0 -2.4 0Z"))
    val Plug = icon("plug", listOf("M8.5 3.5V8 M15.5 3.5V8 M6 8H18V11Q18 16 12 16Q6 16 6 11Z M12 16V18Q12 20.5 15 20.5H17"), listOf())
    val Plus = icon("plus", listOf("M12 4.5V19.5 M4.5 12H19.5"), listOf())
    val Power = icon("power", listOf("M12 3.5V11 M7 5.5C4.5 7 3.5 9 3.5 12C3.5 17.5 6.5 20.5 12 20.5C17.5 20.5 20.5 17.5 20.5 12C20.5 9 19.5 7 17 5.5"), listOf())
    val Quote = icon("quote", listOf("M9.5 11H4.5V5.5H9.5V12Q9.5 16.5 5 18.5 M20 11H15V5.5H20V12Q20 16.5 15.5 18.5"), listOf())
    val Read = icon("read", listOf("M18.5 10V7L14.5 3.5H8Q4.5 3.5 4.5 7V17Q4.5 20.5 8 20.5H12 M13.5 3.7V8H18 M8 11H11 M8 14.5H10", "M12.5 16.5Q16.5 10.5 20.5 16.5Q16.5 22.5 12.5 16.5Z"), listOf("M15.6 16.5a0.9 0.9 0 1 0 1.8 0a0.9 0.9 0 1 0 -1.8 0Z"))
    val Received = icon("received", listOf("M12 3.5V14 M7.5 10L12 14.5L16.5 10 M4 15V17Q4 20.5 7.5 20.5H16.5Q20 20.5 20 17V15"), listOf())
    val Refresh = icon("refresh", listOf("M20 9Q18.5 3.5 12 3.5Q7.5 3.5 5 7 M20 4V9H15 M4 15Q5.5 20.5 12 20.5Q16.5 20.5 19 17 M4 20V15H9"), listOf())
    val Retry = icon("retry", listOf("M4 9H12Q20.5 9 20.5 15Q20.5 20.5 14 20.5H10 M9 3.5L3.5 9L9 14.5"), listOf())
    val Said = icon("said", listOf("M8 4H16Q20.5 4 20.5 8.5V14Q20.5 18 16.5 18H10L5 20.5V17.5Q3.5 16.5 3.5 14V8.5Q3.5 4 8 4Z M8 9H16 M8 13H13"), listOf())
    val Search = icon("search", listOf("M17.5 10.5C17.5 15 15 17 11 17C6.5 17 3.5 14.6 3.5 10.5C3.5 6.3 6.1 3.5 10.5 3.5C14.7 3.5 17.5 6 17.5 10.5Z M16 16L20.5 20.5"), listOf())
    val Send = icon("send", listOf("M4 9L19.5 3.5Q21 3 20.5 4.5L15 20L11 13Z M11 13L16 8"), listOf())
    val Server = icon("server", listOf("M8 3.5H16Q20.5 3.5 20.5 8V16Q20.5 20.5 16 20.5H8Q3.5 20.5 3.5 16V8Q3.5 3.5 8 3.5Z M4 12H20 M11 8H16 M11 16H16"), listOf("M6.5 8a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z", "M6.5 16a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z"))
    val Settings = icon("settings", listOf("M10 3.5H14L15 6L17.5 6.5L19.5 8.5L18.5 11L20.5 13V16L17.5 17L16.5 20L13.5 20.5L12 18.5L9.5 20.5L6.5 19L6 16.5L3.5 15V12L5.5 10.5L4.5 8L7 5.5L9 6Z", "M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0Z"), listOf())
    val ShieldCheck = icon("shield-check", listOf("M12 3.5Q16 6 20 6V12C20 16.5 16.5 19 12 20.5C7.5 19 4 16.5 4 12V6Q8 6 12 3.5Z M8 12L10.5 14.5L16 9"), listOf())
    val Sliders = icon("sliders", listOf("M6 3.5V7 M6 12V20.5 M18 3.5V12 M18 17V20.5", "M5.5 7h1a1.5 1.5 0 0 1 1.5 1.5v2a1.5 1.5 0 0 1 -1.5 1.5h-1a1.5 1.5 0 0 1 -1.5 -1.5v-2a1.5 1.5 0 0 1 1.5 -1.5Z", "M17.5 12h1a1.5 1.5 0 0 1 1.5 1.5v2a1.5 1.5 0 0 1 -1.5 1.5h-1a1.5 1.5 0 0 1 -1.5 -1.5v-2a1.5 1.5 0 0 1 1.5 -1.5Z"), listOf())
    val Sparks = icon("sparks", listOf("M9 7C10 11 11.5 12.5 15.5 13.5C11.5 14.5 10 16 9 20C8 16 6.5 14.5 3 13.5C6.5 12.5 8 11 9 7Z M17.5 3L18.3 5.7L21 6.5L18.3 7.3L17.5 10L16.7 7.3L14 6.5Z"), listOf())
    val Stop = icon("stop", listOf("M8.5 4.5H15.5Q19.5 4.5 19.5 8.5V15.5Q19.5 19.5 15.5 19.5H8.5Q4.5 19.5 4.5 15.5V8.5Q4.5 4.5 8.5 4.5Z"), listOf())
    val Think = icon("think", listOf("M12 3.5C13 8.5 15 10.5 20.5 12C15 13 13 15.5 12 20.5C10.5 15.5 8.5 13.5 3.5 12C8.5 10.5 10.5 8.5 12 3.5Z"), listOf())
    val Thread = icon("thread", listOf("M9.5 4.5H7Q3.5 4.5 3.5 8V16Q3.5 19.5 7 19.5H15L20.5 16V8Q20.5 4.5 17 4.5H14.5", "M7.5 9H10V12Q10 14.5 7.5 14.5 M14 9H16.5V12Q16.5 14.5 14 14.5"), listOf())
    val Ticket = icon("ticket", listOf("M7 5H17Q20.5 5 20.5 8.5V9Q17.5 9 17.5 12Q17.5 15 20.5 15V15.5Q20.5 19 17 19H7Q3.5 19 3.5 15.5V15Q6.5 15 6.5 12Q6.5 9 3.5 9V8.5Q3.5 5 7 5Z M13 8V9 M13 11.5V12.5 M13 15V16"), listOf())
    val Trash = icon("trash", listOf("M4 7H20 M9 6.5V3.5H15V6.5 M6 7L6.5 17Q6.5 20.5 10 20.5H14Q17.5 20.5 17.5 17L18 7 M10 11V16 M14 11V16"), listOf())
    val Unplug = icon("unplug", listOf("M3 12H5 M5 8H9V16H5Z M9 10H12 M9 14H12 M16 8H18Q21 8 21 12Q21 16 18 16H16Z M13.5 3.5L12.5 5.5 M13.5 20.5L14.5 18.5"), listOf())
    val UserPlus = icon("user-plus", listOf("M13 7.5Q13 11.5 9 11.5Q5 11.5 5 7.5Q5 3.5 9 3.5Q13 3.5 13 7.5Z M3.5 20.5V19Q3.5 15 9 15Q11.5 15 13 16 M18 11.5V18.5 M14.5 15H21"), listOf())
    val User = icon("user", listOf("M16 7.5Q16 11.5 12 11.5Q8 11.5 8 7.5Q8 3.5 12 3.5Q16 3.5 16 7.5Z M4.5 20.5V19Q4.5 15 12 15Q19.5 15 19.5 19V20.5"), listOf())
    val Users = icon("users", listOf("M12 8Q12 11.5 8.5 11.5Q5 11.5 5 8Q5 4.5 8.5 4.5Q12 4.5 12 8Z M3 20V18.5Q3 15 8.5 15Q14 15 14 18.5V20 M15 4.5Q19 4.5 19 8Q19 11.5 15 11.5 M17 15Q21 15.5 21 18.5V20"), listOf())
    val Web = icon("web", listOf("M20.5 12C20.5 17.5 17.5 20.5 12 20.5C6.5 20.5 3.5 17.5 3.5 12C3.5 6.5 6.5 3.5 12 3.5C17.5 3.5 20.5 6.5 20.5 12Z M12 3.5C7.5 8 7.5 16 12 20.5C16.5 16 16.5 8 12 3.5Z M4 12H20"), listOf())

    /** Every icon by its name in design/icons, as the core names them (activity rows). */
    val byName = mapOf("agent" to Agent, "arrow-down" to ArrowDown, "arrow-left" to ArrowLeft, "arrow-right" to ArrowRight, "arrow-up" to ArrowUp, "bot" to Bot, "boxes" to Boxes, "brain" to Brain, "camera" to Camera, "chat" to Chat, "chats" to Chats, "check-circle" to CheckCircle, "check" to Check, "chevron-down" to ChevronDown, "chevron-left" to ChevronLeft, "chevron-right" to ChevronRight, "chevron-up" to ChevronUp, "chevrons-up-down" to ChevronsUpDown, "close" to Close, "command" to Command, "compose" to Compose, "copy" to Copy, "download" to Download, "edit" to Edit, "external" to External, "file" to File, "filter" to Filter, "image-upload" to ImageUpload, "info" to Info, "key" to Key, "log-in" to LogIn, "log-out" to LogOut, "monitor" to Monitor, "more" to More, "other" to Other, "panel-close" to PanelClose, "panel-open" to PanelOpen, "photo" to Photo, "plug" to Plug, "plus" to Plus, "power" to Power, "quote" to Quote, "read" to Read, "received" to Received, "refresh" to Refresh, "retry" to Retry, "said" to Said, "search" to Search, "send" to Send, "server" to Server, "settings" to Settings, "shield-check" to ShieldCheck, "sliders" to Sliders, "sparks" to Sparks, "stop" to Stop, "think" to Think, "thread" to Thread, "ticket" to Ticket, "trash" to Trash, "unplug" to Unplug, "user-plus" to UserPlus, "user" to User, "users" to Users, "web" to Web)
}
