// Generated by scripts/icons.py from design/icons (ember's own icons, drawn for it by astra): do not edit.
import type { SVGProps } from "react";

/** An icon's props: its size (px), its line's weight, and whatever an <svg> takes. */
export type IconProps = Omit<SVGProps<SVGSVGElement>, "ref"> & { size?: number | string; strokeWidth?: number | string };

function Svg({ size = 24, strokeWidth = 1.75, children, ...rest }: IconProps & { children: React.ReactNode }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor"
      strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...rest}>
      {children}
    </svg>
  );
}

export function Agent(props: IconProps) {
  return <Svg {...props}><path d="M11 9.5H8Q3.5 9.5 3.5 13.5V17Q3.5 20.5 8 20.5H11Q15.5 20.5 15.5 17V13.5 M14 10L20.5 3.5 M15.5 3.5H20.5V8.5" /><circle cx="7" cy="15" r="1" fill="currentColor" stroke="none" /><circle cx="12" cy="15" r="1" fill="currentColor" stroke="none" /></Svg>;
}

export function Archive(props: IconProps) {
  return <Svg {...props}><path d="M4.5 4H19.5Q20.5 4 20.5 5V7.5Q20.5 8.5 19.5 8.5H4.5Q3.5 8.5 3.5 7.5V5Q3.5 4 4.5 4Z M5 8.5V17Q5 20.5 8.5 20.5H15.5Q19 20.5 19 17V8.5 M10 12.5H14" /></Svg>;
}

export function ArrowDown(props: IconProps) {
  return <Svg {...props}><path d="M12 4V20 M6 14L12 20L18 14" /></Svg>;
}

export function ArrowLeft(props: IconProps) {
  return <Svg {...props}><path d="M20 12H4 M10 6L4 12L10 18" /></Svg>;
}

export function ArrowRight(props: IconProps) {
  return <Svg {...props}><path d="M4 12H20 M14 6L20 12L14 18" /></Svg>;
}

export function ArrowUpRight(props: IconProps) {
  return <Svg {...props}><path d="M5 19L18.5 5.5 M9.5 5H19V14.5" /></Svg>;
}

export function ArrowUp(props: IconProps) {
  return <Svg {...props}><path d="M12 20V4 M6 10L12 4L18 10" /></Svg>;
}

export function Bell(props: IconProps) {
  return <Svg {...props}><path d="M12 3V5 M6.5 17V11Q6.5 5 12 5Q17.5 5 17.5 11V17 M4.5 17H19.5 M10 20.5H14" /></Svg>;
}

export function Bot(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5V6 M12 6C18 6 20.5 8 20.5 12V16C20.5 19 17.5 20.5 12 20.5C6.5 20.5 3.5 19 3.5 16L4 12C4 8 6.5 6 12 6Z M9.5 17H14.5" /><circle cx="8.5" cy="12" r="1.25" fill="currentColor" stroke="none" /><circle cx="15.5" cy="12" r="1.25" fill="currentColor" stroke="none" /></Svg>;
}

export function Boxes(props: IconProps) {
  return <Svg {...props}><path d="M9 3.5H15Q17 3.5 17 5.5V8Q17 10 15 10H9Q7 10 7 8V5.5Q7 3.5 9 3.5Z M5 14H8Q10 14 10 16V18.5Q10 20.5 8 20.5H5Q3 20.5 3 18.5V16Q3 14 5 14Z M16 14H19Q21 14 21 16V18.5Q21 20.5 19 20.5H16Q14 20.5 14 18.5V16Q14 14 16 14Z M12 10V12H6.5V14 M12 12H17.5V14" /></Svg>;
}

export function Brain(props: IconProps) {
  return <Svg {...props}><path d="M12 6.5C12 2.5 6 2.5 6 7C3 7 2.5 12 5 13.5C3.5 17 6 21 9 20.5Q12 20.5 12 17V6.5C12 2.5 18 2.5 18 7C21 7 21.5 12 19 13.5C20.5 17 18 21 15 20.5Q12 20.5 12 17 M6 7Q8.5 7 8.5 9.5 M18 7Q15.5 7 15.5 9.5" /></Svg>;
}

export function Camera(props: IconProps) {
  return <Svg {...props}><path d="M8 6.5L9 3.5H15L16 6.5H17Q20.5 6.5 20.5 10V16.5Q20.5 20 17 20H7Q3.5 20 3.5 16.5V10Q3.5 6.5 7 6.5Z" /><circle cx="12" cy="13" r="3.5" /></Svg>;
}

export function Chat(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5C17.5 3.5 20.5 6 20.5 11C20.5 16 17 18 12 18H10L5 20.5L5.5 16C4 14.5 3.5 13 3.5 11C3.5 6 6.5 3.5 12 3.5Z" /></Svg>;
}

export function Chats(props: IconProps) {
  return <Svg {...props}><path d="M8 5V4.5Q8 3 10 3H17Q20.5 3 20.5 6.5V11Q20.5 13 18.5 13.5 M7 8H12.5Q16 8 16 11.5V15Q16 18.5 12.5 18.5H9L4 21V17.5Q3 16.5 3 15V12Q3 8 7 8Z" /></Svg>;
}

export function CheckCircle(props: IconProps) {
  return <Svg {...props}><path d="M20.5 12C20.5 17.5 17.5 20.5 12 20.5C6.5 20.5 3.5 17.5 3.5 12C3.5 6.5 6.5 3.5 12 3.5C17.5 3.5 20.5 6.5 20.5 12Z M7.5 12L10.5 15L16.5 8.5" /></Svg>;
}

export function Check(props: IconProps) {
  return <Svg {...props}><path d="M4.5 12L9.5 17L19.5 6.5" /></Svg>;
}

export function ChevronDown(props: IconProps) {
  return <Svg {...props}><path d="M6 9L12 15L18 9" /></Svg>;
}

export function ChevronLeft(props: IconProps) {
  return <Svg {...props}><path d="M15 6L9 12L15 18" /></Svg>;
}

export function ChevronRight(props: IconProps) {
  return <Svg {...props}><path d="M9 6L15 12L9 18" /></Svg>;
}

export function ChevronUp(props: IconProps) {
  return <Svg {...props}><path d="M6 15L12 9L18 15" /></Svg>;
}

export function ChevronsUpDown(props: IconProps) {
  return <Svg {...props}><path d="M8 8L12 4L16 8 M8 16L12 20L16 16" /></Svg>;
}

export function Close(props: IconProps) {
  return <Svg {...props}><path d="M6 6L18 18 M18 6L6 18" /></Svg>;
}

export function Command(props: IconProps) {
  return <Svg {...props}><path d="M4.5 6.5L10 12L4.5 17.5 M12.5 18H20" /></Svg>;
}

export function Compose(props: IconProps) {
  return <Svg {...props}><path d="M11 4H8Q3.5 4 3.5 8.5V16Q3.5 20.5 8 20.5H15.5Q20 20.5 20 16V13 M9 11.5L16.3 4.2Q17.5 3 18.7 4.2L19.8 5.3Q21 6.5 19.8 7.7L12.5 15L8 16Z M15 5.5L18.5 9" /></Svg>;
}

export function Copy(props: IconProps) {
  return <Svg {...props}><path d="M8 6.5Q8 3.5 11 3.5H17Q20.5 3.5 20.5 7V13Q20.5 16 17.5 16 M7 8H13Q16 8 16 11V17Q16 20.5 12.5 20.5H7Q3.5 20.5 3.5 17V11.5Q3.5 8 7 8Z" /></Svg>;
}

export function Cursor(props: IconProps) {
  return <Svg {...props}><path d="M5.5 3.5L18.5 10.5L12.5 12.5L10 18.5Z M12.5 12.5L18 18" /></Svg>;
}

export function Devices(props: IconProps) {
  return <Svg {...props}><path d="M12 15.5H6.5Q3 15.5 3 12V7Q3 3.5 6.5 3.5H15Q18.5 3.5 18.5 7V7.5 M8 20H12 M9.5 15.5V20 M17 10H19.5Q21.5 10 21.5 12V18.5Q21.5 20.5 19.5 20.5H17Q15 20.5 15 18.5V12Q15 10 17 10Z" /></Svg>;
}

export function Download(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5V15 M7.5 10.5L12 15L16.5 10.5 M4.5 20H19.5" /></Svg>;
}

export function Edit(props: IconProps) {
  return <Svg {...props}><path d="M5 14.5L15.2 4.3Q16.7 2.8 18.2 4.3L19.7 5.8Q21.2 7.3 19.7 8.8L9.5 19L3.5 20.5Z M13.5 6L18 10.5 M5 14.5L9.5 19" /></Svg>;
}

export function Expand(props: IconProps) {
  return <Svg {...props}><path d="M14.5 5H19V9.5 M18.5 5.5L13.5 10.5 M9.5 19H5V14.5 M5.5 18.5L10.5 13.5" /></Svg>;
}

export function External(props: IconProps) {
  return <Svg {...props}><path d="M11 4H8Q3.5 4 3.5 8.5V16Q3.5 20.5 8 20.5H15.5Q20 20.5 20 16V13 M11 13L20 4 M14.5 3.5H20.5V9.5" /></Svg>;
}

export function File(props: IconProps) {
  return <Svg {...props}><path d="M13.5 3.5H8Q4.5 3.5 4.5 7V17Q4.5 20.5 8 20.5H16Q19.5 20.5 19.5 17V9L13.5 3.5Z M13 4V7.5Q13 10 15.5 10H19" /></Svg>;
}

export function Filter(props: IconProps) {
  return <Svg {...props}><path d="M4 6H20 M7 12H17 M10 18H14" /></Svg>;
}

export function Hourglass(props: IconProps) {
  return <Svg {...props}><path d="M5.5 3H18.5 M5.5 21H18.5 M7 3V6.5Q7 9.5 12 12Q17 14.5 17 17.5V21 M17 3V6.5Q17 9.5 12 12Q7 14.5 7 17.5V21" /></Svg>;
}

export function ImageUpload(props: IconProps) {
  return <Svg {...props}><path d="M11.5 3.5H7Q3.5 3.5 3.5 7V17Q3.5 20.5 7 20.5H17Q20.5 20.5 20.5 17V13 M4 17L9 12L15 18 M17.5 11V3.5 M14 7L17.5 3.5L21 7" /></Svg>;
}

export function Info(props: IconProps) {
  return <Svg {...props}><path d="M20.5 12C20.5 17.5 17.5 20.5 12 20.5C6.5 20.5 3.5 17.5 3.5 12C3.5 6.5 6.5 3.5 12 3.5C17.5 3.5 20.5 6.5 20.5 12Z M10.5 11H12V16H13.5" /><circle cx="12" cy="7.5" r="1" fill="currentColor" stroke="none" /></Svg>;
}

export function Key(props: IconProps) {
  return <Svg {...props}><circle cx="15.5" cy="8.5" r="5" /><path d="M12 12L3.5 20.5 M5 19L7 21 M8 16L10 18" /></Svg>;
}

export function Landscape(props: IconProps) {
  return <Svg {...props}><path d="M6 9H18Q21 9 21 12V16Q21 19 18 19H6Q3 19 3 16V12Q3 9 6 9Z M8 5.5Q12 3 16.5 5.2 M14.8 3.4L16.5 5.2L14.3 6.4" /></Svg>;
}

export function LogIn(props: IconProps) {
  return <Svg {...props}><path d="M13 3.5H16Q20 3.5 20 7.5V16.5Q20 20.5 16 20.5H13 M3.5 12H14.5 M10 7.5L14.5 12L10 16.5" /></Svg>;
}

export function LogOut(props: IconProps) {
  return <Svg {...props}><path d="M11 3.5H8Q4 3.5 4 7.5V16.5Q4 20.5 8 20.5H11 M10 12H20.5 M16 7.5L20.5 12L16 16.5" /></Svg>;
}

export function Minus(props: IconProps) {
  return <Svg {...props}><path d="M4.5 12H19.5" /></Svg>;
}

export function Monitor(props: IconProps) {
  return <Svg {...props}><path d="M8 3.5H16Q20.5 3.5 20.5 8V12Q20.5 16 16 16H8Q3.5 16 3.5 12V8Q3.5 3.5 8 3.5Z M12 16V20.5 M8 20.5H16" /></Svg>;
}

export function More(props: IconProps) {
  return <Svg {...props}><circle cx="5" cy="12" r="1.4" fill="currentColor" stroke="none" /><circle cx="12" cy="12" r="1.4" fill="currentColor" stroke="none" /><circle cx="19" cy="12" r="1.4" fill="currentColor" stroke="none" /></Svg>;
}

export function Move(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5V20.5 M3.5 12H20.5 M9.5 6L12 3.5L14.5 6 M9.5 18L12 20.5L14.5 18 M6 9.5L3.5 12L6 14.5 M18 9.5L20.5 12L18 14.5" /></Svg>;
}

export function Other(props: IconProps) {
  return <Svg {...props}><path d="M4.43396 16.73762 L10.58579 10.58579 C12.00000 9.17157 9.66655 7.54523 11.71716 5.49462 L14.19203 3.01974 L15.95980 4.78751 L14.05061 6.69670 A2.3 2.3 0 0 0 17.30330 9.94939 L19.21249 8.04020 L20.98026 9.80797 L18.50538 12.28284 C16.45477 14.33345 14.82843 12.00000 13.41421 13.41421 L7.26238 19.56604 A2 2 0 0 1 4.43396 16.73762 Z" /></Svg>;
}

export function PanelClose(props: IconProps) {
  return <Svg {...props}><path d="M8 4H16Q20.5 4 20.5 8.5V15.5Q20.5 20 16 20H8Q3.5 20 3.5 15.5V8.5Q3.5 4 8 4Z M14.5 4.5V19.5 M7 12H12 M9.5 9L6.5 12L9.5 15" /></Svg>;
}

export function PanelOpen(props: IconProps) {
  return <Svg {...props}><path d="M8 4H16Q20.5 4 20.5 8.5V15.5Q20.5 20 16 20H8Q3.5 20 3.5 15.5V8.5Q3.5 4 8 4Z M14.5 4.5V19.5 M6.5 12H11.5 M9 9L12 12L9 15" /></Svg>;
}

export function Pause(props: IconProps) {
  return <Svg {...props}><path d="M7 5V19 M17 5V19" /></Svg>;
}

export function Photo(props: IconProps) {
  return <Svg {...props}><path d="M8 3.5H16Q20.5 3.5 20.5 8V16Q20.5 20.5 16 20.5H8Q3.5 20.5 3.5 16V8Q3.5 3.5 8 3.5Z M4 17L9 11.5L14 16.5L17 13.5L20.5 17" /><circle cx="15.5" cy="8" r="1.2" fill="currentColor" stroke="none" /></Svg>;
}

export function Play(props: IconProps) {
  return <Svg {...props}><path d="M7 5.8Q7 4.3 8.3 5L18.4 11Q19.6 12 18.4 13L8.3 19Q7 19.7 7 18.2Z" /></Svg>;
}

export function Plug(props: IconProps) {
  return <Svg {...props}><path d="M8.5 3.5V8 M15.5 3.5V8 M6 8H18V11Q18 16 12 16Q6 16 6 11Z M12 16V18Q12 20.5 15 20.5H17" /></Svg>;
}

export function Plus(props: IconProps) {
  return <Svg {...props}><path d="M12 4.5V19.5 M4.5 12H19.5" /></Svg>;
}

export function Power(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5V11 M7 5.5C4.5 7 3.5 9 3.5 12C3.5 17.5 6.5 20.5 12 20.5C17.5 20.5 20.5 17.5 20.5 12C20.5 9 19.5 7 17 5.5" /></Svg>;
}

export function Quote(props: IconProps) {
  return <Svg {...props}><path d="M9.5 11H4.5V5.5H9.5V12Q9.5 16.5 5 18.5 M20 11H15V5.5H20V12Q20 16.5 15.5 18.5" /></Svg>;
}

export function Read(props: IconProps) {
  return <Svg {...props}><path d="M13.5 3.5H8Q4.5 3.5 4.5 7V17Q4.5 20.5 8 20.5H16Q19.5 20.5 19.5 17V9L13.5 3.5Z M7 13Q12 6.5 17 13Q12 19.5 7 13Z" /><circle cx="12" cy="13" r="1" fill="currentColor" stroke="none" /></Svg>;
}

export function Received(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5V14 M7.5 10L12 14.5L16.5 10 M4 15V17Q4 20.5 7.5 20.5H16.5Q20 20.5 20 17V15" /></Svg>;
}

export function Redo(props: IconProps) {
  return <Svg {...props}><path d="M20 9H12Q3.5 9 3.5 15Q3.5 20.5 10 20.5H14 M15 3.5L20.5 9L15 14.5" /></Svg>;
}

export function Refresh(props: IconProps) {
  return <Svg {...props}><path d="M20 9Q18.5 3.5 12 3.5Q7.5 3.5 5 7 M20 4V9H15 M4 15Q5.5 20.5 12 20.5Q16.5 20.5 19 17 M4 20V15H9" /></Svg>;
}

export function Retry(props: IconProps) {
  return <Svg {...props}><path d="M4 9H12Q20.5 9 20.5 15Q20.5 20.5 14 20.5H10 M9 3.5L3.5 9L9 14.5" /></Svg>;
}

export function Said(props: IconProps) {
  return <Svg {...props}><path d="M8 4H16Q20.5 4 20.5 8.5V14Q20.5 18 16.5 18H10L5 20.5V17.5Q3.5 16.5 3.5 14V8.5Q3.5 4 8 4Z M8 9H16 M8 13H13" /></Svg>;
}

export function Scribble(props: IconProps) {
  return <Svg {...props}><path d="M3.5 17.5Q6 11 9 8Q12 5 12.5 7.5Q13 10 9.5 14.5Q7 18.5 10 18.5Q13 18.5 16.5 12.5Q18.5 9.5 20.5 11" /></Svg>;
}

export function Search(props: IconProps) {
  return <Svg {...props}><path d="M17.5 10.5C17.5 15 15 17 11 17C6.5 17 3.5 14.6 3.5 10.5C3.5 6.3 6.1 3.5 10.5 3.5C14.7 3.5 17.5 6 17.5 10.5Z M16 16L20.5 20.5" /></Svg>;
}

export function Send(props: IconProps) {
  return <Svg {...props}><path d="M4 9L19.5 3.5Q21 3 20.5 4.5L15 20L11 13Z M11 13L16 8" /></Svg>;
}

export function Server(props: IconProps) {
  return <Svg {...props}><path d="M8 3.5H16Q20.5 3.5 20.5 8V16Q20.5 20.5 16 20.5H8Q3.5 20.5 3.5 16V8Q3.5 3.5 8 3.5Z M4 12H20 M11 8H16 M11 16H16" /><circle cx="7.5" cy="8" r="1" fill="currentColor" stroke="none" /><circle cx="7.5" cy="16" r="1" fill="currentColor" stroke="none" /></Svg>;
}

export function Settings(props: IconProps) {
  return <Svg {...props}><path d="M10.5000 5.0000L10.5000 3.0000L13.5000 3.0000L13.5000 5.0000L15.8891 5.9896L17.3033 4.5754L19.4246 6.6967L18.0104 8.1109L19.0000 10.5000L21.0000 10.5000L21.0000 13.5000L19.0000 13.5000L18.0104 15.8891L19.4246 17.3033L17.3033 19.4246L15.8891 18.0104L13.5000 19.0000L13.5000 21.0000L10.5000 21.0000L10.5000 19.0000L8.1109 18.0104L6.6967 19.4246L4.5754 17.3033L5.9896 15.8891L5.0000 13.5000L3.0000 13.5000L3.0000 10.5000L5.0000 10.5000L5.9896 8.1109L4.5754 6.6967L6.6967 4.5754L8.1109 5.9896Z" /><circle cx="12" cy="12" r="3" /></Svg>;
}

export function ShieldCheck(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5Q16 6 20 6V12C20 16.5 16.5 19 12 20.5C7.5 19 4 16.5 4 12V6Q8 6 12 3.5Z M8 12L10.5 14.5L16 9" /></Svg>;
}

export function Sliders(props: IconProps) {
  return <Svg {...props}><path d="M6 3.5V7 M6 12V20.5 M18 3.5V12 M18 17V20.5" /><rect x="4" y="7" width="4" height="5" rx="1.5" /><rect x="16" y="12" width="4" height="5" rx="1.5" /></Svg>;
}

export function Sparks(props: IconProps) {
  return <Svg {...props}><path d="M9.5 8C10.5 12 12 13.5 16 14.5C12 15.5 10.5 17 9.5 21C8.5 17 7 15.5 3 14.5C7 13.5 8.5 12 9.5 8Z M17 3C17.5 5.5 18.5 6.5 21 7C18.5 7.5 17.5 8.5 17 11C16.5 8.5 15.5 7.5 13 7C15.5 6.5 16.5 5.5 17 3Z" /></Svg>;
}

export function Square(props: IconProps) {
  return <Svg {...props}><path d="M8 4.5H16Q19.5 4.5 19.5 8V16Q19.5 19.5 16 19.5H8Q4.5 19.5 4.5 16V8Q4.5 4.5 8 4.5Z" /></Svg>;
}

export function Stop(props: IconProps) {
  return <Svg {...props}><path d="M8.5 4.5H15.5Q19.5 4.5 19.5 8.5V15.5Q19.5 19.5 15.5 19.5H8.5Q4.5 19.5 4.5 15.5V8.5Q4.5 4.5 8.5 4.5Z" /></Svg>;
}

export function Text(props: IconProps) {
  return <Svg {...props}><path d="M5 7V4.5H19V7 M12 4.5V19.5 M9 19.5H15" /></Svg>;
}

export function Think(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5C13 8.5 15 10.5 20.5 12C15 13 13 15.5 12 20.5C10.5 15.5 8.5 13.5 3.5 12C8.5 10.5 10.5 8.5 12 3.5Z" /></Svg>;
}

export function Thread(props: IconProps) {
  return <Svg {...props}><path d="M12 3.5C6.5 3.5 3.5 6 3.5 11C3.5 16 6.5 18.5 12 18.5H14L19.5 20.5L18.5 16.5Q20.5 14.5 20.5 11C20.5 6 17.5 3.5 12 3.5Z M8 7.5H16 M8 11H16 M8 14.5H13" /></Svg>;
}

export function Ticket(props: IconProps) {
  return <Svg {...props}><path d="M5.5 5H18.5Q20.5 5 20.5 7V9.5A2.5 2.5 0 0 0 20.5 14.5V17Q20.5 19 18.5 19H5.5Q3.5 19 3.5 17V14.5A2.5 2.5 0 0 0 3.5 9.5V7Q3.5 5 5.5 5Z M14 8.5V15.5" /></Svg>;
}

export function Trash(props: IconProps) {
  return <Svg {...props}><path d="M4 7H20 M9 6.5V3.5H15V6.5 M6 7L6.5 17Q6.5 20.5 10 20.5H14Q17.5 20.5 17.5 17L18 7 M10 11V16 M14 11V16" /></Svg>;
}

export function Unplug(props: IconProps) {
  return <Svg {...props}><path d="M8.5 3.5V8 M15.5 3.5V6 M6 8H12 M18 11V12Q18 17 12 17Q6 17 6 12V8 M12 17V20.5 M3.5 20.5L20.5 3.5" /></Svg>;
}

export function UserPlus(props: IconProps) {
  return <Svg {...props}><path d="M13 7.5Q13 11.5 9 11.5Q5 11.5 5 7.5Q5 3.5 9 3.5Q13 3.5 13 7.5Z M3.5 20.5V19Q3.5 15 9 15Q11.5 15 13 16 M18 11.5V18.5 M14.5 15H21" /></Svg>;
}

export function User(props: IconProps) {
  return <Svg {...props}><path d="M16 7.5Q16 11.5 12 11.5Q8 11.5 8 7.5Q8 3.5 12 3.5Q16 3.5 16 7.5Z M4.5 20.5V19Q4.5 15 12 15Q19.5 15 19.5 19V20.5" /></Svg>;
}

export function Users(props: IconProps) {
  return <Svg {...props}><path d="M12 8Q12 11.5 8.5 11.5Q5 11.5 5 8Q5 4.5 8.5 4.5Q12 4.5 12 8Z M3 20V18.5Q3 15 8.5 15Q14 15 14 18.5V20 M15 4.5Q19 4.5 19 8Q19 11.5 15 11.5 M17 15Q21 15.5 21 18.5V20" /></Svg>;
}

export function Web(props: IconProps) {
  return <Svg {...props}><path d="M20.5 12C20.5 17.5 17.5 20.5 12 20.5C6.5 20.5 3.5 17.5 3.5 12C3.5 6.5 6.5 3.5 12 3.5C17.5 3.5 20.5 6.5 20.5 12Z M12 3.5C7.5 8 7.5 16 12 20.5C16.5 16 16.5 8 12 3.5Z M4 12H20" /></Svg>;
}

/** Every icon by its name in design/icons, as the core names them (activity rows). */
export const ICONS: Record<string, (props: IconProps) => React.JSX.Element> = {
  "agent": Agent,
  "archive": Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "arrow-up": ArrowUp,
  "bell": Bell,
  "bot": Bot,
  "boxes": Boxes,
  "brain": Brain,
  "camera": Camera,
  "chat": Chat,
  "chats": Chats,
  "check-circle": CheckCircle,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-up-down": ChevronsUpDown,
  "close": Close,
  "command": Command,
  "compose": Compose,
  "copy": Copy,
  "cursor": Cursor,
  "devices": Devices,
  "download": Download,
  "edit": Edit,
  "expand": Expand,
  "external": External,
  "file": File,
  "filter": Filter,
  "hourglass": Hourglass,
  "image-upload": ImageUpload,
  "info": Info,
  "key": Key,
  "landscape": Landscape,
  "log-in": LogIn,
  "log-out": LogOut,
  "minus": Minus,
  "monitor": Monitor,
  "more": More,
  "move": Move,
  "other": Other,
  "panel-close": PanelClose,
  "panel-open": PanelOpen,
  "pause": Pause,
  "photo": Photo,
  "play": Play,
  "plug": Plug,
  "plus": Plus,
  "power": Power,
  "quote": Quote,
  "read": Read,
  "received": Received,
  "redo": Redo,
  "refresh": Refresh,
  "retry": Retry,
  "said": Said,
  "scribble": Scribble,
  "search": Search,
  "send": Send,
  "server": Server,
  "settings": Settings,
  "shield-check": ShieldCheck,
  "sliders": Sliders,
  "sparks": Sparks,
  "square": Square,
  "stop": Stop,
  "text": Text,
  "think": Think,
  "thread": Thread,
  "ticket": Ticket,
  "trash": Trash,
  "unplug": Unplug,
  "user-plus": UserPlus,
  "user": User,
  "users": Users,
  "web": Web,
};
